---
layout: post
title: NWAV52
date: 2024-10-13 21:30:00 -0600
categories:
  - Conferences
  - Presentations
  - Research
redirect_from: 
  - "/nwav52"
  - "/nwav2024"
---

This weekend, I'm at the 52nd New Ways of Analyzing Variation conference in Miami Beach, Florida. See below for summaries and files from my two presentations.

## Friday's presentation on prelaterals in Georgia English 

:::callout-tip
Download the slides [here](/downloads/241108-NWAV2024_GA-Prelats.pptx)!
:::

My research team, including Jon Forrest, Peggy Renwick, and Lelia Glass, presented yet again at NWAV with our talk called "Natural Class Reorganization over Apparent Time by Prelateral /u/ and /oʊ/ in Georgia." We focused on prelateral vowels and how they've changed over time. Focusing just on /ul/ and /ol/, what we're calling [<sc>spool</sc> and <sc>jolt</sc>](/blog/extending-wells-lexical-sets-to-prelateral-vowels), we found that their relationship with their preobstruent counterparts has changed over time in Georgia English. Earlier generations had them slightly backer than their preobstruent counterparts, likely due to mere articulatory consequences. Evidence for this comes from the fact that <sc>spool</sc> is as front as <sc>boot</sc> in our oldest speakers. Later generations separate them quite a lot. For Black speakers it was seen in Gen Zers as they began fronting <sc>boot</sc>; for White speakers it was as the prelateral vowels backed even more. We therefore describe a reorganization of natural classes and the birth of a new natural class, prelaterals, in this speech community. 

## Saturday's presentation on /ls/ and /lθ/ closure durations

:::callout-tip
Download the slides [here](/downloads/241109-NWAV_ClosureDurations.pdf)!
:::

Hallie Davidson is working with me on our project called, "Social Meaning of Closure Duration in the Affrication of /ls/ and /lθ/ in Utah English." In some previous work, I noticed that some people in Utah have closures in /lθ/ clusters as in *health*, *filth*, or *wealth* and that there might be some correlations between longer closures and membership in some social groups. Hallie is testing that specifically by setting up a matched-guise test and seeing if people respond differently to longer durations. This is a "Project Launch" poster, so we welcome any feedback on what questions to ask or how to ensure that our recordings are as natural as possible. We suspect that longer closures will index some social meaning among Utahns. If we do find that, this might be the first time that that particular acoustic cue---closure durations---have shown to be socially meaningful in a language that doesn't have geminate stops! 

