{
  "hash": "0ecf29122ca3154ffbfc8a2bc62bd9ea",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Multinomial Logistic Regression\"\nauthor: \"Joey Stanley\"\ndate: 2025-08-04 10:46:00 -0600\ndate-modified: last-modified\ncategories:\n  - How-to Guides\nimage: elsewheres.png\nreference-location: margin\ncitation-location: margin\ndraft: TRUE\n---\n\nRecently, I've been finding myself needing to model categorical dependent variables, which means I need to run a multinomial logistic regression model. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   4.0.0     ✔ tibble    3.3.0\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.0.4     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmetadata <- readxl::read_excel(\"/Users/joeystan/Desktop/Projects/Phonic/data/progress.xlsx\", sheet = \"metadata\", skip = 1) |>\n  \n  # Get just the responses I want\n  filter(is.na(exclude)) |>\n  select(speaker_id, gender, ethnicity, yob, church, urban_or_rural) |>\n  mutate(state = str_sub(speaker_id, 7,8), \n         .after = speaker_id) |>\n  mutate(yob = as.numeric(yob)) |>\n  print()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNew names:\n• `urban_vs_rural` -> `urban_vs_rural...22`\n• `state_has_accent` -> `state_has_accent...23`\n• `mormonese` -> `mormonese...25`\n• `comments` -> `comments...30`\n• `mormonese` -> `mormonese...32`\n• `comments` -> `comments...37`\n• `urban_vs_rural` -> `urban_vs_rural...40`\n• `state_has_accent` -> `state_has_accent...41`\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 312 × 7\n   speaker_id          state gender      ethnicity   yob church   urban_or_rural\n   <chr>               <chr> <chr>       <chr>     <dbl> <chr>    <chr>         \n 1 PhonicID002-Gavin   ID    male        white      2003 non-mem… small town    \n 2 PhonicID003-Damon   ID    male        white      1976 non-mem… suburb        \n 3 PhonicID004-Ricky   ID    male        white      1979 non-mem… small town    \n 4 PhonicID006-Jade    ID    female      white      1999 non-mem… rural         \n 5 PhonicID007-Meghan  ID    female      white      1998 non-mem… rural         \n 6 PhonicID008-Brandi  ID    female      white      1991 non-mem… small town    \n 7 PhonicID010-Bianca  ID    female      white      1994 non-mem… small town    \n 8 PhonicID011-Riley   ID    genderqueer white      1998 non-mem… rural         \n 9 PhonicID012-Allen   ID    male        white      1988 inactive small town    \n10 PhonicID013-Arianna ID    female      white      2001 active   suburb        \n# ℹ 302 more rows\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmountain <- read_csv(\"/Users/joeystan/Desktop/mountain/data/final_classifications.csv\", show_col_types = FALSE) |> \n  inner_join(metadata, by = \"speaker_id\") |> \n  filter(!is.na(realization),\n         !word %in% c(\"botany\", \"mutiny\", # same foot but multisyllabic\n                      \"bulletin\", # not the same foot\n                      \"threaten\", \"whiten\", \"written\")) |>  # polymorphemic\n  \n  mutate(gender3 = fct_collapse(gender, \"male\" = \"male\", \"female\" = \"female\", other_level = \"other\"), \n         .after = gender) |>\n  mutate(realization = factor(realization, levels = c(\"standard\", \"utah\", \"hyperarticulated\")),\n         state = factor(state, levels = c(\"ZZ\", \"UT\", \"ID\", \"MT\", \"WY\"))) |> \n  \n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3,553 × 10\n   speaker_id      word  realization state gender gender3 ethnicity   yob church\n   <chr>           <chr> <fct>       <fct> <chr>  <fct>   <chr>     <dbl> <chr> \n 1 PhonicID002-Ga… butt… standard    ID    male   male    white      2003 non-m…\n 2 PhonicID002-Ga… cott… standard    ID    male   male    white      2003 non-m…\n 3 PhonicID002-Ga… curt… standard    ID    male   male    white      2003 non-m…\n 4 PhonicID002-Ga… kitt… hyperartic… ID    male   male    white      2003 non-m…\n 5 PhonicID002-Ga… latin standard    ID    male   male    white      2003 non-m…\n 6 PhonicID002-Ga… rott… standard    ID    male   male    white      2003 non-m…\n 7 PhonicID002-Ga… satin standard    ID    male   male    white      2003 non-m…\n 8 PhonicID003-Da… butt… standard    ID    male   male    white      1976 non-m…\n 9 PhonicID003-Da… cott… standard    ID    male   male    white      1976 non-m…\n10 PhonicID003-Da… curt… standard    ID    male   male    white      1976 non-m…\n# ℹ 3,543 more rows\n# ℹ 1 more variable: urban_or_rural <chr>\n```\n\n\n:::\n:::\n\n\n\n## mlogit\n\nThis is used in Chapter 13 of Levshina. But I can't get the data to be shaped the right way. [this](https://stats.oarc.ucla.edu/r/dae/multinomial-logistic-regression/) recommends {multinom} instead since it does not require a reshape. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(mlogit)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: dfidx\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"Fishing\", package = \"mlogit\")\nFishing\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        mode price.beach price.pier price.boat price.charter catch.beach\n1    charter     157.930    157.930    157.930       182.930      0.0678\n2    charter      15.114     15.114     10.534        34.534      0.1049\n3       boat     161.874    161.874     24.334        59.334      0.5333\n4       pier      15.134     15.134     55.930        84.930      0.0678\n5       boat     106.930    106.930     41.514        71.014      0.0678\n6    charter     192.474    192.474     28.934        63.934      0.5333\n7      beach      51.934     51.934    191.930       220.930      0.0678\n8    charter      15.134     15.134     21.714        56.714      0.0678\n9       boat      34.914     34.914     34.914        53.414      0.2537\n10      boat      28.314     28.314     28.314        46.814      0.2537\n11      pier      34.914     34.914     24.334        48.334      0.1049\n12      boat     312.144    312.144     16.722        51.722      0.5333\n13      pier      17.862     17.862      4.122        28.122      0.1049\n14      pier      15.134     15.134     55.930        84.930      0.0678\n15     beach      74.514     74.514     74.514        93.014      0.2537\n16      pier      33.534     33.534    123.930       152.930      0.0678\n17     beach      48.114     48.114     33.534        57.534      0.1049\n18      pier      33.462     33.462      7.722        31.722      0.1049\n19      boat     211.344    211.344     11.322        46.322      0.5333\n20      boat      49.062     49.062     11.322        35.322      0.1049\n21   charter     345.744    345.744     18.522        53.522      0.5333\n22   charter      88.062     88.062     20.322        44.322      0.1049\n23      boat     100.674    100.674     15.134        50.134      0.5333\n24   charter      28.314     28.314     19.734        43.734      0.1049\n25   charter      33.462     33.462     34.320        69.320      0.0678\n26     beach      67.784     67.784     17.862        52.862      0.5333\n27      pier      50.320     50.320     49.062        73.062      0.1049\n28      boat      72.462     72.462     74.320       109.320      0.0678\n29   charter      70.074     70.074     10.534        45.534      0.5333\n30   charter     131.274    131.274     19.734        54.734      0.5333\n31   charter      28.314     28.314     19.734        43.734      0.1049\n32   charter      49.062     49.062     11.322        35.322      0.1049\n33      boat      33.462     33.462      7.722        31.722      0.1049\n34     beach       9.522      9.522     78.292       107.292      0.0678\n35      pier      25.662     25.662      5.922        29.922      0.1049\n36   charter     144.144    144.144      7.722        42.722      0.5333\n37      pier     120.004    120.004    252.640       281.640      0.0678\n38      boat      25.648     25.648     80.608       105.608      0.2537\n39   charter     115.808    115.808     25.004        60.004      0.5333\n40      pier      32.604     32.604     68.640        97.640      0.0678\n41      boat      10.296     10.296     46.332        75.332      0.0678\n42   charter      10.296     10.296     54.912        89.912      0.0678\n43      boat     231.472    231.472     15.096        50.096      0.5333\n44   charter      59.248     59.248    186.208       211.208      0.2537\n45   charter     231.472    231.472     15.096        50.096      0.5333\n46      pier      19.896     19.896     89.532       118.532      0.0678\n47   charter     341.872    341.872     22.296        57.296      0.5333\n48   charter      80.608     80.608     17.404        52.404      0.5333\n49     beach      24.334     24.334     89.930       118.930      0.0678\n50     beach      11.322     11.322     93.092       122.092      0.0678\n51   charter     177.744    177.744      9.522        44.522      0.5333\n52      pier       5.922      5.922     48.692        77.692      0.0678\n53      boat     177.744    177.744      9.522        44.522      0.5333\n54      boat      70.074     70.074     10.534        45.534      0.5333\n55   charter      41.514     41.514     28.934        52.934      0.1049\n56   charter      21.714     21.714     15.134        39.134      0.1049\n57   charter     144.144    144.144      7.722        42.722      0.5333\n58      boat      25.662     25.662      5.922        29.922      0.1049\n59      boat     244.944    244.944     13.122        48.122      0.5333\n60   charter     144.144    144.144      7.722        42.722      0.5333\n61      pier       5.922      5.922     48.692        77.692      0.0678\n62      pier      93.092     93.092     93.092       118.092      0.0678\n63   charter     177.744    177.744      9.522        44.522      0.5333\n64      boat      41.262     41.262      9.522        33.522      0.1049\n65      pier       9.522      9.522     78.292       107.292      0.0678\n66   charter      76.944     76.944      4.122        39.122      0.5333\n67      boat     177.744    177.744      9.522        44.522      0.5333\n68   charter     177.744    177.744      9.522        44.522      0.5333\n69      boat     244.944    244.944     13.122        48.122      0.5333\n70      pier      33.462     33.462      7.722        31.722      0.1049\n71      boat      33.462     33.462      7.722        31.722      0.1049\n72   charter       5.922      5.922     25.662        60.662      0.0678\n73   charter     345.744    345.744     18.522        53.522      0.5333\n74      boat     244.944    244.944     13.122        48.122      0.5333\n75      boat      64.662     64.662     14.922        38.922      0.1049\n76     beach       9.522      9.522     78.292       107.292      0.0678\n77     beach      24.696     24.696    111.132       140.132      0.0678\n78      boat      33.892     33.892     33.892        58.892      0.0678\n79   charter     144.144    144.144      7.722        42.722      0.5333\n80      boat     110.544    110.544      5.922        40.922      0.5333\n81   charter      76.944     76.944      4.122        39.122      0.5333\n82     beach       7.722      7.722     63.492        92.492      0.0678\n83      boat     177.744    177.744      9.522        44.522      0.5333\n84      boat      17.862     17.862      4.122        28.122      0.1049\n85   charter      33.462     33.462     33.462        51.962      0.2537\n86      boat       8.514      8.514     39.474        64.474      0.2537\n87   charter      38.134     38.134     54.714        89.714      0.0678\n88      boat      24.334     24.334     34.914        69.914      0.0678\n89      pier     100.674    100.674     15.134        50.134      0.5333\n90      pier     104.214    104.214    104.214       122.714      0.2537\n91   charter     161.874    161.874     24.334        59.334      0.5333\n92   charter      48.114     48.114     33.534        57.534      0.1049\n93      boat      64.662     64.662     66.320       101.320      0.0678\n94   charter      72.462     72.462     74.320       109.320      0.0678\n95      boat     422.984    422.984    111.462       146.462      0.5333\n96   charter      56.862     56.862     58.320        93.320      0.0678\n97      boat      72.462     72.462     74.320       109.320      0.0678\n98   charter     210.566    210.566     49.740        79.240      0.0678\n99      pier      43.740     43.740     52.488        70.988      0.2537\n100    beach      31.740     31.740     38.088        56.588      0.2537\n101    beach      19.740     19.740     23.688        42.188      0.2537\n102     pier      31.740     31.740     38.088        56.588      0.2537\n103  charter      55.770     55.770     25.740        60.740      0.0678\n104  charter      42.770     42.770     19.740        54.740      0.0678\n105  charter     261.366    261.366     61.740        91.240      0.0678\n106  charter     268.702    268.702    146.770       181.770      0.5333\n107  charter      55.740     55.740    221.102       246.102      0.2537\n108  charter     159.766    159.766     37.740        67.240      0.0678\n109     pier      16.770     16.770     32.766        61.766      0.0678\n110     boat     125.902    125.902     68.770       103.770      0.5333\n111     boat      56.862     56.862     58.320        93.320      0.0678\n112  charter      25.662     25.662     26.320        61.320      0.0678\n113  charter      46.258     46.258     18.320        47.820      0.0678\n114    beach      42.320     42.320     42.320        60.820      0.2537\n115  charter      64.662     64.662     66.320       101.320      0.0678\n116  charter      42.320     42.320     41.262        65.262      0.1049\n117     boat      58.320     58.320     58.320        76.820      0.2537\n118  charter      77.234     77.234     73.002       108.002      0.0678\n119  charter     150.150    150.150     62.634        97.634      0.5333\n120  charter     135.634    135.634    267.552       296.552      0.0678\n121    beach      73.002     73.002     73.002        91.502      0.2537\n122     boat     205.270    205.270     94.740       129.740      0.0678\n123  charter      55.770     55.770     25.740        60.740      0.0678\n124    beach      61.740     61.740     74.088        92.588      0.2537\n125     boat     120.770    120.770     55.740        90.740      0.0678\n126  charter     146.770    146.770     67.740       102.740      0.0678\n127     pier      55.740     55.740     66.888        85.388      0.2537\n128  charter     134.366    134.366     31.740        61.240      0.0678\n129     pier      49.740     49.740     59.688        78.188      0.2537\n130     boat     205.270    205.270     94.740       129.740      0.0678\n131     boat     205.270    205.270     94.740       129.740      0.0678\n132  charter     107.770    107.770     49.740        84.740      0.0678\n133     boat     261.366    261.366     61.740        91.240      0.0678\n134     boat     108.966    108.966     25.740        55.240      0.0678\n135     boat     286.766    286.766     67.740        97.240      0.0678\n136     boat     375.802    375.802    205.270       240.270      0.5333\n137  charter      68.770     68.770     31.740        66.740      0.0678\n138  charter      68.770     68.770     31.740        66.740      0.0678\n139  charter      67.784     67.784     17.862        52.862      0.5333\n140  charter     186.184    186.184     49.062        84.062      0.5333\n141     boat      66.320     66.320     66.320        84.820      0.2537\n142  charter      38.184     38.184     10.062        45.062      0.5333\n143     boat      72.462     72.462     74.320       109.320      0.0678\n144  charter      49.062     49.062     50.320        85.320      0.0678\n145     boat     333.258    333.258     94.506       129.506      0.5333\n146  charter      85.698     85.698     60.306        84.306      0.1049\n147  charter     166.698    166.698    166.698       185.198      0.2537\n148  charter     252.858    252.858     71.706       106.706      0.5333\n149     boat     128.706    128.706    182.898       217.898      0.0678\n150  charter     212.658    212.658     60.306        95.306      0.5333\n151  charter     212.658    212.658     60.306        95.306      0.5333\n152  charter      92.058     92.058     26.106        61.106      0.5333\n153     boat     139.350    139.350     63.172        87.172      0.1049\n154     boat     109.350    109.350     49.572        73.572      0.1049\n155     boat     323.310    323.310     56.372        91.372      0.5333\n156     boat      71.214     71.214     71.214        96.214      0.0678\n157     boat      94.350     94.350     42.772        66.772      0.1049\n158  charter     109.350    109.350     49.572        73.572      0.1049\n159     pier      49.572     49.572    121.014       150.014      0.0678\n160  charter     206.310    206.310     35.972        70.972      0.5333\n161  charter     245.310    245.310     42.772        77.772      0.5333\n162  charter     206.310    206.310     35.972        70.972      0.5333\n163  charter      64.350     64.350    167.310       192.310      0.2537\n164    beach      42.772     42.772    104.414       133.414      0.0678\n165  charter     323.310    323.310     56.372        91.372      0.5333\n166    beach      15.572     15.572     38.014        67.014      0.0678\n167     boat      71.214     71.214     71.214        96.214      0.0678\n168     boat     104.414    104.414     94.350       123.850      0.0678\n169    beach     124.350    124.350    124.350       142.850      0.2537\n170  charter     104.414    104.414    104.414       129.414      0.0678\n171     boat     175.748    175.748    175.748       194.248      0.2537\n172     boat     335.340    335.340     72.900       107.900      0.5333\n173  charter     243.340    243.340     52.900        87.900      0.5333\n174    beach      22.372     22.372     54.614        83.614      0.0678\n175  charter     206.310    206.310     35.972        70.972      0.5333\n176  charter      29.172     29.172     64.350        99.350      0.0678\n177     boat     323.310    323.310     56.372        91.372      0.5333\n178  charter      35.972     35.972     79.350       114.350      0.0678\n179     boat     362.310    362.310     63.172        98.172      0.5333\n180  charter      71.214     71.214     64.350        93.850      0.0678\n181    beach      49.572     49.572    121.014       150.014      0.0678\n182  charter     151.008    151.008     32.604        67.604      0.5333\n183  charter     186.208    186.208     40.204        75.204      0.5333\n184     boat      92.058     92.058     26.106        61.106      0.5333\n185     boat      37.506     37.506     57.904        86.904      0.0678\n186  charter     132.258    132.258     37.506        72.506      0.5333\n187  charter     252.858    252.858     71.706       106.706      0.5333\n188     boat     252.858    252.858     71.706       106.706      0.5333\n189    beach      34.914     34.914     34.914        53.414      0.2537\n190  charter      63.004     63.004     92.848       127.848      0.0678\n191  charter     137.648    137.648     93.404       117.404      0.1049\n192  charter     221.408    221.408     47.804        82.804      0.5333\n193     boat     206.310    206.310     35.972        70.972      0.5333\n194     pier      21.714     21.714     21.714        40.214      0.2537\n195  charter      10.534     10.534     15.114        50.114      0.0678\n196  charter     206.310    206.310     35.972        70.972      0.5333\n197  charter     252.858    252.858     71.706       106.706      0.5333\n198     pier      75.504     75.504     75.504       100.504      0.0678\n199  charter      26.106     26.106     37.098        72.098      0.0678\n200  charter      22.704     22.704     20.898        50.398      0.0678\n201     boat      71.706     71.706    101.898       136.898      0.0678\n202    beach     117.306    117.306    181.104       210.104      0.0678\n203  charter     453.858    453.858    128.706       163.706      0.5333\n204     pier      26.106     26.106     40.304        69.304      0.0678\n205  charter     132.258    132.258     37.506        72.506      0.5333\n206     boat      69.498     69.498     69.498        87.998      0.2537\n207     boat      69.498     69.498     48.906        72.906      0.1049\n208     boat      70.448     70.448     47.804        71.804      0.1049\n209  charter     116.640    116.640    116.640       141.640      0.0678\n210     pier      47.804     47.804    100.640       129.640      0.0678\n211  charter      80.608     80.608     17.404        52.404      0.5333\n212  charter     115.248    115.248    362.208       387.208      0.2537\n213  charter     291.808    291.808     63.004        98.004      0.5333\n214     pier      32.604     32.604     68.640        97.640      0.0678\n215  charter      36.640     36.640     36.640        61.640      0.0678\n216  charter      39.474     39.474      5.934        40.934      0.5333\n217    beach     120.004    120.004    252.640       281.640      0.0678\n218  charter     100.674    100.674     15.134        50.134      0.5333\n219  charter     223.074    223.074     33.534        68.534      0.5333\n220  charter     161.874    161.874     24.334        59.334      0.5333\n221  charter     453.858    453.858    128.706       163.706      0.5333\n222  charter     252.858    252.858     71.706       106.706      0.5333\n223     boat     255.798    255.798    180.006       204.006      0.1049\n224  charter      71.706     71.706    110.704       139.704      0.0678\n225     boat      92.058     92.058     26.106        61.106      0.5333\n226  charter      81.648     81.648     55.404        79.404      0.1049\n227     pier      47.804     47.804    100.640       129.640      0.0678\n228  charter     221.408    221.408     47.804        82.804      0.5333\n229  charter      10.534     10.534     15.114        50.114      0.0678\n230     pier       5.922      5.922      5.922        30.922      0.0678\n231     pier      11.322     11.322     11.322        36.322      0.0678\n232     pier       6.290      6.290      6.290        35.290      0.0678\n233     boat      17.986     17.986     17.986        46.986      0.0678\n234  charter      17.986     17.986     17.986        42.986      0.0678\n235  charter      17.986     17.986     17.986        46.986      0.0678\n236     boat      45.186     45.186     45.186        70.186      0.0678\n237    beach      21.386     21.386     21.386        46.386      0.0678\n238    beach       9.522      9.522      9.522        34.522      0.0678\n239     boat     316.342    316.342     51.842        86.842      0.5333\n240     boat      32.242     32.242      5.922        34.922      0.0678\n241     pier       9.522      9.522      9.522        34.522      0.0678\n242     boat      11.322     11.322     11.322        36.322      0.0678\n243    beach       9.522      9.522      9.522        34.522      0.0678\n244    beach      71.442     71.442     13.122        42.122      0.0678\n245     boat      14.580     14.580     14.580        39.580      0.0678\n246  charter       8.580      8.580      8.580        33.580      0.0678\n247  charter      56.610     56.610     12.580        41.580      0.0678\n248  charter      18.580     18.580     18.580        43.580      0.0678\n249     pier       8.580      8.580      8.580        33.580      0.0678\n250     boat     359.022    359.022    666.110       691.110      0.2537\n251  charter      29.610     29.610      6.580        35.580      0.0678\n252     boat     135.110    135.110     20.610        55.610      0.5333\n253  charter       4.580      4.580      4.580        29.580      0.0678\n254     boat       6.580      6.580      6.580        31.580      0.0678\n255     boat      31.586     31.586     31.586        56.586      0.0678\n256  charter      24.786     24.786     24.786        49.786      0.0678\n257     pier      13.818     13.818     13.818        42.818      0.0678\n258  charter      30.618     30.618     30.618        59.618      0.0678\n259     boat     214.500    214.500      4.290        39.290      0.5333\n260     boat     264.500    264.500      5.290        40.290      0.5333\n261  charter       4.290      4.290      4.290        33.290      0.0678\n262    beach       4.122      4.122      4.122        29.122      0.0678\n263     pier       5.922      5.922      5.922        30.922      0.0678\n264    beach      71.442     71.442     13.122        42.122      0.0678\n265     boat       5.922      5.922      5.922        30.922      0.0678\n266     pier      15.870     15.870     15.870        40.870      0.0678\n267     boat       6.450      6.450      3.870        32.870      0.0678\n268     boat      12.580     12.580     12.580        37.580      0.0678\n269     boat       6.580      6.580      6.580        31.580      0.0678\n270     pier       6.580      6.580      6.580        31.580      0.0678\n271  charter       7.722      7.722      7.722        32.722      0.0678\n272     boat     164.500    164.500      3.290        38.290      0.5333\n273  charter       5.290      5.290      5.290        30.290      0.0678\n274     boat       3.290      3.290      3.290        32.290      0.0678\n275  charter       5.290      5.290      5.290        34.290      0.0678\n276     pier       2.290      2.290      2.290        31.290      0.0678\n277     boat     264.500    264.500      5.290        40.290      0.5333\n278  charter       7.290      7.290      7.290        36.290      0.0678\n279    beach      13.290     13.290     13.290        42.290      0.0678\n280  charter     214.500    214.500      4.290        39.290      0.5333\n281  charter       4.290      4.290      4.290        29.290      0.0678\n282  charter     166.212    166.212      7.290        31.290      0.1049\n283  charter       6.290      6.290      6.290        35.290      0.0678\n284     boat     189.012    189.012      8.290        32.290      0.1049\n285  charter     164.500    164.500      3.290        38.290      0.5333\n286  charter       4.290      4.290      4.290        33.290      0.0678\n287  charter     114.500    114.500      2.290        37.290      0.5333\n288     pier       2.290      2.290      2.290        31.290      0.0678\n289     pier      75.012     75.012     75.012        93.512      0.2537\n290     pier       4.290      4.290      4.290        33.290      0.0678\n291     boat     214.500    214.500      4.290        39.290      0.5333\n292     boat      75.012     75.012      3.290        27.290      0.1049\n293  charter      11.450     11.450      6.870        35.870      0.0678\n294  charter      31.450     31.450     18.870        47.870      0.0678\n295  charter      33.870     33.870     33.870        58.870      0.0678\n296     boat     843.186    843.186     53.686        88.686      0.5333\n297  charter     364.500    364.500      7.290        42.290      0.5333\n298  charter     314.500    314.500      6.290        41.290      0.5333\n299  charter       5.290      5.290      5.290        30.290      0.0678\n300     boat     264.500    264.500      5.290        40.290      0.5333\n301  charter       7.290      7.290      7.290        36.290      0.0678\n302     boat      97.812     97.812      4.290        28.290      0.1049\n303     pier       3.290      3.290      3.290        28.290      0.0678\n304    beach       8.290      8.290      8.290        33.290      0.0678\n305  charter      10.580     10.580     10.580        35.580      0.0678\n306    beach      11.186     11.186     11.186        36.186      0.0678\n307    beach      38.386     38.386     38.386        63.386      0.0678\n308     boat       8.580      8.580      8.580        33.580      0.0678\n309  charter      38.610     38.610      8.580        37.580      0.0678\n310  charter       4.290      4.290      4.290        29.290      0.0678\n311     boat       4.290      4.290      4.290        29.290      0.0678\n312  charter      75.012     75.012      3.290        27.290      0.1049\n313     boat     214.500    214.500      4.290        39.290      0.5333\n314     boat       5.290      5.290      5.290        30.290      0.0678\n315  charter     143.412    143.412      6.290        30.290      0.1049\n316  charter       4.290      4.290      4.290        29.290      0.0678\n317  charter       6.290      6.290      6.290        35.290      0.0678\n318     boat       6.290      6.290      6.290        31.290      0.0678\n319  charter       4.290      4.290      4.290        29.290      0.0678\n320     pier       3.290      3.290      3.290        28.290      0.0678\n321  charter      26.320     26.320      3.290        32.290      0.0678\n322     pier       4.290      4.290      4.290        29.290      0.0678\n323     pier       2.290      2.290      2.290        27.290      0.0678\n324     pier       2.290      2.290      2.290        27.290      0.0678\n325    beach       4.290      4.290      4.290        29.290      0.0678\n326     boat       8.290      8.290      8.290        33.290      0.0678\n327     boat       7.290      7.290      7.290        32.290      0.0678\n328     pier      13.290     13.290     13.290        38.290      0.0678\n329     boat       3.290      3.290      3.290        28.290      0.0678\n330     boat       6.290      6.290      6.290        31.290      0.0678\n331  charter      26.320     26.320      3.290        32.290      0.0678\n332     boat       4.290      4.290      4.290        29.290      0.0678\n333     boat       6.290      6.290      6.290        31.290      0.0678\n334  charter      74.610     74.610     16.580        45.580      0.0678\n335     pier       4.290      4.290      4.290        29.290      0.0678\n336  charter       6.290      6.290      6.290        31.290      0.0678\n337    beach       2.290      2.290      2.290        27.290      0.0678\n338     pier       5.290      5.290      5.290        30.290      0.0678\n339     boat       3.290      3.290      3.290        28.290      0.0678\n340     boat       2.290      2.290      2.290        27.290      0.0678\n341     boat      34.320     34.320      4.290        33.290      0.0678\n342  charter       6.290      6.290      6.290        31.290      0.0678\n343     boat       9.290      9.290      9.290        34.290      0.0678\n344    beach     306.820    306.820     42.320        77.320      0.5333\n345     boat      65.610     65.610    231.822       266.822      0.0678\n346     boat       8.290      8.290      8.290        33.290      0.0678\n347  charter     132.132    132.132     34.320        58.320      0.1049\n348  charter      26.320     26.320      3.290        32.290      0.0678\n349  charter       7.290      7.290      7.290        32.290      0.0678\n350     boat      51.450     51.450     30.870        59.870      0.0678\n351     boat      30.870     30.870     30.870        55.870      0.0678\n352     boat      12.870     12.870     12.870        37.870      0.0678\n353  charter      21.870     21.870     21.870        46.870      0.0678\n354    beach      24.786     24.786     24.786        49.786      0.0678\n355  charter      21.386     21.386     21.386        50.386      0.0678\n356  charter     455.950    455.950     41.450        76.450      0.5333\n357     boat      12.870     12.870     12.870        37.870      0.0678\n358  charter     119.262    119.262    235.950       260.950      0.2537\n359     boat      15.870     15.870     15.870        40.870      0.0678\n360     boat      24.870     24.870     24.870        49.870      0.0678\n361  charter      46.450     46.450     27.870        56.870      0.0678\n362    beach       4.122      4.122      4.122        29.122      0.0678\n363     pier       4.122      4.122      4.122        29.122      0.0678\n364     boat     130.832    130.832    130.832       155.832      0.0678\n365     boat     119.554    119.554     73.002        97.002      0.1049\n366     boat      45.402     45.402     74.354       109.354      0.0678\n367  charter      45.402     45.402     74.354       109.354      0.0678\n368     boat     119.554    119.554     73.002        97.002      0.1049\n369  charter      31.602     31.602     51.754        86.754      0.0678\n370  charter     106.714    106.714     31.602        66.602      0.5333\n371    beach      37.098     37.098     37.098        66.098      0.0678\n372     pier      20.898     20.898     20.898        49.898      0.0678\n373  charter     393.660    393.660    154.548       189.548      0.5333\n374  charter     177.660    177.660     69.748       104.748      0.5333\n375  charter      26.832     26.832     26.832        51.832      0.0678\n376  charter     110.032    110.032    110.032       135.032      0.0678\n377     boat     151.632    151.632    236.196       271.196      0.0678\n378     boat     511.596    511.596    328.432       352.432      0.1049\n379  charter     353.498    353.498    130.832       165.832      0.5333\n380     boat      68.432     68.432    106.596       141.596      0.0678\n381     pier      90.948     90.948     90.948       119.948      0.0678\n382     boat     132.990    132.990     90.948       114.948      0.1049\n383  charter      90.948     90.948    132.990       162.490      0.0678\n384  charter      65.016     65.016     26.574        61.574      0.5333\n385  charter     216.216    216.216     88.374       123.374      0.5333\n386     boat     319.302    319.302    247.860       271.860      0.1049\n387     boat     295.422    295.422    115.196       139.196      0.1049\n388     pier     150.174    150.174    170.586       199.586      0.0678\n389  charter     367.416    367.416    150.174       185.174      0.5333\n390  charter     170.774    170.774    218.856       253.856      0.0678\n391  charter      88.374     88.374    113.256       148.256      0.0678\n392    beach      47.174     47.174     53.586        82.586      0.0678\n393     pier     129.574    129.574    147.186       176.186      0.0678\n394     pier     108.974    108.974    123.786       152.786      0.0678\n395  charter     569.016    569.016    232.574       267.574      0.5333\n396  charter      88.374     88.374    100.386       129.386      0.0678\n397  charter     317.016    317.016    129.574       164.574      0.5333\n398  charter     106.596    106.596    168.448       193.448      0.2537\n399  charter     140.714    140.714    159.758       188.758      0.0678\n400     boat     171.396    171.396    140.714       164.714      0.1049\n401     boat     171.396    171.396    270.848       295.848      0.2537\n402  charter     107.916    107.916    138.598       173.598      0.0678\n403     boat     115.736    115.736     79.254       103.254      0.1049\n404  charter     266.696    266.696     79.254       114.254      0.5333\n405     boat      86.658     86.658     37.752        61.752      0.1049\n406     boat      58.050     58.050     11.352        46.352      0.5333\n407     boat      86.658     86.658     37.752        61.752      0.1049\n408  charter      85.698     85.698     60.306        84.306      0.1049\n409  charter     212.658    212.658     60.306        95.306      0.5333\n410  charter     212.658    212.658     60.306        95.306      0.5333\n411  charter      69.498     69.498     48.906        72.906      0.1049\n412    beach      85.698     85.698     85.698       104.198      0.2537\n413     boat      53.298     53.298     37.506        61.506      0.1049\n414     boat     172.458    172.458     48.906        83.906      0.5333\n415  charter     212.658    212.658     60.306        95.306      0.5333\n416     pier     224.296    224.296     66.654       101.654      0.5333\n417     pier      34.874     34.874     34.874        63.874      0.0678\n418  charter     360.126    360.126     77.274       112.274      0.5333\n419  charter      34.874     34.874     34.874        59.874      0.0678\n420  charter     261.326    261.326     56.074        91.074      0.5333\n421  charter      66.674     66.674    154.734       189.734      0.0678\n422  charter      77.274     77.274     77.274       106.274      0.0678\n423  charter     266.616    266.616    108.974       143.974      0.5333\n424  charter     191.334    191.334     64.350        99.350      0.5333\n425     boat     253.174    253.174    184.350       208.350      0.1049\n426  charter     191.334    191.334     64.350        99.350      0.5333\n427     boat      49.350     49.350     67.774       102.774      0.0678\n428     boat     191.334    191.334     64.350        99.350      0.5333\n429     boat     102.134    102.134     34.350        69.350      0.5333\n430  charter     191.334    191.334     64.350        99.350      0.5333\n431  charter     146.734    146.734     49.350        84.350      0.5333\n432  charter     235.934    235.934     79.350       114.350      0.5333\n433     pier      34.350     34.350     38.014        67.014      0.0678\n434  charter      67.774     67.774     49.350        73.350      0.1049\n435     pier      20.152     20.152     20.152        49.152      0.0678\n436     boat      74.354     74.354     45.402        69.402      0.1049\n437     boat     191.334    191.334     64.350        99.350      0.5333\n438  charter     322.218    322.218     94.770       129.770      0.5333\n439     boat     189.618    189.618     55.770        90.770      0.5333\n440  charter     489.804    489.804     59.682        94.682      0.5333\n441  charter      75.012     75.012     19.082        43.082      0.1049\n442  charter     251.804    251.804     30.682        65.682      0.5333\n443  charter      36.482     36.482     36.482        61.482      0.0678\n444     pier      13.282     13.282     13.282        42.282      0.0678\n445     boat     322.048    322.048    167.314       202.314      0.5333\n446    beach      74.196     74.196     74.196        92.696      0.2537\n447  charter     578.048    578.048    300.314       335.314      0.5333\n448  charter     138.996    138.996    114.114       138.114      0.1049\n449  charter     197.340    197.340     42.900        77.900      0.5333\n450     boat     233.818    233.818     68.770       103.770      0.5333\n451  charter     133.770    133.770    133.770       158.770      0.0678\n452     pier      94.770     94.770     94.770       123.770      0.0678\n453  charter     133.770    133.770    133.770       158.770      0.0678\n454     boat     127.058    127.058     81.770       105.770      0.1049\n455  charter      47.174     47.174     34.350        58.350      0.1049\n456    beach     109.350    109.350    121.014       150.014      0.0678\n457     boat     154.214    154.214    154.214       179.214      0.0678\n458  charter     253.174    253.174    184.350       208.350      0.1049\n459  charter     181.896    181.896     54.054        89.054      0.5333\n460     boat      78.936     78.936     54.054        78.054      0.1049\n461     boat     104.454    104.454    127.666       156.666      0.0678\n462  charter     373.050    373.050     72.952       107.952      0.5333\n463     boat      45.474     45.474     45.474        70.474      0.0678\n464     pier      45.474     45.474     45.474        74.474      0.0678\n465  charter     106.858    106.858     68.770        92.770      0.1049\n466     boat     233.818    233.818     68.770       103.770      0.5333\n467     boat     147.258    147.258     94.770       118.770      0.1049\n468     boat     147.258    147.258     94.770       118.770      0.1049\n469  charter     189.618    189.618     55.770        90.770      0.5333\n470  charter      66.458     66.458     42.770        66.770      0.1049\n471     boat     278.018    278.018     81.770       116.770      0.5333\n472  charter     233.818    233.818     68.770       103.770      0.5333\n473  charter      66.458     66.458     42.770        66.770      0.1049\n474  charter     278.018    278.018     81.770       116.770      0.5333\n475  charter      55.770     55.770     55.770        80.770      0.0678\n476     pier      68.770     68.770     68.770        97.770      0.0678\n477     boat      42.282     42.282    166.212       201.212      0.0678\n478     boat      36.482     36.482     36.482        65.482      0.0678\n479  charter      13.282     13.282     13.282        38.282      0.0678\n480     boat      97.812     97.812     24.882        48.882      0.1049\n481     boat      36.482     36.482     36.482        65.482      0.0678\n482  charter      13.282     13.282     13.282        38.282      0.0678\n483  charter     108.974    108.974    139.656       174.656      0.0678\n484  charter     216.216    216.216     88.374       123.374      0.5333\n485     boat     139.656    139.656    108.974       132.974      0.1049\n486  charter     113.256    113.256     88.374       112.374      0.1049\n487     pier     129.574    129.574    147.186       176.186      0.0678\n488  charter     146.734    146.734     49.350        84.350      0.5333\n489    beach      87.814     87.814     87.814       112.814      0.0678\n490  charter     414.334    414.334    139.350       174.350      0.5333\n491     boat      94.350     94.350    104.414       133.414      0.0678\n492    beach      66.654     66.654     81.466       110.466      0.0678\n493  charter      41.454     41.454     50.666        79.666      0.0678\n494     boat     351.496    351.496    104.454       139.454      0.5333\n495     pier      41.454     41.454     50.666        79.666      0.0678\n496     pier      91.854     91.854    112.266       141.266      0.0678\n497  charter     115.736    115.736     79.254       103.254      0.1049\n498  charter      41.454     41.454     60.536        95.536      0.0678\n499  charter      50.666     50.666     60.536        90.036      0.0678\n500  charter     139.496    139.496     41.454        76.454      0.5333\n501  charter     351.496    351.496    104.454       139.454      0.5333\n502     pier      54.054     54.054     66.066        95.066      0.0678\n503  charter     181.896    181.896     54.054        89.054      0.5333\n504  charter      28.854     28.854     35.266        64.266      0.0678\n505     pier      23.736     23.736     23.736        42.236      0.2537\n506  charter      54.696     54.696     16.254        51.254      0.5333\n507     boat      28.854     28.854     35.266        64.266      0.0678\n508  charter      56.074     56.074     92.046       127.046      0.0678\n509  charter     260.406    260.406     66.674       101.674      0.5333\n510  charter     301.806    301.806     77.274       112.274      0.5333\n511     boat      34.874     34.874     44.086        73.086      0.0678\n512  charter      92.046     92.046     56.074        80.074      0.1049\n513     boat     384.606    384.606     98.474       133.474      0.5333\n514  charter     260.406    260.406     66.674       101.674      0.5333\n515     pier      34.874     34.874     44.086        73.086      0.0678\n516    beach      97.686     97.686     97.686       122.686      0.0678\n517    beach      44.086     44.086     44.086        69.086      0.0678\n518  charter      53.406     53.406     13.674        48.674      0.5333\n519  charter      74.646     74.646    177.606       202.606      0.2537\n520     pier     144.246    144.246    144.246       162.746      0.2537\n521  charter      92.046     92.046    219.006       244.006      0.2537\n522     pier     136.206    136.206     34.874        69.874      0.5333\n523     boat     144.246    144.246     87.874       111.874      0.1049\n524    beach      56.074     56.074     70.886        99.886      0.0678\n525  charter     167.374    167.374    211.586       240.586      0.0678\n526  charter     136.206    136.206     34.874        69.874      0.5333\n527  charter     260.406    260.406     66.674       101.674      0.5333\n528     boat     343.206    343.206     87.874       122.874      0.5333\n529  charter      74.646     74.646    177.606       202.606      0.2537\n530     boat     233.818    233.818     68.770       103.770      0.5333\n531  charter     343.206    343.206     87.874       122.874      0.5333\n532  charter     219.006    219.006     56.074        91.074      0.5333\n533     pier      87.874     87.874    111.086       140.086      0.0678\n534  charter     177.606    177.606     45.474        80.474      0.5333\n535     boat     104.048    104.048     70.604        94.604      0.1049\n536  charter     151.008    151.008     32.604        67.604      0.5333\n537  charter     101.004    101.004    212.640       241.640      0.0678\n538  charter     115.808    115.808     25.004        60.004      0.5333\n539  charter     386.464    386.464     42.734        77.734      0.5333\n540     boat     428.064    428.064     47.334        82.334      0.5333\n541  charter      72.072     72.072     19.734        43.734      0.1049\n542  charter      88.872     88.872     24.334        48.334      0.1049\n543     boat     305.072    305.072     19.896        54.896      0.5333\n544     boat     305.072    305.072     19.896        54.896      0.5333\n545     boat      54.912     54.912     10.296        34.296      0.1049\n546     boat     157.872    157.872     10.296        45.296      0.5333\n547     boat     268.272    268.272     17.496        52.496      0.5333\n548  charter      84.272     84.272      5.496        40.496      0.5333\n549     pier      10.534     10.534     13.740        42.740      0.0678\n550     pier      24.334     24.334     31.740        60.740      0.0678\n551    beach      15.134     15.134     19.740        48.740      0.0678\n552     boat      88.872     88.872     24.334        48.334      0.1049\n553     pier      38.134     38.134     49.740        78.740      0.0678\n554     boat      88.872     88.872     24.334        48.334      0.1049\n555  charter      72.072     72.072     19.734        43.734      0.1049\n556  charter     157.872    157.872     10.296        45.296      0.5333\n557     boat     581.072    581.072     37.896        72.896      0.5333\n558  charter     341.872    341.872     22.296        57.296      0.5333\n559  charter     268.272    268.272     17.496        52.496      0.5333\n560  charter     341.872    341.872     22.296        57.296      0.5333\n561    beach      17.496     17.496     78.732       107.732      0.0678\n562  charter     194.672    194.672     12.696        47.696      0.5333\n563     boat      67.712     67.712     12.696        36.696      0.1049\n564     boat      67.712     67.712     12.696        36.696      0.1049\n565     boat      42.112     42.112      7.896        31.896      0.1049\n566     boat     157.872    157.872     10.296        45.296      0.5333\n567     pier      12.696     12.696     57.132        86.132      0.0678\n568    beach      89.532     89.532     89.532       114.532      0.0678\n569     boat      46.332     46.332     46.332        71.332      0.0678\n570     boat     106.112    106.112     19.896        43.896      0.1049\n571     pier      22.296     22.296    100.332       129.332      0.0678\n572  charter     121.072    121.072      7.896        42.896      0.5333\n573  charter     121.072    121.072      7.896        42.896      0.5333\n574     boat      93.312     93.312     17.496        41.496      0.1049\n575     boat      54.912     54.912     10.296        34.296      0.1049\n576     boat      80.512     80.512     15.096        39.096      0.1049\n577     boat      67.712     67.712     12.696        36.696      0.1049\n578  charter      54.912     54.912     10.296        34.296      0.1049\n579     boat     415.472    415.472     27.096        62.096      0.5333\n580  charter      95.264     95.264     10.534        45.534      0.5333\n581    beach      37.896     37.896    170.532       199.532      0.0678\n582  charter     121.072    121.072      7.896        42.896      0.5333\n583  charter      54.912     54.912     10.296        34.296      0.1049\n584  charter     268.272    268.272     17.496        52.496      0.5333\n585     boat     157.872    157.872     10.296        45.296      0.5333\n586     boat     157.872    157.872     10.296        45.296      0.5333\n587     boat      80.512     80.512     15.096        39.096      0.1049\n588    beach      10.296     10.296     46.332        75.332      0.0678\n589  charter     106.112    106.112    305.072       330.072      0.2537\n590  charter     157.872    157.872     10.296        45.296      0.5333\n591     boat      89.532     89.532    106.112       135.612      0.0678\n592     boat      54.912     54.912     10.296        34.296      0.1049\n593     boat     231.472    231.472     15.096        50.096      0.5333\n594     boat     268.272    268.272     17.496        52.496      0.5333\n595  charter     157.312    157.312     29.496        53.496      0.1049\n596  charter     121.072    121.072      7.896        42.896      0.5333\n597  charter     231.472    231.472     15.096        50.096      0.5333\n598     boat     341.872    341.872     22.296        57.296      0.5333\n599     boat      80.512     80.512     15.096        39.096      0.1049\n600  charter     344.864    344.864     38.134        73.134      0.5333\n601  charter     220.064    220.064     24.334        59.334      0.5333\n602  charter     122.472    122.472     33.534        57.534      0.1049\n603  charter      72.072     72.072     19.734        43.734      0.1049\n604    beach       5.934      5.934      7.740        36.740      0.0678\n605  charter     136.864    136.864     15.134        50.134      0.5333\n606  charter     136.864    136.864     15.134        50.134      0.5333\n607     boat     136.864    136.864     15.134        50.134      0.5333\n608  charter      95.264     95.264     10.534        45.534      0.5333\n609     boat     223.272    223.272     61.134        85.134      0.1049\n610     boat     386.464    386.464     42.734        77.734      0.5333\n611  charter     303.264    303.264     33.534        68.534      0.5333\n612    beach      24.334     24.334     31.740        60.740      0.0678\n613  charter      72.072     72.072     19.734        43.734      0.1049\n614     boat     265.272    265.272     72.634        96.634      0.1049\n615     boat     178.464    178.464     19.734        54.734      0.5333\n616  charter      54.912     54.912     10.296        34.296      0.1049\n617     pier      22.296     22.296    100.332       129.332      0.0678\n618     boat     581.072    581.072     37.896        72.896      0.5333\n619     boat      67.712     67.712     12.696        36.696      0.1049\n620     boat      93.312     93.312     17.496        41.496      0.1049\n621    beach      93.312     93.312     93.312       111.812      0.2537\n622  charter     220.064    220.064     24.334        59.334      0.5333\n623  charter     178.464    178.464     19.734        54.734      0.5333\n624     boat     265.272    265.272     72.634        96.634      0.1049\n625     pier      56.534     56.534     73.740       102.740      0.0678\n626  charter     122.472    122.472     33.534        57.534      0.1049\n627    beach      15.134     15.134     19.740        48.740      0.0678\n628     boat     261.664    261.664     28.934        63.934      0.5333\n629    beach      42.734     42.734     55.740        84.740      0.0678\n630     boat     189.672    189.672     51.934        75.934      0.1049\n631     boat     344.864    344.864     38.134        73.134      0.5333\n632     boat      54.912     54.912     10.296        34.296      0.1049\n633     boat     157.872    157.872     10.296        45.296      0.5333\n634  charter     415.472    415.472     27.096        62.096      0.5333\n635     boat     581.072    581.072     37.896        72.896      0.5333\n636  charter     378.672    378.672     24.696        59.696      0.5333\n637     boat      19.896     19.896    106.112       141.112      0.0678\n638  charter      67.712     67.712     12.696        36.696      0.1049\n639     pier      17.496     17.496     78.732       107.732      0.0678\n640     boat     452.272    452.272     29.496        64.496      0.5333\n641  charter      93.312     93.312     17.496        41.496      0.1049\n642     pier      12.696     12.696     57.132        86.132      0.0678\n643     boat     202.112    202.112     37.896        61.896      0.1049\n644  charter     489.072    489.072     31.896        66.896      0.5333\n645     boat      54.912     54.912     10.296        34.296      0.1049\n646     pier       5.496      5.496     24.732        53.732      0.0678\n647  charter      10.296     10.296     54.912        89.912      0.0678\n648     boat      12.696     12.696     67.712       102.712      0.0678\n649  charter     231.472    231.472     15.096        50.096      0.5333\n650    beach      10.296     10.296     46.332        75.332      0.0678\n651     boat      42.112     42.112      7.896        31.896      0.1049\n652  charter     231.472    231.472     15.096        50.096      0.5333\n653  charter     121.072    121.072      7.896        42.896      0.5333\n654     boat     231.472    231.472     15.096        50.096      0.5333\n655     pier      10.296     10.296     46.332        75.332      0.0678\n656    beach       5.496      5.496     24.732        53.732      0.0678\n657     boat     202.112    202.112     37.896        61.896      0.1049\n658     pier      78.732     78.732     78.732       103.732      0.0678\n659     boat     268.272    268.272     17.496        52.496      0.5333\n660    beach       9.870      9.870     32.900        51.400      0.2537\n661     pier      36.870     36.870    122.900       141.400      0.2537\n662  charter     276.432    276.432    212.640       247.640      0.5333\n663  charter     100.016    100.016      9.870        39.370      0.0678\n664  charter     193.232    193.232    148.640       183.640      0.5333\n665     boat      52.640     52.640      9.870        44.870      0.0678\n666     boat     191.216    191.216     18.870        48.370      0.0678\n667    beach      47.370     47.370    157.900       176.400      0.2537\n668  charter      68.640     68.640     12.870        47.870      0.0678\n669     boat     252.640    252.640     47.370        82.370      0.0678\n670     boat     191.216    191.216     18.870        48.370      0.0678\n671     boat      68.640     68.640     12.870        47.870      0.0678\n672     boat     160.816    160.816     15.870        45.370      0.0678\n673     boat     148.640    148.640     27.870        62.870      0.0678\n674     boat      84.640     84.640     15.870        50.870      0.0678\n675  charter     180.640    180.640     33.870        68.870      0.0678\n676    beach       9.870      9.870     32.900        51.400      0.2537\n677  charter     100.640    100.640     18.870        53.870      0.0678\n678     boat     148.640    148.640     27.870        62.870      0.0678\n679     boat     148.640    148.640     27.870        62.870      0.0678\n680     boat     191.216    191.216     18.870        48.370      0.0678\n681  charter      68.640     68.640     12.870        47.870      0.0678\n682     boat     100.640    100.640     18.870        53.870      0.0678\n683     boat     191.216    191.216     18.870        48.370      0.0678\n684  charter     132.640    132.640     24.870        59.870      0.0678\n685  charter      36.640     36.640      6.870        41.870      0.0678\n686  charter      52.640     52.640      9.870        44.870      0.0678\n687    beach      12.870     12.870     42.900        61.400      0.2537\n688     pier      47.370     47.370    157.900       176.400      0.2537\n689    beach      27.870     27.870     92.900       111.400      0.2537\n690     pier      18.870     18.870     62.900        81.400      0.2537\n691  charter     160.816    160.816     15.870        45.370      0.0678\n692  charter     164.640    164.640     30.870        65.870      0.0678\n693     boat     191.216    191.216     18.870        48.370      0.0678\n694     boat      84.640     84.640     15.870        50.870      0.0678\n695  charter      24.870     24.870    172.432       197.432      0.2537\n696    beach      12.870     12.870     42.900        61.400      0.2537\n697     boat     116.640    116.640     21.870        56.870      0.0678\n698     pier      33.870     33.870    112.900       131.400      0.2537\n699     boat     252.016    252.016     24.870        54.370      0.0678\n700     boat     252.016    252.016     24.870        54.370      0.0678\n701     pier      24.870     24.870     82.900       101.400      0.2537\n702     boat     100.640    100.640     18.870        53.870      0.0678\n703  charter     100.640    100.640     18.870        53.870      0.0678\n704     boat     100.640    100.640     18.870        53.870      0.0678\n705     pier       6.870      6.870     22.900        41.400      0.2537\n706     pier      15.870     15.870     68.770        87.270      0.2537\n707     boat     221.408    221.408     18.870        48.370      0.0678\n708    beach      27.870     27.870    120.770       139.270      0.2537\n709    beach       9.870      9.870     42.770        61.270      0.2537\n710     pier       9.870      9.870     42.770        61.270      0.2537\n711     pier      15.870     15.870     68.770        87.270      0.2537\n712    beach      18.870     18.870     81.770       100.270      0.2537\n713  charter     116.640    116.640     21.870        56.870      0.0678\n714    beach      21.870     21.870     72.900        91.400      0.2537\n715     pier      12.870     12.870     42.900        61.400      0.2537\n716     pier      12.870     12.870     42.900        61.400      0.2537\n717  charter     116.640    116.640     21.870        56.870      0.0678\n718  charter      84.640     84.640     15.870        50.870      0.0678\n719  charter     132.640    132.640     24.870        59.870      0.0678\n720  charter      52.640     52.640      9.870        44.870      0.0678\n721     boat       9.870      9.870     32.900        51.400      0.2537\n722  charter     148.640    148.640     27.870        62.870      0.0678\n723     boat     180.640    180.640     33.870        68.870      0.0678\n724  charter     130.416    130.416     12.870        42.370      0.0678\n725     boat     221.616    221.616     21.870        51.370      0.0678\n726     pier      36.870     36.870    122.900       141.400      0.2537\n727     boat     191.216    191.216     18.870        48.370      0.0678\n728  charter      68.640     68.640     12.870        47.870      0.0678\n729     pier      30.870     30.870    102.900       121.400      0.2537\n730     boat     282.416    282.416     27.870        57.370      0.0678\n731     boat     116.640    116.640     21.870        56.870      0.0678\n732     boat      84.640     84.640     15.870        50.870      0.0678\n733  charter     116.640    116.640     21.870        56.870      0.0678\n734     boat     148.640    148.640     27.870        62.870      0.0678\n735     pier      18.870     18.870     62.900        81.400      0.2537\n736  charter      84.640     84.640     15.870        50.870      0.0678\n737     boat     100.640    100.640     18.870        53.870      0.0678\n738     boat      84.640     84.640     15.870        50.870      0.0678\n739  charter       6.870      6.870     47.632        72.632      0.2537\n740  charter      84.640     84.640     15.870        50.870      0.0678\n741  charter      68.640     68.640     12.870        47.870      0.0678\n742  charter      84.640     84.640     15.870        50.870      0.0678\n743    beach      18.870     18.870     62.900        81.400      0.2537\n744  charter     160.816    160.816     15.870        45.370      0.0678\n745     pier      15.870     15.870     52.900        71.400      0.2537\n746     boat     100.016    100.016      9.870        39.370      0.0678\n747     pier       9.870      9.870     32.900        51.400      0.2537\n748     pier       9.870      9.870     32.900        51.400      0.2537\n749     boat      84.640     84.640     15.870        50.870      0.0678\n750     pier      12.870     12.870     42.900        61.400      0.2537\n751  charter      52.640     52.640      9.870        44.870      0.0678\n752     pier      12.870     12.870     42.900        61.400      0.2537\n753     boat     180.640    180.640     33.870        68.870      0.0678\n754  charter      36.640     36.640      6.870        41.870      0.0678\n755     boat      52.640     52.640      9.870        44.870      0.0678\n756     boat      84.640     84.640     15.870        50.870      0.0678\n757    beach       9.870      9.870     32.900        51.400      0.2537\n758     boat     148.640    148.640     27.870        62.870      0.0678\n759  charter      52.640     52.640      9.870        44.870      0.0678\n760    beach      15.870     15.870     52.900        71.400      0.2537\n761     boat     228.640    228.640     42.870        77.870      0.0678\n762  charter      68.640     68.640     12.870        47.870      0.0678\n763  charter      52.640     52.640      9.870        44.870      0.0678\n764     boat     160.816    160.816     15.870        45.370      0.0678\n765     boat     116.640    116.640     21.870        56.870      0.0678\n766  charter      84.640     84.640     15.870        50.870      0.0678\n767     pier      12.870     12.870     42.900        61.400      0.2537\n768     boat     221.616    221.616     21.870        51.370      0.0678\n769  charter      68.640     68.640     12.870        47.870      0.0678\n770    beach       9.870      9.870     32.900        51.400      0.2537\n771     pier      12.870     12.870     42.900        61.400      0.2537\n772     pier       3.870      3.870     12.900        31.400      0.2537\n773  charter     116.640    116.640     21.870        56.870      0.0678\n774  charter      84.640     84.640     15.870        50.870      0.0678\n775    beach       9.870      9.870     32.900        51.400      0.2537\n776     pier       9.870      9.870     32.900        51.400      0.2537\n777  charter      43.740     43.740     52.488        70.988      0.2537\n778  charter     107.770    107.770     49.740        84.740      0.0678\n779     boat      78.302     78.302     42.770        77.770      0.5333\n780  charter     120.770    120.770     55.740        90.740      0.0678\n781  charter      94.770     94.770     43.740        78.740      0.0678\n782  charter      81.770     81.770     37.740        72.740      0.0678\n783  charter     134.366    134.366     31.740        61.240      0.0678\n784  charter      55.770     55.770     25.740        60.740      0.0678\n785     boat      94.770     94.770     43.740        78.740      0.0678\n786     pier      43.740     43.740     52.488        70.988      0.2537\n787     boat      94.770     94.770     43.740        78.740      0.0678\n788  charter      81.770     81.770     37.740        72.740      0.0678\n789  charter     107.770    107.770     49.740        84.740      0.0678\n790  charter     108.966    108.966     25.740        55.240      0.0678\n791     pier      25.740     25.740     30.888        49.388      0.2537\n792     boat     108.966    108.966     25.740        55.240      0.0678\n793  charter      94.770     94.770     43.740        78.740      0.0678\n794    beach     125.902    125.902     68.770       103.770      0.5333\n795  charter      68.770     68.770     31.740        66.740      0.0678\n796     boat     159.766    159.766     37.740        67.240      0.0678\n797  charter      81.770     81.770     37.740        72.740      0.0678\n798     boat      68.770     68.770     31.740        66.740      0.0678\n799  charter     107.770    107.770     49.740        84.740      0.0678\n800     boat      94.770     94.770     43.740        78.740      0.0678\n801     boat      29.770     29.770     13.740        48.740      0.0678\n802     boat     108.966    108.966     25.740        55.240      0.0678\n803     boat      42.594     42.594      6.870        41.870      0.0678\n804  charter      79.794     79.794     12.870        47.870      0.0678\n805     boat     115.808    115.808      9.870        39.370      0.0678\n806     boat     154.194    154.194     24.870        59.870      0.0678\n807  charter      42.594     42.594      6.870        41.870      0.0678\n808    beach      24.870     24.870    107.770       126.270      0.2537\n809  charter     186.208    186.208     15.870        45.370      0.0678\n810  charter      61.194     61.194      9.870        44.870      0.0678\n811     pier      12.870     12.870     55.770        74.270      0.2537\n812  charter      79.794     79.794     12.870        47.870      0.0678\n813    beach      27.870     27.870    120.770       139.270      0.2537\n814  charter      79.794     79.794     12.870        47.870      0.0678\n815     boat     555.808    555.808     47.370        76.870      0.0678\n816     boat      80.608     80.608      6.870        36.370      0.0678\n817     boat     467.808    467.808     39.870        69.370      0.0678\n818    beach      36.870     36.870    159.770       178.270      0.2537\n819    beach      12.870     12.870     55.770        74.270      0.2537\n820    beach       6.870      6.870     29.770        48.270      0.2537\n821  charter     115.808    115.808      9.870        39.370      0.0678\n822    beach      12.870     12.870     55.770        74.270      0.2537\n823     boat     154.194    154.194     24.870        59.870      0.0678\n824     boat     116.994    116.994     18.870        53.870      0.0678\n825    beach      12.870     12.870     55.770        74.270      0.2537\n826     pier       3.870      3.870     16.770        35.270      0.2537\n827  charter     154.194    154.194     24.870        59.870      0.0678\n828    beach      30.870     30.870    133.770       152.270      0.2537\n829     pier       3.870      3.870     16.770        35.270      0.2537\n830  charter     135.594    135.594     21.870        56.870      0.0678\n831  charter     116.994    116.994     18.870        53.870      0.0678\n832  charter     116.994    116.994     18.870        53.870      0.0678\n833     boat     555.808    555.808     47.370        76.870      0.0678\n834  charter     116.994    116.994     18.870        53.870      0.0678\n835     boat     209.994    209.994     33.870        68.870      0.0678\n836     boat      98.394     98.394     15.870        50.870      0.0678\n837     boat     115.808    115.808      9.870        39.370      0.0678\n838  charter      80.608     80.608      6.870        36.370      0.0678\n839  charter      79.794     79.794     12.870        47.870      0.0678\n840    beach      24.870     24.870    107.770       126.270      0.2537\n841     boat     151.008    151.008     12.870        42.370      0.0678\n842     boat     256.608    256.608     21.870        51.370      0.0678\n843     boat      98.394     98.394     15.870        50.870      0.0678\n844     pier      12.870     12.870     55.770        74.270      0.2537\n845    beach      21.870     21.870     94.770       113.270      0.2537\n846     boat     115.808    115.808      9.870        39.370      0.0678\n847  charter     135.594    135.594     21.870        56.870      0.0678\n848  charter     135.594    135.594     21.870        56.870      0.0678\n849     pier      24.870     24.870    107.770       126.270      0.2537\n850  charter      79.794     79.794     12.870        47.870      0.0678\n851     boat      23.994     23.994      3.870        38.870      0.0678\n852  charter      98.394     98.394     15.870        50.870      0.0678\n853     boat     221.408    221.408     18.870        48.370      0.0678\n854  charter      12.870     12.870     53.196        78.196      0.2537\n855     boat      80.608     80.608      6.870        36.370      0.0678\n856     boat     256.608    256.608     21.870        51.370      0.0678\n857     boat      80.608     80.608      6.870        36.370      0.0678\n858     pier      12.870     12.870     55.770        74.270      0.2537\n859  charter     115.808    115.808    115.808       140.808      0.0678\n860    beach      15.870     15.870     68.770        87.270      0.2537\n861     boat     397.408    397.408     33.870        63.370      0.0678\n862     boat      79.794     79.794     12.870        47.870      0.0678\n863  charter      42.594     42.594      6.870        41.870      0.0678\n864     boat     256.608    256.608     21.870        51.370      0.0678\n865     pier       3.870      3.870     16.770        35.270      0.2537\n866     pier      21.870     21.870     94.770       113.270      0.2537\n867     boat      79.794     79.794     12.870        47.870      0.0678\n868     boat     327.008    327.008     27.870        57.370      0.0678\n869     boat      45.408     45.408      3.870        33.370      0.0678\n870     boat     175.890    175.890    121.836       146.836      0.2537\n871    beach      31.144     31.144     70.532       105.532      0.5333\n872     boat      35.724     35.724     31.144        56.144      0.2537\n873    beach     121.836    121.836    203.346       238.346      0.5333\n874  charter     175.890    175.890    121.836       146.836      0.2537\n875     pier      93.436     93.436    155.946       190.946      0.5333\n876     boat     224.818    224.818    245.256       270.256      0.2537\n877  charter     128.018    128.018    139.656       164.656      0.2537\n878  charter      57.246     57.246      9.870        34.870      0.2537\n879     boat      22.446     22.446      3.870        28.870      0.2537\n880  charter      74.646     74.646     12.870        37.870      0.2537\n881     boat     144.246    144.246     24.870        49.870      0.2537\n882    beach       9.870      9.870    121.730       156.730      0.5333\n883  charter      22.446     22.446      3.870        28.870      0.2537\n884     boat      74.646     74.646     12.870        37.870      0.2537\n885    beach       9.870      9.870    121.730       156.730      0.5333\n886     pier      18.870     18.870    232.730       267.730      0.5333\n887     boat     161.646    161.646     27.870        52.870      0.2537\n888  charter      57.246     57.246      9.870        34.870      0.2537\n889  charter     109.446    109.446     18.870        43.870      0.2537\n890     boat      74.646     74.646     12.870        37.870      0.2537\n891     boat      22.446     22.446      3.870        28.870      0.2537\n892     pier       3.870      3.870     47.730        82.730      0.5333\n893    beach       3.870      3.870     47.730        82.730      0.5333\n894     boat      57.246     57.246      9.870        34.870      0.2537\n895     boat     161.646    161.646     27.870        52.870      0.2537\n896    beach      15.870     15.870    195.730       230.730      0.5333\n897     pier      12.870     12.870    158.730       193.730      0.5333\n898     pier       9.870      9.870    121.730       156.730      0.5333\n899     boat      74.646     74.646     12.870        37.870      0.2537\n900     boat      74.646     74.646     12.870        37.870      0.2537\n901     boat      57.246     57.246      9.870        34.870      0.2537\n902     boat     176.344    176.344     57.246        86.746      0.0678\n903     boat      74.646     74.646     12.870        37.870      0.2537\n904     pier       9.870      9.870    121.730       156.730      0.5333\n905  charter      74.646     74.646     12.870        37.870      0.2537\n906     pier       6.870      6.870     84.730       119.730      0.5333\n907     boat      39.846     39.846      6.870        31.870      0.2537\n908  charter      92.046     92.046     15.870        40.870      0.2537\n909     boat     283.544    283.544     92.046       121.546      0.0678\n910     boat      74.646     74.646     12.870        37.870      0.2537\n911     boat      74.646     74.646     12.870        37.870      0.2537\n912  charter      57.246     57.246      9.870        34.870      0.2537\n913  charter     195.730    195.730     92.046       127.046      0.0678\n914     pier       9.870      9.870    121.730       156.730      0.5333\n915     boat     144.246    144.246     24.870        49.870      0.2537\n916     boat     144.246    144.246     24.870        49.870      0.2537\n917     boat     109.446    109.446     18.870        43.870      0.2537\n918     boat      39.846     39.846      6.870        31.870      0.2537\n919     boat      57.246     57.246      9.870        34.870      0.2537\n920    beach      27.870     27.870    343.730       378.730      0.5333\n921  charter      92.046     92.046     15.870        40.870      0.2537\n922     boat      92.046     92.046     15.870        40.870      0.2537\n923     boat      15.096     15.096    213.860       248.860      0.5333\n924     pier       7.896      7.896    111.860       146.860      0.5333\n925    beach      12.696     12.696    179.860       214.860      0.5333\n926     boat      32.976     32.976      5.496        30.496      0.2537\n927     boat      47.376     47.376      7.896        32.896      0.2537\n928    beach      19.896     19.896    281.860       316.860      0.5333\n929     boat      76.176     76.176     12.696        37.696      0.2537\n930     boat      47.376     47.376      7.896        32.896      0.2537\n931     boat     133.776    133.776     22.296        47.296      0.2537\n932  charter      61.776     61.776     10.296        35.296      0.2537\n933     boat     227.376    227.376     37.896        62.896      0.2537\n934    beach       7.896      7.896    111.860       146.860      0.5333\n935     boat      90.576     90.576     15.096        40.096      0.2537\n936  charter      90.576     90.576     15.096        40.096      0.2537\n937    beach      15.096     15.096    213.860       248.860      0.5333\n938    beach      10.296     10.296    145.860       180.860      0.5333\n939  charter     133.776    133.776     22.296        47.296      0.2537\n940     boat      61.776     61.776     10.296        35.296      0.2537\n941     boat      61.776     61.776     10.296        35.296      0.2537\n942    beach      15.096     15.096    213.860       248.860      0.5333\n943     boat      32.976     32.976      5.496        30.496      0.2537\n944     boat     162.576    162.576     27.096        52.096      0.2537\n945     boat      76.176     76.176     12.696        37.696      0.2537\n946     pier      77.860     77.860    115.874       144.874      0.0678\n947    beach      17.496     17.496    247.860       282.860      0.5333\n948  charter      61.776     61.776     10.296        35.296      0.2537\n949     boat     104.976    104.976     17.496        42.496      0.2537\n950  charter      47.376     47.376      7.896        32.896      0.2537\n951     boat     150.174    150.174     45.198        70.198      0.2537\n952    beach      26.598     26.598    172.458       207.458      0.5333\n953  charter      88.374     88.374     26.598        51.598      0.2537\n954     boat     129.574    129.574     38.998        63.998      0.2537\n955  charter     132.258    132.258     67.774       102.774      0.0678\n956     pier      26.598     26.598    172.458       207.458      0.5333\n957    beach      14.198     14.198     92.058       127.058      0.5333\n958  charter      47.174     47.174     14.198        39.198      0.2537\n959  charter     108.974    108.974     32.798        57.798      0.2537\n960     pier      20.398     20.398    132.258       167.258      0.5333\n961  charter      88.374     88.374     26.598        51.598      0.2537\n962     boat     129.574    129.574     38.998        63.998      0.2537\n963     boat      88.374     88.374     26.598        51.598      0.2537\n964    beach      32.798     32.798    212.658       247.658      0.5333\n965     boat      88.374     88.374     26.598        51.598      0.2537\n966  charter     129.574    129.574     38.998        63.998      0.2537\n967     boat     108.974    108.974     32.798        57.798      0.2537\n968  charter     129.574    129.574     38.998        63.998      0.2537\n969     pier      26.598     26.598    172.458       207.458      0.5333\n970     pier      26.598     26.598    172.458       207.458      0.5333\n971  charter     129.574    129.574     38.998        63.998      0.2537\n972     boat     253.174    253.174     76.198       101.198      0.2537\n973     boat     108.974    108.974     32.798        57.798      0.2537\n974     pier      20.398     20.398    132.258       167.258      0.5333\n975     boat      47.174     47.174     14.198        39.198      0.2537\n976     pier      38.998     38.998    252.858       287.858      0.5333\n977     boat     129.574    129.574     38.998        63.998      0.2537\n978     pier      76.198     76.198    494.058       529.058      0.5333\n979    beach       7.998      7.998     51.858        86.858      0.5333\n980     pier       9.870      9.870    121.730       156.730      0.5333\n981    beach      14.476     14.476     62.510        81.010      0.2537\n982     pier       2.322      2.322     55.470        90.470      0.5333\n983     boat      53.586     53.586      4.122        29.122      0.2537\n984     boat     123.786    123.786      9.522        34.522      0.2537\n985  charter      61.776     61.776     10.296        35.296      0.2537\n986     pier       3.096      3.096     43.860        78.860      0.5333\n987     pier       7.896      7.896    111.860       146.860      0.5333\n988     boat      76.176     76.176     12.696        37.696      0.2537\n989     boat      47.376     47.376      7.896        32.896      0.2537\n990  charter      18.576     18.576      3.096        28.096      0.2537\n991  charter      32.976     32.976      5.496        30.496      0.2537\n992     boat     119.376    119.376     19.896        44.896      0.2537\n993     boat      61.776     61.776     10.296        35.296      0.2537\n994     pier      15.096     15.096    213.860       248.860      0.5333\n995     pier      10.296     10.296    145.860       180.860      0.5333\n996     pier       5.496      5.496     77.860       112.860      0.5333\n997  charter      32.976     32.976      5.496        30.496      0.2537\n998    beach      17.496     17.496    247.860       282.860      0.5333\n999     boat      32.976     32.976      5.496        30.496      0.2537\n1000    boat      61.776     61.776     10.296        35.296      0.2537\n1001    boat      76.176     76.176     12.696        37.696      0.2537\n1002    pier       5.496      5.496     77.860       112.860      0.5333\n1003    boat      18.576     18.576      3.096        28.096      0.2537\n1004    boat      90.576     90.576     15.096        40.096      0.2537\n1005   beach      76.176     76.176    139.656       158.156      0.2537\n1006    boat      76.176     76.176     12.696        37.696      0.2537\n1007    boat     227.376    227.376     37.896        62.896      0.2537\n1008   beach       5.496      5.496     77.860       112.860      0.5333\n1009    pier      47.376     47.376     86.856       105.356      0.2537\n1010   beach       7.896      7.896    111.860       146.860      0.5333\n1011    boat      37.506     37.506      3.290        28.290      0.2537\n1012   beach       3.290      3.290    101.990       136.990      0.5333\n1013   beach       2.290      2.290     70.990       105.990      0.5333\n1014   beach       1.290      1.290     39.990        74.990      0.5333\n1015    pier       6.290      6.290    194.990       229.990      0.5333\n1016    boat     243.340    243.340     41.262        70.762      0.0678\n1017    boat      56.862     56.862     36.450        61.450      0.2537\n1018    pier      49.062     49.062    149.702       168.202      0.2537\n1019 charter      49.062     49.062     31.450        56.450      0.2537\n1020    boat      25.662     25.662     16.450        41.450      0.2537\n1021    boat     214.326    214.326     56.862        91.862      0.0678\n1022    boat     126.126    126.126     33.462        68.462      0.0678\n1023   beach      11.450     11.450     67.326       102.326      0.5333\n1024 charter      16.450     16.450     96.726       131.726      0.5333\n1025    boat     243.340    243.340     41.262        70.762      0.0678\n1026 charter      80.262     80.262     51.450        76.450      0.2537\n1027    boat      96.726     96.726     25.662        60.662      0.0678\n1028   beach      26.450     26.450    155.526       190.526      0.5333\n1029 charter      25.662     25.662     16.450        41.450      0.2537\n1030 charter      41.262     41.262     26.450        51.450      0.2537\n1031   beach      21.450     21.450    126.126       161.126      0.5333\n1032 charter      33.462     33.462     21.450        46.450      0.2537\n1033    boat      67.326     67.326     17.862        52.862      0.0678\n1034    boat      33.462     33.462     21.450        46.450      0.2537\n1035    pier      17.862     17.862     54.502        73.002      0.2537\n1036   beach      11.450     11.450     67.326       102.326      0.5333\n1037 charter     176.748    176.748     18.876        48.376      0.0678\n1038 charter      14.476     14.476     22.372        47.372      0.2537\n1039    boat     341.548    341.548     36.476        65.976      0.0678\n1040    boat      39.846     39.846      6.870        31.870      0.2537\n1041    boat      39.846     39.846      6.870        31.870      0.2537\n1042 charter      74.646     74.646     12.870        37.870      0.2537\n1043   beach      15.870     15.870    195.730       230.730      0.5333\n1044 charter      57.246     57.246      9.870        34.870      0.2537\n1045 charter      92.046     92.046     15.870        40.870      0.2537\n1046 charter      90.576     90.576     15.096        40.096      0.2537\n1047 charter      61.776     61.776     10.296        35.296      0.2537\n1048    pier       7.896      7.896    111.860       146.860      0.5333\n1049    pier      15.096     15.096    213.860       248.860      0.5333\n1050    boat      61.776     61.776     10.296        35.296      0.2537\n1051 charter     145.860    145.860    217.074       246.074      0.0678\n1052    boat      76.176     76.176     12.696        37.696      0.2537\n1053 charter      61.776     61.776     10.296        35.296      0.2537\n1054    pier       7.896      7.896    111.860       146.860      0.5333\n1055   beach      12.696     12.696    179.860       214.860      0.5333\n1056 charter     104.976    104.976     17.496        42.496      0.2537\n1057    pier       7.896      7.896    111.860       146.860      0.5333\n1058 charter      76.176     76.176     12.696        37.696      0.2537\n1059    boat     166.212    166.212     52.488        77.488      0.2537\n1060    pier      16.488     16.488     97.096       132.096      0.5333\n1061    boat     143.412    143.412     45.288        70.288      0.2537\n1062    boat      97.812     97.812     30.888        55.888      0.2537\n1063 charter      75.012     75.012     23.688        48.688      0.2537\n1064    pier      30.888     30.888    181.896       216.896      0.5333\n1065    boat     120.612    120.612     38.088        63.088      0.2537\n1066 charter      97.812     97.812     30.888        55.888      0.2537\n1067    pier      30.888     30.888    181.896       216.896      0.5333\n1068    boat     120.612    120.612     38.088        63.088      0.2537\n1069 charter      97.096     97.096     52.212        87.212      0.0678\n1070 charter     189.012    189.012     59.688        84.688      0.2537\n1071 charter      52.212     52.212     16.488        41.488      0.2537\n1072    boat      75.012     75.012     23.688        48.688      0.2537\n1073    boat     351.496    351.496    189.012       224.012      0.0678\n1074   beach      30.888     30.888    181.896       216.896      0.5333\n1075    boat      61.776     61.776     10.296        35.296      0.2537\n1076    boat     267.674    267.674     76.176       105.676      0.0678\n1077    pier      12.696     12.696    179.860       214.860      0.5333\n1078 charter      32.976     32.976      5.496        30.496      0.2537\n1079 charter      47.376     47.376      7.896        32.896      0.2537\n1080    boat      32.976     32.976      5.496        30.496      0.2537\n1081    pier      10.296     10.296    145.860       180.860      0.5333\n1082    boat     267.674    267.674     76.176       105.676      0.0678\n1083 charter      76.176     76.176     12.696        37.696      0.2537\n1084 charter      61.776     61.776     10.296        35.296      0.2537\n1085 charter     111.860    111.860     47.376        82.376      0.0678\n1086    boat     227.376    227.376     37.896        62.896      0.2537\n1087 charter      76.176     76.176     12.696        37.696      0.2537\n1088 charter      32.976     32.976      5.496        30.496      0.2537\n1089 charter      61.776     61.776     10.296        35.296      0.2537\n1090    boat      90.576     90.576     15.096        40.096      0.2537\n1091    boat     227.376    227.376     37.896        62.896      0.2537\n1092    boat      32.976     32.976      5.496        30.496      0.2537\n1093 charter      47.376     47.376      7.896        32.896      0.2537\n1094   beach      17.496     17.496    247.860       282.860      0.5333\n1095    boat      97.812     97.812     30.888        55.888      0.2537\n1096    pier      16.488     16.488     97.096       132.096      0.5333\n1097 charter      75.012     75.012     23.688        48.688      0.2537\n1098 charter      75.012     75.012     23.688        48.688      0.2537\n1099    boat      76.986     76.986      5.922        30.922      0.2537\n1100    boat      63.168     63.168     15.792        40.792      0.2537\n1101    boat      82.368     82.368     20.592        45.592      0.2537\n1102    pier       4.290      4.290    132.990       167.990      0.5333\n1103    boat      71.706     71.706      6.290        31.290      0.2537\n1104    pier       8.290      8.290    256.990       291.990      0.5333\n1105   beach      94.506     94.506    193.986       212.486      0.2537\n1106    pier       1.290      1.290     39.990        74.990      0.5333\n1107 charter      37.506     37.506      3.290        28.290      0.2537\n1108 charter      48.906     48.906      4.290        29.290      0.2537\n1109 charter      37.506     37.506      3.290        28.290      0.2537\n1110 charter      60.306     60.306      5.290        30.290      0.2537\n1111    pier       3.290      3.290    101.990       136.990      0.5333\n1112 charter      48.906     48.906      4.290        29.290      0.2537\n1113 charter      26.106     26.106      2.290        27.290      0.2537\n1114 charter     347.004    347.004     83.106       112.606      0.0678\n1115   beach       6.290      6.290    194.990       229.990      0.5333\n1116 charter      48.906     48.906      4.290        29.290      0.2537\n1117    pier       2.290      2.290     70.990       105.990      0.5333\n1118    pier       6.290      6.290    194.990       229.990      0.5333\n1119    boat     180.006    180.006     15.790        40.790      0.2537\n1120   beach       4.290      4.290    132.990       167.990      0.5333\n1121   beach       4.290      4.290    132.990       167.990      0.5333\n1122    boat     204.204    204.204     48.906        78.406      0.0678\n1123   beach       6.290      6.290    194.990       229.990      0.5333\n1124   beach       9.290      9.290    287.990       322.990      0.5333\n1125 charter      60.306     60.306      5.290        30.290      0.2537\n1126    pier       5.290      5.290    163.990       198.990      0.5333\n1127    pier       4.290      4.290    132.990       167.990      0.5333\n1128    boat      94.506     94.506      8.290        33.290      0.2537\n1129 charter      60.306     60.306      5.290        30.290      0.2537\n1130    boat      37.506     37.506      3.290        28.290      0.2537\n1131    pier       3.290      3.290    101.990       136.990      0.5333\n1132 charter      48.906     48.906      4.290        29.290      0.2537\n1133    boat     117.306    117.306     10.290        35.290      0.2537\n1134    boat      71.706     71.706      6.290        31.290      0.2537\n1135    pier      37.506     37.506     76.986        95.486      0.2537\n1136    boat     101.990    101.990     37.506        72.506      0.0678\n1137    pier      37.506     37.506     76.986        95.486      0.2537\n1138 charter      48.906     48.906      4.290        29.290      0.2537\n1139    boat      60.306     60.306      5.290        30.290      0.2537\n1140    boat      71.706     71.706      6.290        31.290      0.2537\n1141    boat      71.706     71.706      6.290        31.290      0.2537\n1142    boat       4.290      4.290    132.990       167.990      0.5333\n1143    boat       5.290      5.290    163.990       198.990      0.5333\n1144 charter      48.906     48.906      4.290        29.290      0.2537\n1145    pier       6.290      6.290    194.990       229.990      0.5333\n1146 charter     180.006    180.006     15.790        40.790      0.2537\n1147 charter      83.106     83.106      7.290        32.290      0.2537\n1148 charter      83.106     83.106      7.290        32.290      0.2537\n1149    pier      37.506     37.506     76.986        95.486      0.2537\n1150 charter      94.506     94.506      8.290        33.290      0.2537\n1151    boat      71.706     71.706      6.290        31.290      0.2537\n1152    boat     163.990    163.990     60.306        95.306      0.0678\n1153    boat      71.706     71.706      6.290        31.290      0.2537\n1154   beach     105.906    105.906    217.386       235.886      0.2537\n1155    boat      30.186     30.186     39.990        63.990      0.1049\n1156    pier       2.290      2.290     70.990       105.990      0.5333\n1157 charter      94.506     94.506      8.290        33.290      0.2537\n1158    pier       1.290      1.290     39.990        74.990      0.5333\n1159    boat     194.990    194.990     71.706       106.706      0.0678\n1160   beach      18.876     18.876     81.510       100.010      0.2537\n1161    boat     259.148    259.148     27.676        57.176      0.0678\n1162 charter      32.076     32.076     49.572        74.572      0.2537\n1163    boat     143.412    143.412     45.288        70.288      0.2537\n1164    pier      23.276     23.276    100.510       119.010      0.2537\n1165    boat     388.434    388.434     69.476       104.476      0.0678\n1166 charter      97.812     97.812     30.888        55.888      0.2537\n1167    pier      52.488     52.488    309.096       344.096      0.5333\n1168   beach      23.688     23.688    139.496       174.496      0.5333\n1169 charter     181.896    181.896     97.812       132.812      0.0678\n1170    pier      23.688     23.688    139.496       174.496      0.5333\n1171    boat     255.150    255.150    106.434       141.434      0.5333\n1172    boat     164.834    164.834    155.802       190.802      0.0678\n1173 charter      45.402     45.402     45.402        63.902      0.2537\n1174   beach      62.634     62.634    123.552       152.552      0.0678\n1175    boat      91.834     91.834     86.802       121.802      0.0678\n1176 charter     121.034    121.034    114.402       149.402      0.0678\n1177   beach     121.836    121.836    203.346       238.346      0.5333\n1178    pier     150.236    150.236    250.746       285.746      0.5333\n1179   beach     235.436    235.436    392.946       427.946      0.5333\n1180    pier      65.036     65.036    108.546       143.546      0.5333\n1181   beach      36.636     36.636     61.146        96.146      0.5333\n1182    boat     339.890    339.890    235.436       260.436      0.2537\n     catch.pier catch.boat catch.charter     income\n1        0.0503     0.2601        0.5391  7083.3317\n2        0.0451     0.1574        0.4671  1249.9998\n3        0.4522     0.2413        1.0266  3749.9999\n4        0.0789     0.1643        0.5391  2083.3332\n5        0.0503     0.1082        0.3240  4583.3320\n6        0.4522     0.1665        0.3975  4583.3320\n7        0.0789     0.1643        0.5391  8750.0010\n8        0.0789     0.0102        0.0209  2083.3332\n9        0.1498     0.0233        0.0219  3749.9999\n10       0.1498     0.0233        0.0219  2916.6666\n11       0.0451     0.1574        0.4671  3749.9999\n12       0.4522     0.2413        1.0266  7083.3317\n13       0.0451     0.0023        0.0046  1249.9998\n14       0.0789     0.0014        0.0029  2083.3332\n15       0.1498     0.2339        0.6288  8750.0010\n16       0.0789     0.1643        0.5391  5416.6667\n17       0.0451     0.1574        0.4671  5416.6667\n18       0.0079     0.0613        0.3087  2916.6666\n19       0.0069     0.0361        0.4216  4583.3320\n20       0.0451     0.1574        0.4671  4583.3320\n21       0.4522     0.0156        0.0058  7916.6663\n22       0.0451     0.0023        0.0046  8750.0010\n23       0.4522     0.1665        0.3975  2083.3332\n24       0.0079     0.0613        0.3087  2916.6666\n25       0.0789     0.0559        0.6456  2916.6666\n26       0.4522     0.2413        1.0266  1249.9998\n27       0.0451     0.1574        0.4671  4583.3320\n28       0.0789     0.0897        1.0905  7083.3317\n29       0.4522     0.0156        0.0058  1249.9998\n30       0.4522     0.0156        0.0058  2916.6666\n31       0.0451     0.0023        0.0046  2916.6666\n32       0.0079     0.0613        0.3087  4583.3320\n33       0.0451     0.0023        0.0046  2916.6666\n34       0.0789     0.0014        0.0029  3749.9999\n35       0.0079     0.0613        0.3087  2083.3332\n36       0.0069     0.0361        0.4216  2916.6666\n37       0.0789     0.0014        0.0029 12499.9980\n38       0.1498     0.0531        0.0052  1249.9998\n39       0.4522     0.0156        0.0058  2083.3332\n40       0.0789     0.1643        0.5391  2916.6666\n41       0.0789     0.1643        0.5391  2916.6666\n42       0.0789     0.0897        1.0905  2916.6666\n43       0.4522     0.2413        1.0266  4583.3320\n44       0.1498     0.7369        2.3101  3749.9999\n45       0.4522     0.2413        1.0266  4583.3320\n46       0.0789     0.0014        0.0029  6250.0013\n47       0.4522     0.2413        1.0266  7083.3317\n48       0.4522     0.2413        1.0266  1249.9998\n49       0.0789     0.1643        0.5391  3749.9999\n50       0.0789     0.1643        0.5391  4583.3320\n51       0.4522     0.0156        0.0058  3749.9999\n52       0.0789     0.1643        0.5391  2083.3332\n53       0.4522     0.2413        1.0266  3749.9999\n54       0.0069     0.0361        0.4216  1249.9998\n55       0.0079     0.0613        0.3087  4583.3320\n56       0.0451     0.0023        0.0046  2083.3332\n57       0.4522     0.0156        0.0058  2916.6666\n58       0.0079     0.0613        0.3087  2083.3332\n59       0.4522     0.0156        0.0058  5416.6667\n60       0.4522     0.2413        1.0266  2916.6666\n61       0.0789     0.0014        0.0029  2083.3332\n62       0.0503     0.2601        0.5391  4583.3320\n63       0.0069     0.0361        0.4216  3749.9999\n64       0.0451     0.1574        0.4671  3749.9999\n65       0.0789     0.1643        0.5391  3749.9999\n66       0.4522     0.2413        1.0266  1249.9998\n67       0.4522     0.2413        1.0266  3749.9999\n68       0.4522     0.1665        0.3975  3749.9999\n69       0.4522     0.2413        1.0266  5416.6667\n70       0.0451     0.1574        0.4671  2916.6666\n71       0.0451     0.0023        0.0046  2916.6666\n72       0.0789     0.0102        0.0209  2083.3332\n73       0.4522     0.1665        0.3975  7916.6663\n74       0.0069     0.0361        0.4216  5416.6667\n75       0.0451     0.0023        0.0046  6250.0013\n76       0.0789     0.1643        0.5391  3749.9999\n77       0.0789     0.1643        0.5391  7916.6663\n78       0.0503     0.2601        0.5391  1249.9998\n79       0.0069     0.0361        0.4216  2916.6666\n80       0.4522     0.2413        1.0266  2083.3332\n81       0.4522     0.0156        0.0058  1249.9998\n82       0.0789     0.0014        0.0029  2916.6666\n83       0.4522     0.1665        0.3975  3749.9999\n84       0.0451     0.1574        0.4671  1249.9998\n85       0.0014     0.0626        0.2773  2916.6666\n86       0.1498     0.6817        2.3014   416.6667\n87       0.0789     0.0559        0.6456  6250.0013\n88       0.0789     0.0897        1.0905  3749.9999\n89       0.4522     0.2413        1.0266  2083.3332\n90       0.1498     0.2339        0.6288 12499.9980\n91       0.4522     0.0156        0.0058  3749.9999\n92       0.0451     0.1574        0.4671  5416.6667\n93       0.0789     0.0102        0.0209  6250.0013\n94       0.0789     0.0102        0.0209  7083.3317\n95       0.4522     0.0051        1.0266 11250.0010\n96       0.0789     0.0102        0.0209  5416.6667\n97       0.0789     0.0897        1.0905  7083.3317\n98       0.0052     0.0732        0.1726  6250.0013\n99       0.1498     0.2339        0.6288  5416.6667\n100      0.1498     0.2339        0.6288  3749.9999\n101      0.1498     0.2339        0.6288  2083.3332\n102      0.1498     0.2339        0.6288  3749.9999\n103      0.0025     0.0108        0.2377  2916.6666\n104      0.0789     0.0559        0.6456  2083.3332\n105      0.0052     0.0732        0.1726  7916.6663\n106      0.4522     0.1665        0.3975  8750.0010\n107      0.1498     0.6817        2.3014  7083.3317\n108      0.0052     0.0732        0.1726  4583.3320\n109      0.0789     0.1643        0.5391   416.6667\n110      0.4522     0.2413        1.0266  3749.9999\n111      0.0025     0.0108        0.2377  5416.6667\n112      0.0025     0.0108        0.2377  2083.3332\n113      0.0052     0.0732        0.1726  1249.9998\n114      0.1498     0.0233        0.0219  3749.9999\n115      0.0789     0.0559        0.6456  6250.0013\n116      0.0451     0.1574        0.4671  3749.9999\n117      0.1498     0.0233        0.0219  5416.6667\n118      0.0789     0.0102        0.0209  3749.9999\n119      0.4522     0.2413        1.0266  2916.6666\n120      0.0789     0.1643        0.0041  7083.3317\n121      0.1498     0.2339        0.6288  3749.9999\n122      0.0789     0.0897        1.0905 12499.9980\n123      0.0789     0.0897        1.0905  2916.6666\n124      0.1498     0.2339        0.6288  7916.6663\n125      0.0789     0.0102        0.0209  7083.3317\n126      0.0789     0.0102        0.0209  8750.0010\n127      0.1498     0.2339        0.6288  7083.3317\n128      0.0052     0.0732        0.1726  3749.9999\n129      0.1498     0.2339        0.6288  6250.0013\n130      0.0789     0.0102        0.0209 12499.9980\n131      0.0025     0.0108        0.2377 12499.9980\n132      0.0789     0.0559        0.6456  6250.0013\n133      0.0052     0.0732        0.1726  7916.6663\n134      0.0503     0.0143        0.0289  2916.6666\n135      0.0503     0.0143        0.0289  8750.0010\n136      0.4522     0.0156        0.0058 12499.9980\n137      0.0025     0.0108        0.2377  3749.9999\n138      0.0789     0.0559        0.6456  3749.9999\n139      0.0069     0.0361        0.4216  1249.9998\n140      0.4522     0.2413        1.0266  4583.3320\n141      0.1498     0.2339        0.6288  6250.0013\n142      0.4522     0.1665        0.3975   416.6667\n143      0.0789     0.0897        1.0905  7083.3317\n144      0.0025     0.0108        0.2377  4583.3320\n145      0.4522     0.2413        1.0266  6250.0013\n146      0.0451     0.0023        0.0046  3749.9999\n147      0.0014     0.0626        0.2773  7916.6663\n148      0.4522     0.0156        0.0058  4583.3320\n149      0.0789     0.0897        1.0905  8750.0010\n150      0.4522     0.0156        0.0058  3749.9999\n151      0.4522     0.0156        0.0058  3749.9999\n152      0.4522     0.0156        0.0058  1249.9998\n153      0.0079     0.0613        0.3087  7083.3317\n154      0.0079     0.0613        0.3087  5416.6667\n155      0.4522     0.2413        1.0266  6250.0013\n156      0.0503     0.0276        0.0029  2916.6666\n157      0.0451     0.1574        0.4671  4583.3320\n158      0.0451     0.0023        0.0046  5416.6667\n159      0.0789     0.1643        0.5391  5416.6667\n160      0.4522     0.2413        1.0266  3749.9999\n161      0.4522     0.0051        1.0266  4583.3320\n162      0.4522     0.2413        1.0266  3749.9999\n163      0.1498     0.6817        2.3014  2916.6666\n164      0.0789     0.1643        0.5391  4583.3320\n165      0.0069     0.0361        0.4216  6250.0013\n166      0.0789     0.1643        0.5391  1249.9998\n167      0.0503     0.2601        0.5391  2916.6666\n168      0.0503     0.0143        0.0289  4583.3320\n169      0.1498     0.2339        0.6288  6250.0013\n170      0.0503     0.2601        0.5391  4583.3320\n171      0.1498     0.0233        0.0219  6250.0013\n172      0.0069     0.0361        0.4216  5416.6667\n173      0.4522     0.0156        0.0058  3749.9999\n174      0.0789     0.1643        0.5391  2083.3332\n175      0.0069     0.0361        0.4216  3749.9999\n176      0.0789     0.0897        1.0905  2916.6666\n177      0.4522     0.0051        1.0266  6250.0013\n178      0.0789     0.0559        0.6456  3749.9999\n179      0.4522     0.2413        1.0266  7083.3317\n180      0.0503     0.1082        0.3240  2916.6666\n181      0.0789     0.1643        0.5391  5416.6667\n182      0.4522     0.2413        1.0266  2916.6666\n183      0.4522     0.2413        1.0266  3749.9999\n184      0.0069     0.0361        0.4216  1249.9998\n185      0.0789     0.0014        0.0029  2083.3332\n186      0.4522     0.2413        1.0266  2083.3332\n187      0.0069     0.0361        0.4216  4583.3320\n188      0.0069     0.0361        0.4216  4583.3320\n189      0.1498     0.2339        0.6288  3749.9999\n190      0.0789     0.0102        0.0209  6250.0013\n191      0.0079     0.0613        0.3087  9583.3357\n192      0.4522     0.0051        1.0266  4583.3320\n193      0.4522     0.1665        0.3975  3749.9999\n194      0.1498     0.2339        0.6288  2083.3332\n195      0.0789     0.0102        0.0209  1249.9998\n196      0.4522     0.2413        1.0266  3749.9999\n197      0.4522     0.1665        0.3975  4583.3320\n198      0.0503     0.2601        0.5391  2916.6666\n199      0.0025     0.0108        0.2377  1249.9998\n200      0.0503     0.0016        0.1176   416.6667\n201      0.0789     0.0559        0.6456  4583.3320\n202      0.0789     0.1643        0.5391  7916.6663\n203      0.0069     0.0361        0.4216  8750.0010\n204      0.0025     0.0499        0.2421  1249.9998\n205      0.4522     0.2413        1.0266  2083.3332\n206      0.1498     0.2339        0.6288  2916.6666\n207      0.0451     0.0023        0.0046  2916.6666\n208      0.0451     0.1574        0.4671  4583.3320\n209      0.0503     0.0276        0.0029  5416.6667\n210      0.0789     0.0014        0.0029  4583.3320\n211      0.4522     0.2413        1.0266  1249.9998\n212      0.1498     0.6817        2.3014  7916.6663\n213      0.4522     0.0156        0.0058  6250.0013\n214      0.0789     0.1643        0.5391  2916.6666\n215      0.0052     0.1491        0.2421  1249.9998\n216      0.4522     0.2413        1.0266   416.6667\n217      0.0789     0.1643        0.5391 12499.9980\n218      0.4522     0.0156        0.0058  2083.3332\n219      0.4522     0.0156        0.0058  5416.6667\n220      0.4522     0.0156        0.0058  3749.9999\n221      0.4522     0.2413        1.0266  8750.0010\n222      0.4522     0.0156        0.0058  4583.3320\n223      0.0451     0.1574        0.4671 12499.9980\n224      0.0789     0.0971        0.1648  4583.3320\n225      0.4522     0.2413        1.0266  1249.9998\n226      0.0451     0.1574        0.4671  5416.6667\n227      0.0789     0.0014        0.0029  4583.3320\n228      0.0069     0.0361        0.4216  4583.3320\n229      0.0789     0.0102        0.0209  1249.9998\n230      0.0503     0.2601        0.5391  2083.3332\n231      0.0503     0.0276        0.0029  4583.3320\n232      0.0789     0.1643        0.5391  4583.3320\n233      0.0789     0.0014        0.0029  3749.9999\n234      0.0503     0.0230        0.1648  3749.9999\n235      0.0789     0.1643        0.5391  3749.9999\n236      0.0503     0.2601        0.5391 10416.6660\n237      0.0052     0.1491        0.2421  4583.3320\n238      0.0503     0.2601        0.5391  3749.9999\n239      0.4522     0.2413        1.0266  3749.9999\n240      0.0789     0.0014        0.0029  2083.3332\n241      0.0503     0.0276        0.0029  3749.9999\n242      0.0503     0.0276        0.0029  4583.3320\n243      0.0503     0.0276        0.0029  3749.9999\n244      0.0789     0.1643        0.5391  5416.6667\n245      0.0503     0.2601        0.5391  5416.6667\n246      0.0052     0.1491        0.2421  2916.6666\n247      0.0025     0.0499        0.2421  4583.3320\n248      0.0503     0.2601        0.5391  7083.3317\n249      0.0503     0.2601        0.5391  2916.6666\n250      0.1498     0.0531        0.0052  8750.0010\n251      0.0025     0.0499        0.2421  2083.3332\n252      0.4522     0.2413        1.0266  1249.9998\n253      0.0503     0.0230        0.1648  1249.9998\n254      0.0503     0.0031        0.0041  2083.3332\n255      0.0052     0.1491        0.2421  7083.3317\n256      0.0052     0.1491        0.2421  5416.6667\n257      0.0025     0.0499        0.2421  2083.3332\n258      0.0789     0.1643        0.5391  5416.6667\n259      0.4522     0.0051        1.0266  2916.6666\n260      0.4522     0.0156        0.0058  3749.9999\n261      0.0789     0.0971        0.1648  2916.6666\n262      0.0503     0.2601        0.5391  1249.9998\n263      0.0503     0.0276        0.0029  2083.3332\n264      0.0025     0.0499        0.2421  5416.6667\n265      0.0503     0.0276        0.0029  2083.3332\n266      0.0503     0.0276        0.0029  3749.9999\n267      0.0789     0.0014        0.0029   416.6667\n268      0.0503     0.0276        0.0029  4583.3320\n269      0.0052     0.1491        0.2421  2083.3332\n270      0.0503     0.2601        0.5391  2083.3332\n271      0.0503     0.0276        0.0029  2916.6666\n272      0.4522     0.1665        0.3975  2083.3332\n273      0.0503     0.0276        0.0029  3749.9999\n274      0.0789     0.0014        0.0029  2083.3332\n275      0.0789     0.0971        0.1648  3749.9999\n276      0.0789     0.0971        0.1648  1249.9998\n277      0.4522     0.0051        1.0266  3749.9999\n278      0.0789     0.0014        0.0029  5416.6667\n279      0.0789     0.1643        0.0041 10416.6660\n280      0.4522     0.2413        1.0266  2916.6666\n281      0.0503     0.0230        0.1648  2916.6666\n282      0.0079     0.0613        0.3087  5416.6667\n283      0.0789     0.0971        0.1648  4583.3320\n284      0.0079     0.0613        0.3087  6250.0013\n285      0.0069     0.0361        0.4216  2083.3332\n286      0.0025     0.0499        0.2421  2916.6666\n287      0.4522     0.2413        1.0266  1249.9998\n288      0.0789     0.1643        0.5391  1249.9998\n289      0.1498     0.0233        0.0219  2083.3332\n290      0.0789     0.1643        0.5391  2916.6666\n291      0.4522     0.0051        1.0266  2916.6666\n292      0.0451     0.1574        0.4671  2083.3332\n293      0.0789     0.0971        0.1648  1249.9998\n294      0.0789     0.1643        0.5391  4583.3320\n295      0.0503     0.2601        0.5391  8750.0010\n296      0.4522     0.2413        1.0266 12499.9980\n297      0.4522     0.0051        1.0266  5416.6667\n298      0.4522     0.2413        1.0266  4583.3320\n299      0.0503     0.0230        0.1648  3749.9999\n300      0.4522     0.2413        1.0266  3749.9999\n301      0.0789     0.0971        0.1648  5416.6667\n302      0.0451     0.0023        0.0046  2916.6666\n303      0.0503     0.0276        0.0029  2083.3332\n304      0.0503     0.2601        0.5391  6250.0013\n305      0.0503     0.0276        0.0029  3749.9999\n306      0.0503     0.2601        0.5391  2083.3332\n307      0.0503     0.2601        0.5391  8750.0010\n308      0.0503     0.0276        0.0029  2916.6666\n309      0.0025     0.0499        0.2421  2916.6666\n310      0.0503     0.2601        0.5391  2916.6666\n311      0.0503     0.0276        0.0029  2916.6666\n312      0.0451     0.0023        0.0046  2083.3332\n313      0.4522     0.0051        1.0266  2916.6666\n314      0.0503     0.0276        0.0029  3749.9999\n315      0.0451     0.1574        0.4671  4583.3320\n316      0.0052     0.1491        0.2421  2916.6666\n317      0.0789     0.1643        0.5391  4583.3320\n318      0.0503     0.2601        0.5391  4583.3320\n319      0.0503     0.0276        0.0029  2916.6666\n320      0.0052     0.1491        0.2421  2083.3332\n321      0.0789     0.1643        0.0041  2083.3332\n322      0.0503     0.2601        0.5391  2916.6666\n323      0.0503     0.2601        0.5391  1249.9998\n324      0.0503     0.2601        0.5391  1249.9998\n325      0.0503     0.2601        0.5391  2916.6666\n326      0.0503     0.2601        0.5391  6250.0013\n327      0.0503     0.2601        0.5391  5416.6667\n328      0.0503     0.2601        0.5391 10416.6660\n329      0.0503     0.0230        0.1648  2083.3332\n330      0.0052     0.1491        0.2421  4583.3320\n331      0.0789     0.0971        0.1648  2083.3332\n332      0.0503     0.0276        0.0029  2916.6666\n333      0.0503     0.0276        0.0029  4583.3320\n334      0.0025     0.0499        0.2421  6250.0013\n335      0.0503     0.2601        0.5391  2916.6666\n336      0.0503     0.2601        0.5391  4583.3320\n337      0.0503     0.0276        0.0029  1249.9998\n338      0.0503     0.0276        0.0029  3749.9999\n339      0.0503     0.0276        0.0029  2083.3332\n340      0.0503     0.0276        0.0029  1249.9998\n341      0.0789     0.0014        0.0029  2916.6666\n342      0.0503     0.0276        0.0029  4583.3320\n343      0.0503     0.2601        0.5391  7083.3317\n344      0.4522     0.2413        1.0266  3749.9999\n345      0.0789     0.0897        1.0905  5416.6667\n346      0.0503     0.0276        0.0029  6250.0013\n347      0.0079     0.0613        0.3087  2916.6666\n348      0.0789     0.0014        0.0029  2083.3332\n349      0.0503     0.2601        0.5391  5416.6667\n350      0.0789     0.1643        0.5391  7916.6663\n351      0.0503     0.2601        0.5391  7916.6663\n352      0.0503     0.0276        0.0029  2916.6666\n353      0.0503     0.0230        0.1648  5416.6667\n354      0.0503     0.2601        0.5391  5416.6667\n355      0.0789     0.1643        0.5391  4583.3320\n356      0.0069     0.0361        0.4216  6250.0013\n357      0.0503     0.2601        0.5391  2916.6666\n358      0.1498     0.0531        0.0052  2916.6666\n359      0.0503     0.2601        0.5391  3749.9999\n360      0.0503     0.2601        0.5391  6250.0013\n361      0.0789     0.1643        0.0041  7083.3317\n362      0.0503     0.2601        0.5391  1249.9998\n363      0.0503     0.2601        0.5391  1249.9998\n364      0.0503     0.2601        0.5391  4583.3320\n365      0.0451     0.0238        0.0468  3749.9999\n366      0.0789     0.0897        1.0905  2083.3332\n367      0.0789     0.0559        0.6456  2083.3332\n368      0.0451     0.1574        0.4671  3749.9999\n369      0.0789     0.0102        0.0209  1249.9998\n370      0.0069     0.0361        0.4216  1249.9998\n371      0.0789     0.1643        0.5391  1249.9998\n372      0.0789     0.1643        0.5391   416.6667\n373      0.4522     0.0156        0.0058  5416.6667\n374      0.0069     0.0361        0.4216  2083.3332\n375      0.0052     0.1491        0.2421   416.6667\n376      0.0503     0.2601        0.5391  3749.9999\n377      0.0789     0.0102        0.0209  5416.6667\n378      0.0451     0.0023        0.0046 12499.9980\n379      0.4522     0.2413        1.0266  4583.3320\n380      0.0789     0.0559        0.6456  2083.3332\n381      0.0789     0.0014        0.0029  2916.6666\n382      0.0451     0.0023        0.0046  2916.6666\n383      0.0052     0.0732        0.1726  2916.6666\n384      0.4522     0.2413        1.0266   416.6667\n385      0.4522     0.0156        0.0058  2916.6666\n386      0.0079     0.0613        0.3087  5416.6667\n387      0.0451     0.1574        0.4671  7083.3317\n388      0.0789     0.1643        0.5391  5416.6667\n389      0.4522     0.2413        1.0266  5416.6667\n390      0.0025     0.0108        0.2377  6250.0013\n391      0.0789     0.0559        0.6456  2916.6666\n392      0.0789     0.1643        0.5391  1249.9998\n393      0.0789     0.1643        0.5391  4583.3320\n394      0.0789     0.1643        0.5391  3749.9999\n395      0.4522     0.2413        1.0266  8750.0010\n396      0.0789     0.1643        0.5391  2916.6666\n397      0.4522     0.1665        0.3975  4583.3320\n398      0.1498     0.6817        2.3014  2083.3332\n399      0.0025     0.0499        0.2421  3749.9999\n400      0.0451     0.1574        0.4671  3749.9999\n401      0.1498     0.0531        0.0052  3749.9999\n402      0.0789     0.0559        0.6456  3749.9999\n403      0.0451     0.0023        0.0046  4583.3320\n404      0.0069     0.0361        0.4216  4583.3320\n405      0.0451     0.0023        0.0046  2916.6666\n406      0.0069     0.0361        0.4216   416.6667\n407      0.0451     0.0023        0.0046  2916.6666\n408      0.0451     0.0023        0.0046  3749.9999\n409      0.4522     0.0156        0.0058  3749.9999\n410      0.4522     0.0156        0.0058  3749.9999\n411      0.0451     0.0023        0.0046  2916.6666\n412      0.1498     0.0233        0.0219  3749.9999\n413      0.0451     0.1574        0.4671  2083.3332\n414      0.4522     0.2413        1.0266  2916.6666\n415      0.0069     0.0361        0.4216  3749.9999\n416      0.4522     0.2413        1.0266  3749.9999\n417      0.0789     0.1643        0.5391  2083.3332\n418      0.4522     0.0156        0.0058  5416.6667\n419      0.0503     0.0276        0.0029  2083.3332\n420      0.4522     0.0156        0.0058  3749.9999\n421      0.0789     0.0559        0.6456  4583.3320\n422      0.0789     0.0971        0.1648  5416.6667\n423      0.4522     0.2413        1.0266  3749.9999\n424      0.4522     0.2413        1.0266  2916.6666\n425      0.0451     0.0023        0.0046  9583.3357\n426      0.0069     0.0361        0.4216  2916.6666\n427      0.0789     0.0897        1.0905  2083.3332\n428      0.0069     0.0361        0.4216  2916.6666\n429      0.4522     0.0051        1.0266  1249.9998\n430      0.4522     0.1665        0.3975  2916.6666\n431      0.0069     0.0361        0.4216  2083.3332\n432      0.0069     0.0361        0.4216  3749.9999\n433      0.0789     0.1643        0.5391  1249.9998\n434      0.0079     0.0613        0.3087  2083.3332\n435      0.0789     0.1643        0.5391  1249.9998\n436      0.0451     0.0023        0.0046  2083.3332\n437      0.4522     0.2413        1.0266  2916.6666\n438      0.4522     0.1665        0.3975  5416.6667\n439      0.4522     0.2413        1.0266  2916.6666\n440      0.4522     0.2413        1.0266  7916.6663\n441      0.0079     0.0613        0.3087  2083.3332\n442      0.4522     0.2413        1.0266  3749.9999\n443      0.0503     0.2601        0.5391  4583.3320\n444      0.0789     0.1643        0.5391  1249.9998\n445      0.4522     0.1665        0.3975  4583.3320\n446      0.1498     0.0008        0.0027  1249.9998\n447      0.4522     0.2413        1.0266  8750.0010\n448      0.0451     0.1574        0.4671  2916.6666\n449      0.0069     0.0361        0.4216  2916.6666\n450      0.4522     0.0156        0.0058  3749.9999\n451      0.0052     0.1491        0.2421  7916.6663\n452      0.0789     0.1643        0.5391  5416.6667\n453      0.0503     0.0276        0.0029  7916.6663\n454      0.0079     0.0613        0.3087  4583.3320\n455      0.0079     0.0613        0.3087  1249.9998\n456      0.0789     0.1643        0.5391  5416.6667\n457      0.0503     0.2601        0.5391  7083.3317\n458      0.0079     0.0613        0.3087  9583.3357\n459      0.4522     0.2413        1.0266  2916.6666\n460      0.0451     0.0023        0.0046  2916.6666\n461      0.0789     0.0014        0.0029  6250.0013\n462      0.4522     0.2413        1.0266  6250.0013\n463      0.0052     0.1491        0.2421  2916.6666\n464      0.0789     0.1643        0.0041  2916.6666\n465      0.0451     0.0023        0.0046  3749.9999\n466      0.0069     0.0361        0.4216  3749.9999\n467      0.0451     0.0023        0.0046  5416.6667\n468      0.0451     0.0238        0.0468  5416.6667\n469      0.4522     0.2413        1.0266  2916.6666\n470      0.0079     0.0613        0.3087  2083.3332\n471      0.4522     0.1665        0.3975  4583.3320\n472      0.4522     0.0156        0.0058  3749.9999\n473      0.0451     0.0238        0.0468  2083.3332\n474      0.0069     0.0361        0.4216  4583.3320\n475      0.0052     0.1491        0.2421  2916.6666\n476      0.0789     0.1643        0.5391  3749.9999\n477      0.0789     0.0897        1.0905  5416.6667\n478      0.0789     0.1643        0.5391  4583.3320\n479      0.0503     0.2601        0.5391  1249.9998\n480      0.0451     0.0023        0.0046  2916.6666\n481      0.0025     0.0499        0.2421  4583.3320\n482      0.0503     0.0230        0.1648  1249.9998\n483      0.0789     0.0559        0.6456  3749.9999\n484      0.0069     0.0361        0.4216  2916.6666\n485      0.0451     0.1574        0.4671  3749.9999\n486      0.0451     0.0023        0.0046  2916.6666\n487      0.0789     0.1643        0.5391  4583.3320\n488      0.0069     0.0361        0.4216  2083.3332\n489      0.0503     0.2601        0.5391  3749.9999\n490      0.4522     0.2413        1.0266  7083.3317\n491      0.0789     0.1643        0.5391  4583.3320\n492      0.0789     0.1643        0.5391  3749.9999\n493      0.0789     0.1643        0.5391  2083.3332\n494      0.4522     0.0156        0.0058  6250.0013\n495      0.0025     0.0499        0.2421  2083.3332\n496      0.0789     0.0014        0.0029  5416.6667\n497      0.0079     0.0613        0.3087  4583.3320\n498      0.0789     0.0559        0.6456  2083.3332\n499      0.0052     0.0732        0.1726  2083.3332\n500      0.4522     0.0156        0.0058  2083.3332\n501      0.0069     0.0361        0.4216  6250.0013\n502      0.0789     0.1643        0.5391  2916.6666\n503      0.4522     0.2413        1.0266  2916.6666\n504      0.0025     0.0499        0.2421  1249.9998\n505      0.1498     0.0233        0.0219   416.6667\n506      0.4522     0.0156        0.0058   416.6667\n507      0.0789     0.0014        0.0029  1249.9998\n508      0.0789     0.0102        0.0209  3749.9999\n509      0.4522     0.0156        0.0058  4583.3320\n510      0.4522     0.1665        0.3975  5416.6667\n511      0.0789     0.0971        0.1648  2083.3332\n512      0.0451     0.0238        0.0468  3749.9999\n513      0.4522     0.2413        1.0266  7083.3317\n514      0.4522     0.0156        0.0058  4583.3320\n515      0.0789     0.0014        0.0029  2083.3332\n516      0.0052     0.1491        0.2421  5416.6667\n517      0.0503     0.2601        0.5391  2083.3332\n518      0.4522     0.0156        0.0058   416.6667\n519      0.1498     0.0531        0.0052  2916.6666\n520      0.1498     0.0233        0.0219  6250.0013\n521      0.1498     0.6817        2.3014  3749.9999\n522      0.4522     0.1665        0.3975  2083.3332\n523      0.0451     0.0023        0.0046  6250.0013\n524      0.0789     0.1643        0.5391  3749.9999\n525      0.0789     0.1643        0.5391 12499.9980\n526      0.0069     0.0361        0.4216  2083.3332\n527      0.4522     0.2413        1.0266  4583.3320\n528      0.4522     0.1665        0.3975  6250.0013\n529      0.1498     0.6817        2.3014  2916.6666\n530      0.4522     0.2413        1.0266  3749.9999\n531      0.4522     0.0051        1.0266  6250.0013\n532      0.4522     0.2413        1.0266  3749.9999\n533      0.0025     0.0499        0.2421  6250.0013\n534      0.4522     0.0156        0.0058  2916.6666\n535      0.0451     0.1574        0.4671  7083.3317\n536      0.4522     0.0156        0.0058  2916.6666\n537      0.0789     0.0971        0.1648 10416.6660\n538      0.4522     0.2413        1.0266  2083.3332\n539      0.4522     0.2413        1.0266  7083.3317\n540      0.0069     0.0361        0.4216  7916.6663\n541      0.0451     0.0023        0.0046  2916.6666\n542      0.0079     0.0613        0.3087  3749.9999\n543      0.0069     0.0361        0.4216  6250.0013\n544      0.0069     0.0361        0.4216  6250.0013\n545      0.0079     0.0613        0.3087  2916.6666\n546      0.0069     0.0361        0.4216  2916.6666\n547      0.4522     0.2413        1.0266  5416.6667\n548      0.4522     0.2413        1.0266  1249.9998\n549      0.0789     0.1643        0.5391  1249.9998\n550      0.0025     0.0499        0.2421  3749.9999\n551      0.0789     0.1643        0.5391  2083.3332\n552      0.0451     0.0023        0.0046  3749.9999\n553      0.0025     0.0499        0.2421  6250.0013\n554      0.0451     0.1574        0.4671  3749.9999\n555      0.0451     0.0023        0.0046  2916.6666\n556      0.4522     0.0156        0.0058  2916.6666\n557      0.4522     0.2413        1.0266 12499.9980\n558      0.0069     0.0361        0.4216  7083.3317\n559      0.4522     0.0156        0.0058  5416.6667\n560      0.4522     0.1665        0.3975  7083.3317\n561      0.0789     0.0014        0.0029  5416.6667\n562      0.4522     0.0051        1.0266  3749.9999\n563      0.0451     0.0002        0.0021  3749.9999\n564      0.0079     0.0613        0.3087  3749.9999\n565      0.0451     0.0023        0.0046  2083.3332\n566      0.4522     0.2413        1.0266  2916.6666\n567      0.0789     0.1643        0.5391  3749.9999\n568      0.0503     0.0230        0.1648  6250.0013\n569      0.0052     0.1491        0.2421  2916.6666\n570      0.0451     0.0023        0.0046  6250.0013\n571      0.0789     0.1643        0.5391  7083.3317\n572      0.4522     0.2413        1.0266  2083.3332\n573      0.4522     0.1665        0.3975  2083.3332\n574      0.0451     0.1574        0.4671  5416.6667\n575      0.0451     0.0023        0.0046  2916.6666\n576      0.0079     0.0613        0.3087  4583.3320\n577      0.0451     0.0023        0.0046  3749.9999\n578      0.0079     0.0613        0.3087  2916.6666\n579      0.4522     0.0156        0.0058  8750.0010\n580      0.0069     0.0361        0.4216  1249.9998\n581      0.0789     0.0014        0.0029 12499.9980\n582      0.0069     0.0361        0.4216  2083.3332\n583      0.0451     0.0023        0.0046  2916.6666\n584      0.0069     0.0361        0.4216  5416.6667\n585      0.4522     0.0051        1.0266  2916.6666\n586      0.4522     0.0156        0.0058  2916.6666\n587      0.0451     0.1574        0.4671  4583.3320\n588      0.0789     0.1643        0.5391  2916.6666\n589      0.1498     0.0531        0.0052  6250.0013\n590      0.4522     0.1665        0.3975  2916.6666\n591      0.0503     0.0143        0.0289  6250.0013\n592      0.0451     0.0023        0.0046  2916.6666\n593      0.4522     0.0156        0.0058  4583.3320\n594      0.0069     0.0361        0.4216  5416.6667\n595      0.0451     0.0023        0.0046  9583.3357\n596      0.0069     0.0361        0.4216  2083.3332\n597      0.0069     0.0361        0.4216  4583.3320\n598      0.0069     0.0361        0.4216  7083.3317\n599      0.0451     0.1574        0.4671  4583.3320\n600      0.4522     0.2413        1.0266  6250.0013\n601      0.4522     0.0156        0.0058  3749.9999\n602      0.0079     0.0613        0.3087  5416.6667\n603      0.0451     0.0023        0.0046  2916.6666\n604      0.0789     0.0014        0.0029   416.6667\n605      0.4522     0.0156        0.0058  2083.3332\n606      0.4522     0.0156        0.0058  2083.3332\n607      0.4522     0.2413        1.0266  2083.3332\n608      0.0069     0.0361        0.4216  1249.9998\n609      0.0079     0.0613        0.3087 10416.6660\n610      0.0069     0.0361        0.4216  7083.3317\n611      0.4522     0.2413        1.0266  5416.6667\n612      0.0789     0.1643        0.5391  3749.9999\n613      0.0079     0.0613        0.3087  2916.6666\n614      0.0079     0.0613        0.3087 12499.9980\n615      0.4522     0.2413        1.0266  2916.6666\n616      0.0451     0.1574        0.4671  2916.6666\n617      0.0789     0.1643        0.5391  7083.3317\n618      0.4522     0.2413        1.0266 12499.9980\n619      0.0451     0.1574        0.4671  3749.9999\n620      0.0451     0.0238        0.0468  5416.6667\n621      0.1498     0.0233        0.0219  5416.6667\n622      0.4522     0.0156        0.0058  3749.9999\n623      0.4522     0.2413        1.0266  2916.6666\n624      0.0451     0.1574        0.4671 12499.9980\n625      0.0789     0.1643        0.5391  9583.3357\n626      0.0451     0.0238        0.0468  5416.6667\n627      0.0789     0.1643        0.5391  2083.3332\n628      0.0069     0.0361        0.4216  4583.3320\n629      0.0789     0.1643        0.5391  7083.3317\n630      0.0451     0.0023        0.0046  8750.0010\n631      0.4522     0.2413        1.0266  6250.0013\n632      0.0451     0.0023        0.0046  2916.6666\n633      0.0069     0.0361        0.4216  2916.6666\n634      0.0069     0.0361        0.4216  8750.0010\n635      0.4522     0.0156        0.0058 12499.9980\n636      0.4522     0.1665        0.3975  7916.6663\n637      0.0025     0.0108        0.2377  6250.0013\n638      0.0451     0.0238        0.0468  3749.9999\n639      0.0025     0.0499        0.2421  5416.6667\n640      0.4522     0.2413        1.0266  9583.3357\n641      0.0079     0.0613        0.3087  5416.6667\n642      0.0789     0.1643        0.5391  3749.9999\n643      0.0451     0.0023        0.0046 12499.9980\n644      0.4522     0.2413        1.0266 10416.6660\n645      0.0079     0.0613        0.3087  2916.6666\n646      0.0025     0.0499        0.2421  1249.9998\n647      0.0789     0.0897        1.0905  2916.6666\n648      0.0789     0.0102        0.0209  3749.9999\n649      0.0069     0.0361        0.4216  4583.3320\n650      0.0789     0.1643        0.5391  2916.6666\n651      0.0451     0.1574        0.4671  2083.3332\n652      0.4522     0.1665        0.3975  4583.3320\n653      0.0069     0.0361        0.4216  2083.3332\n654      0.4522     0.0156        0.0058  4583.3320\n655      0.0789     0.1643        0.5391  2916.6666\n656      0.0789     0.1643        0.5391  1249.9998\n657      0.0451     0.0238        0.0468 12499.9980\n658      0.0503     0.2601        0.5391  5416.6667\n659      0.4522     0.2413        1.0266  5416.6667\n660      0.1498     0.2339        0.6288  2083.3332\n661      0.1498     0.2339        0.6288  9583.3357\n662      0.0069     0.0361        0.4216 10416.6660\n663      0.0052     0.0732        0.1726  2083.3332\n664      0.4522     0.2413        1.0266  7083.3317\n665      0.0789     0.0102        0.0209  2083.3332\n666      0.0503     0.0143        0.0289  4583.3320\n667      0.1498     0.0233        0.0219 12499.9980\n668      0.0789     0.0897        1.0905  2916.6666\n669      0.0789     0.0102        0.0209 12499.9980\n670      0.0503     0.0143        0.0289  4583.3320\n671      0.0025     0.0108        0.2377  2916.6666\n672      0.0503     0.0143        0.0289  3749.9999\n673      0.0789     0.0559        0.6456  7083.3317\n674      0.0789     0.0102        0.0209  3749.9999\n675      0.0789     0.0102        0.0209  8750.0010\n676      0.1498     0.2339        0.6288  2083.3332\n677      0.0789     0.0897        1.0905  4583.3320\n678      0.0789     0.0102        0.0209  7083.3317\n679      0.0789     0.0102        0.0209  7083.3317\n680      0.0503     0.0143        0.0289  4583.3320\n681      0.0025     0.0108        0.2377  2916.6666\n682      0.0789     0.0102        0.0209  4583.3320\n683      0.0503     0.0143        0.0289  4583.3320\n684      0.0789     0.0897        1.0905  6250.0013\n685      0.0789     0.0559        0.6456  1249.9998\n686      0.0789     0.0102        0.0209  2083.3332\n687      0.1498     0.2339        0.6288  2916.6666\n688      0.1498     0.2339        0.6288 12499.9980\n689      0.1498     0.2339        0.6288  7083.3317\n690      0.1498     0.2339        0.6288  4583.3320\n691      0.0503     0.0016        0.1176  3749.9999\n692      0.0789     0.0897        1.0905  7916.6663\n693      0.0503     0.0143        0.0289  4583.3320\n694      0.0789     0.0102        0.0209  3749.9999\n695      0.1498     0.6817        2.3014  6250.0013\n696      0.1498     0.0082        0.0044  2916.6666\n697      0.0789     0.0897        1.0905  5416.6667\n698      0.1498     0.2339        0.6288  8750.0010\n699      0.0503     0.0016        0.1176  6250.0013\n700      0.0503     0.0143        0.0289  6250.0013\n701      0.1498     0.2339        0.6288  6250.0013\n702      0.0789     0.0559        0.6456  4583.3320\n703      0.0789     0.0559        0.6456  4583.3320\n704      0.0789     0.0559        0.6456  4583.3320\n705      0.1498     0.0233        0.0219  1249.9998\n706      0.1498     0.0233        0.0219  3749.9999\n707      0.0503     0.0143        0.0289  4583.3320\n708      0.1498     0.0233        0.0219  7083.3317\n709      0.1498     0.0233        0.0219  2083.3332\n710      0.1498     0.2339        0.6288  2083.3332\n711      0.1498     0.0233        0.0219  3749.9999\n712      0.1498     0.2339        0.6288  4583.3320\n713      0.0789     0.0102        0.0209  5416.6667\n714      0.1498     0.2339        0.6288  5416.6667\n715      0.1498     0.2339        0.6288  2916.6666\n716      0.1498     0.0233        0.0219  2916.6666\n717      0.0789     0.0897        1.0905  5416.6667\n718      0.0025     0.0108        0.2377  3749.9999\n719      0.0789     0.0897        1.0905  6250.0013\n720      0.0789     0.0559        0.6456  2083.3332\n721      0.1498     0.2339        0.6288  2083.3332\n722      0.0789     0.0102        0.0209  7083.3317\n723      0.0789     0.0559        0.6456  8750.0010\n724      0.0503     0.0016        0.1176  2916.6666\n725      0.0503     0.0143        0.0289  5416.6667\n726      0.1498     0.2339        0.6288  9583.3357\n727      0.0052     0.0732        0.1726  4583.3320\n728      0.0789     0.0102        0.0209  2916.6666\n729      0.1498     0.2339        0.6288  7916.6663\n730      0.0503     0.0143        0.0289  7083.3317\n731      0.0789     0.0559        0.6456  5416.6667\n732      0.0789     0.0897        1.0905  3749.9999\n733      0.0789     0.0897        1.0905  5416.6667\n734      0.0789     0.0559        0.6456  7083.3317\n735      0.1498     0.0233        0.0219  4583.3320\n736      0.0789     0.0897        1.0905  3749.9999\n737      0.0025     0.0108        0.2377  4583.3320\n738      0.0789     0.0897        1.0905  3749.9999\n739      0.1498     0.6817        2.3014  1249.9998\n740      0.0789     0.0897        1.0905  3749.9999\n741      0.0789     0.0102        0.0209  2916.6666\n742      0.0789     0.0102        0.0209  3749.9999\n743      0.1498     0.2339        0.6288  4583.3320\n744      0.0052     0.0732        0.1726  3749.9999\n745      0.1498     0.0233        0.0219  3749.9999\n746      0.0503     0.0143        0.0289  2083.3332\n747      0.1498     0.0233        0.0219  2083.3332\n748      0.1498     0.2339        0.6288  2083.3332\n749      0.0789     0.0897        1.0905  3749.9999\n750      0.1498     0.2339        0.6288  2916.6666\n751      0.0789     0.0559        0.6456  2083.3332\n752      0.1498     0.0233        0.0219  2916.6666\n753      0.0789     0.0102        0.0209  8750.0010\n754      0.0789     0.0559        0.6456  1249.9998\n755      0.0789     0.0897        1.0905  2083.3332\n756      0.0789     0.0102        0.0209  3749.9999\n757      0.1498     0.2339        0.6288  2083.3332\n758      0.0789     0.0102        0.0209  7083.3317\n759      0.0789     0.0102        0.0209  2083.3332\n760      0.1498     0.2339        0.6288  3749.9999\n761      0.0789     0.0102        0.0209 11250.0010\n762      0.0789     0.0559        0.6456  2916.6666\n763      0.0789     0.0559        0.6456  2083.3332\n764      0.0503     0.0143        0.0289  3749.9999\n765      0.0789     0.0102        0.0209  5416.6667\n766      0.0789     0.0897        1.0905  3749.9999\n767      0.1498     0.0233        0.0219  2916.6666\n768      0.0503     0.1082        0.3240  5416.6667\n769      0.0025     0.0108        0.2377  2916.6666\n770      0.1498     0.2339        0.6288  2083.3332\n771      0.1498     0.0233        0.0219  2916.6666\n772      0.1498     0.2339        0.6288   416.6667\n773      0.0789     0.0102        0.0209  5416.6667\n774      0.0789     0.0559        0.6456  3749.9999\n775      0.1498     0.0233        0.0219  2083.3332\n776      0.1498     0.0233        0.0219  2083.3332\n777      0.1498     0.2339        0.6288  5416.6667\n778      0.0789     0.0559        0.6456  6250.0013\n779      0.0069     0.0361        0.4216  2083.3332\n780      0.0789     0.0897        1.0905  7083.3317\n781      0.0025     0.0108        0.2377  5416.6667\n782      0.0789     0.0559        0.6456  4583.3320\n783      0.0503     0.1082        0.3240  3749.9999\n784      0.0789     0.0102        0.0209  2916.6666\n785      0.0789     0.0897        1.0905  5416.6667\n786      0.1498     0.2339        0.6288  5416.6667\n787      0.0789     0.0559        0.6456  5416.6667\n788      0.0789     0.0102        0.0209  4583.3320\n789      0.0789     0.0559        0.6456  6250.0013\n790      0.0503     0.0143        0.0289  2916.6666\n791      0.1498     0.0082        0.0044  2916.6666\n792      0.0052     0.0732        0.1726  2916.6666\n793      0.0789     0.0102        0.0209  5416.6667\n794      0.4522     0.2413        1.0266  3749.9999\n795      0.0789     0.0897        1.0905  3749.9999\n796      0.0503     0.0143        0.0289  4583.3320\n797      0.0025     0.0108        0.2377  4583.3320\n798      0.0025     0.0108        0.2377  3749.9999\n799      0.0789     0.0559        0.6456  6250.0013\n800      0.0025     0.0108        0.2377  5416.6667\n801      0.0789     0.0559        0.6456  1249.9998\n802      0.0503     0.0143        0.0289  2916.6666\n803      0.0789     0.0102        0.0209  1249.9998\n804      0.0789     0.0559        0.6456  2916.6666\n805      0.0503     0.0143        0.0289  2083.3332\n806      0.0789     0.0897        1.0905  6250.0013\n807      0.0789     0.0559        0.6456  1249.9998\n808      0.1498     0.0082        0.0044  6250.0013\n809      0.0052     0.0732        0.1726  3749.9999\n810      0.0789     0.0559        0.6456  2083.3332\n811      0.1498     0.2339        0.6288  2916.6666\n812      0.0789     0.0559        0.6456  2916.6666\n813      0.1498     0.2339        0.6288  7083.3317\n814      0.0789     0.0897        1.0905  2916.6666\n815      0.0503     0.0143        0.0289 12499.9980\n816      0.0503     0.0143        0.0289  1249.9998\n817      0.0503     0.0143        0.0289 10416.6660\n818      0.1498     0.2339        0.6288  9583.3357\n819      0.1498     0.0082        0.0044  2916.6666\n820      0.1498     0.0233        0.0219  1249.9998\n821      0.0503     0.1082        0.3240  2083.3332\n822      0.1498     0.2339        0.6288  2916.6666\n823      0.0789     0.0102        0.0209  6250.0013\n824      0.0789     0.0102        0.0209  4583.3320\n825      0.1498     0.2339        0.6288  2916.6666\n826      0.1498     0.0233        0.0219   416.6667\n827      0.0789     0.0559        0.6456  6250.0013\n828      0.1498     0.0233        0.0219  7916.6663\n829      0.0014     0.0626        0.2773   416.6667\n830      0.0789     0.0102        0.0209  5416.6667\n831      0.0789     0.0102        0.0209  4583.3320\n832      0.0789     0.0897        1.0905  4583.3320\n833      0.0052     0.0732        0.1726 12499.9980\n834      0.0789     0.0102        0.0209  4583.3320\n835      0.0789     0.0102        0.0209  8750.0010\n836      0.0789     0.0559        0.6456  3749.9999\n837      0.0503     0.0143        0.0289  2083.3332\n838      0.0503     0.1082        0.3240  1249.9998\n839      0.0789     0.0102        0.0209  2916.6666\n840      0.1498     0.0233        0.0219  6250.0013\n841      0.0503     0.1082        0.3240  2916.6666\n842      0.0503     0.0143        0.0289  5416.6667\n843      0.0789     0.0559        0.6456  3749.9999\n844      0.1498     0.2339        0.6288  2916.6666\n845      0.1498     0.0233        0.0219  5416.6667\n846      0.0503     0.1082        0.3240  2083.3332\n847      0.0789     0.0102        0.0209  5416.6667\n848      0.0789     0.0559        0.6456  5416.6667\n849      0.1498     0.2339        0.6288  6250.0013\n850      0.0789     0.0897        1.0905  2916.6666\n851      0.0789     0.0559        0.6456   416.6667\n852      0.0789     0.0102        0.0209  3749.9999\n853      0.0503     0.0143        0.0289  4583.3320\n854      0.1498     0.6817        2.3014  2916.6666\n855      0.0052     0.0732        0.1726  1249.9998\n856      0.0503     0.0143        0.0289  5416.6667\n857      0.0503     0.0143        0.0289  1249.9998\n858      0.1498     0.2339        0.6288  2916.6666\n859      0.0503     0.2601        0.5391  2083.3332\n860      0.1498     0.2339        0.6288  3749.9999\n861      0.0503     0.0143        0.0289  8750.0010\n862      0.0789     0.0102        0.0209  2916.6666\n863      0.0789     0.0559        0.6456  1249.9998\n864      0.0503     0.1082        0.3240  5416.6667\n865      0.1498     0.0233        0.0219   416.6667\n866      0.1498     0.0233        0.0219  5416.6667\n867      0.0789     0.0559        0.6456  2916.6666\n868      0.0503     0.0143        0.0289  7083.3317\n869      0.0503     0.0022        0.3240   416.6667\n870      0.1498     0.6817        2.3014  2916.6666\n871      0.4522     0.0156        0.0058  1249.9998\n872      0.1498     0.6817        2.3014  1249.9998\n873      0.4522     0.0156        0.0058  2916.6666\n874      0.1498     0.6817        2.3014  2916.6666\n875      0.4522     0.2413        1.0266  2083.3332\n876      0.1498     0.6817        2.3014  7083.3317\n877      0.1498     0.6817        2.3014  3749.9999\n878      0.1498     0.0531        0.0052  2083.3332\n879      0.1498     0.7369        2.3101   416.6667\n880      0.1498     0.6817        2.3014  2916.6666\n881      0.1498     0.0531        0.0052  6250.0013\n882      0.4522     0.2413        1.0266  2083.3332\n883      0.1498     0.6817        2.3014   416.6667\n884      0.1498     0.7369        2.3101  2916.6666\n885      0.4522     0.2413        1.0266  2083.3332\n886      0.4522     0.2413        1.0266  4583.3320\n887      0.1498     0.0531        0.0052  7083.3317\n888      0.1498     0.6817        2.3014  2083.3332\n889      0.1498     0.0531        0.0052  4583.3320\n890      0.1498     0.0531        0.0052  2916.6666\n891      0.1498     0.6817        2.3014   416.6667\n892      0.4522     0.2413        1.0266   416.6667\n893      0.4522     0.2413        1.0266   416.6667\n894      0.1498     0.6817        2.3014  2083.3332\n895      0.1498     0.6817        2.3014  7083.3317\n896      0.4522     0.0156        0.0058  3749.9999\n897      0.4522     0.2413        1.0266  2916.6666\n898      0.4522     0.2413        1.0266  2083.3332\n899      0.1498     0.0531        0.0052  2916.6666\n900      0.1498     0.7369        2.3101  2916.6666\n901      0.1498     0.0531        0.0052  2083.3332\n902      0.0503     0.0143        0.0289  2083.3332\n903      0.1498     0.6817        2.3014  2916.6666\n904      0.4522     0.2413        1.0266  2083.3332\n905      0.1498     0.6817        2.3014  2916.6666\n906      0.4522     0.2413        1.0266  1249.9998\n907      0.1498     0.0531        0.0052  1249.9998\n908      0.1498     0.6817        2.3014  3749.9999\n909      0.0503     0.0143        0.0289  3749.9999\n910      0.1498     0.6817        2.3014  2916.6666\n911      0.1498     0.0531        0.0052  2916.6666\n912      0.1498     0.6817        2.3014  2083.3332\n913      0.0789     0.0559        0.6456  3749.9999\n914      0.4522     0.2413        1.0266  2083.3332\n915      0.1498     0.6817        2.3014  6250.0013\n916      0.1498     0.6817        2.3014  6250.0013\n917      0.1498     0.0531        0.0052  4583.3320\n918      0.1498     0.0531        0.0052  1249.9998\n919      0.1498     0.0531        0.0052  2083.3332\n920      0.4522     0.2413        1.0266  7083.3317\n921      0.1498     0.6817        2.3014  3749.9999\n922      0.1498     0.6817        2.3014  3749.9999\n923      0.0069     0.0361        0.4216  4583.3320\n924      0.4522     0.0156        0.0058  2083.3332\n925      0.4522     0.0051        1.0266  3749.9999\n926      0.1498     0.7369        2.3101  1249.9998\n927      0.1498     0.6817        2.3014  2083.3332\n928      0.4522     0.2413        1.0266  6250.0013\n929      0.1498     0.7369        2.3101  3749.9999\n930      0.1498     0.7369        2.3101  2083.3332\n931      0.1498     0.6817        2.3014  7083.3317\n932      0.1498     0.6817        2.3014  2916.6666\n933      0.1498     0.0531        0.0052 12499.9980\n934      0.4522     0.2413        1.0266  2083.3332\n935      0.1498     0.7369        2.3101  4583.3320\n936      0.1498     0.6817        2.3014  4583.3320\n937      0.4522     0.2413        1.0266  4583.3320\n938      0.4522     0.2413        1.0266  2916.6666\n939      0.1498     0.0531        0.0052  7083.3317\n940      0.1498     0.7369        2.3101  2916.6666\n941      0.1498     0.6817        2.3014  2916.6666\n942      0.4522     0.2413        1.0266  4583.3320\n943      0.1498     0.6817        2.3014  1249.9998\n944      0.1498     0.7369        2.3101  8750.0010\n945      0.1498     0.7369        2.3101  3749.9999\n946      0.0789     0.0014        0.0029  1249.9998\n947      0.4522     0.0156        0.0058  5416.6667\n948      0.1498     0.6817        2.3014  2916.6666\n949      0.1498     0.6817        2.3014  5416.6667\n950      0.1498     0.6817        2.3014  2083.3332\n951      0.1498     0.6817        2.3014  5416.6667\n952      0.4522     0.2413        1.0266  2916.6666\n953      0.1498     0.6817        2.3014  2916.6666\n954      0.1498     0.6817        2.3014  4583.3320\n955      0.0789     0.0559        0.6456  2083.3332\n956      0.4522     0.2413        1.0266  2916.6666\n957      0.4522     0.2413        1.0266  1249.9998\n958      0.1498     0.6817        2.3014  1249.9998\n959      0.1498     0.6817        2.3014  3749.9999\n960      0.4522     0.0156        0.0058  2083.3332\n961      0.1498     0.6817        2.3014  2916.6666\n962      0.1498     0.7369        2.3101  4583.3320\n963      0.1498     0.0531        0.0052  2916.6666\n964      0.4522     0.1665        0.3975  3749.9999\n965      0.1498     0.6817        2.3014  2916.6666\n966      0.1498     0.0531        0.0052  4583.3320\n967      0.1498     0.6817        2.3014  3749.9999\n968      0.1498     0.6817        2.3014  4583.3320\n969      0.4522     0.2413        1.0266  2916.6666\n970      0.4522     0.0156        0.0058  2916.6666\n971      0.1498     0.6817        2.3014  4583.3320\n972      0.1498     0.6817        2.3014  9583.3357\n973      0.1498     0.0531        0.0052  3749.9999\n974      0.4522     0.2413        1.0266  2083.3332\n975      0.1498     0.0531        0.0052  1249.9998\n976      0.4522     0.1665        0.3975  4583.3320\n977      0.1498     0.6817        2.3014  4583.3320\n978      0.4522     0.2413        1.0266  9583.3357\n979      0.4522     0.2413        1.0266   416.6667\n980      0.4522     0.0156        0.0058  2083.3332\n981      0.1498     0.0233        0.0219  2083.3332\n982      0.4522     0.2413        1.0266   416.6667\n983      0.1498     0.6817        2.3014  1249.9998\n984      0.1498     0.0531        0.0052  3749.9999\n985      0.1498     0.0531        0.0052  2916.6666\n986      0.4522     0.2413        1.0266   416.6667\n987      0.4522     0.2413        1.0266  2083.3332\n988      0.1498     0.7369        2.3101  3749.9999\n989      0.1498     0.6817        2.3014  2083.3332\n990      0.1498     0.6817        2.3014   416.6667\n991      0.1498     0.0531        0.0052  1249.9998\n992      0.1498     0.6817        2.3014  6250.0013\n993      0.1498     0.6817        2.3014  2916.6666\n994      0.4522     0.2413        1.0266  4583.3320\n995      0.4522     0.1665        0.3975  2916.6666\n996      0.4522     0.2413        1.0266  1249.9998\n997      0.1498     0.6817        2.3014  1249.9998\n998      0.4522     0.2413        1.0266  5416.6667\n999      0.1498     0.0531        0.0052  1249.9998\n1000     0.1498     0.6817        2.3014  2916.6666\n1001     0.1498     0.0531        0.0052  3749.9999\n1002     0.4522     0.2413        1.0266  1249.9998\n1003     0.1498     0.0531        0.0052   416.6667\n1004     0.1498     0.0531        0.0052  4583.3320\n1005     0.1498     0.2339        0.6288  3749.9999\n1006     0.1498     0.6817        2.3014  3749.9999\n1007     0.1498     0.0531        0.0052 12499.9980\n1008     0.4522     0.1665        0.3975  1249.9998\n1009     0.1498     0.2339        0.6288  2083.3332\n1010     0.4522     0.2413        1.0266  2083.3332\n1011     0.1498     0.6817        2.3014  2083.3332\n1012     0.4522     0.0051        1.0266  2083.3332\n1013     0.4522     0.1665        0.3975  1249.9998\n1014     0.4522     0.2413        1.0266   416.6667\n1015     0.4522     0.2413        1.0266  4583.3320\n1016     0.0503     0.0143        0.0289  3749.9999\n1017     0.1498     0.0531        0.0052  5416.6667\n1018     0.1498     0.0082        0.0044  4583.3320\n1019     0.1498     0.7369        2.3101  4583.3320\n1020     0.1498     0.6817        2.3014  2083.3332\n1021     0.0789     0.0102        0.0209  5416.6667\n1022     0.0789     0.0102        0.0209  2916.6666\n1023     0.4522     0.2413        1.0266  1249.9998\n1024     0.4522     0.2413        1.0266  2083.3332\n1025     0.0503     0.0143        0.0289  3749.9999\n1026     0.1498     0.6817        2.3014  7916.6663\n1027     0.0789     0.0102        0.0209  2083.3332\n1028     0.4522     0.2413        1.0266  3749.9999\n1029     0.1498     0.6817        2.3014  2083.3332\n1030     0.1498     0.6817        2.3014  3749.9999\n1031     0.4522     0.2413        1.0266  2916.6666\n1032     0.1498     0.0531        0.0052  2916.6666\n1033     0.0789     0.0897        1.0905  1249.9998\n1034     0.1498     0.7369        2.3101  2916.6666\n1035     0.1498     0.0233        0.0219  1249.9998\n1036     0.4522     0.2413        1.0266  1249.9998\n1037     0.0503     0.1082        0.3240  2916.6666\n1038     0.1498     0.0531        0.0052  2083.3332\n1039     0.0503     0.0143        0.0289  6250.0013\n1040     0.1498     0.0531        0.0052  1249.9998\n1041     0.1498     0.6817        2.3014  1249.9998\n1042     0.1498     0.6817        2.3014  2916.6666\n1043     0.4522     0.1665        0.3975  3749.9999\n1044     0.1498     0.7369        2.3101  2083.3332\n1045     0.1498     0.0531        0.0052  3749.9999\n1046     0.0014     0.7369        2.3101  4583.3320\n1047     0.1498     0.6817        2.3014  2916.6666\n1048     0.4522     0.2413        1.0266  2083.3332\n1049     0.4522     0.2413        1.0266  4583.3320\n1050     0.1498     0.7369        2.3101  2916.6666\n1051     0.0789     0.0014        0.0029  2916.6666\n1052     0.1498     0.7369        2.3101  3749.9999\n1053     0.1498     0.6817        2.3014  2916.6666\n1054     0.4522     0.2413        1.0266  2083.3332\n1055     0.4522     0.0156        0.0058  3749.9999\n1056     0.1498     0.6817        2.3014  5416.6667\n1057     0.4522     0.2413        1.0266  2083.3332\n1058     0.1498     0.0531        0.0052  3749.9999\n1059     0.1498     0.0531        0.0052  5416.6667\n1060     0.4522     0.2413        1.0266  1249.9998\n1061     0.1498     0.6817        2.3014  4583.3320\n1062     0.1498     0.7369        2.3101  2916.6666\n1063     0.0014     0.7369        2.3101  2083.3332\n1064     0.4522     0.2413        1.0266  2916.6666\n1065     0.1498     0.6817        2.3014  3749.9999\n1066     0.1498     0.6817        2.3014  2916.6666\n1067     0.4522     0.2413        1.0266  2916.6666\n1068     0.1498     0.7369        2.3101  3749.9999\n1069     0.0789     0.0897        1.0905  1249.9998\n1070     0.1498     0.6817        2.3014  6250.0013\n1071     0.1498     0.6817        2.3014  1249.9998\n1072     0.1498     0.6817        2.3014  2083.3332\n1073     0.0789     0.0897        1.0905  6250.0013\n1074     0.4522     0.0156        0.0058  2916.6666\n1075     0.1498     0.7369        2.3101  2916.6666\n1076     0.0503     0.1082        0.3240  3749.9999\n1077     0.4522     0.2413        1.0266  3749.9999\n1078     0.1498     0.6817        2.3014  1249.9998\n1079     0.1498     0.0531        0.0052  2083.3332\n1080     0.1498     0.7369        2.3101  1249.9998\n1081     0.4522     0.2413        1.0266  2916.6666\n1082     0.0503     0.0143        0.0289  3749.9999\n1083     0.1498     0.6817        2.3014  3749.9999\n1084     0.1498     0.6817        2.3014  2916.6666\n1085     0.0789     0.0102        0.0209  2083.3332\n1086     0.1498     0.7369        2.3101 12499.9980\n1087     0.1498     0.6817        2.3014  3749.9999\n1088     0.1498     0.0531        0.0052  1249.9998\n1089     0.1498     0.6817        2.3014  2916.6666\n1090     0.1498     0.0531        0.0052  4583.3320\n1091     0.1498     0.6817        2.3014 12499.9980\n1092     0.1498     0.6817        2.3014  1249.9998\n1093     0.1498     0.7369        2.3101  2083.3332\n1094     0.4522     0.2413        1.0266  5416.6667\n1095     0.1498     0.7369        2.3101  2916.6666\n1096     0.4522     0.2413        1.0266  1249.9998\n1097     0.1498     0.0531        0.0052  2083.3332\n1098     0.1498     0.6817        2.3014  2083.3332\n1099     0.1498     0.6817        2.3014  2083.3332\n1100     0.1498     0.0531        0.0052  2083.3332\n1101     0.1498     0.0531        0.0052  2916.6666\n1102     0.4522     0.2413        1.0266  2916.6666\n1103     0.1498     0.0531        0.0052  4583.3320\n1104     0.4522     0.2413        1.0266  6250.0013\n1105     0.1498     0.0008        0.0027  6250.0013\n1106     0.4522     0.0051        1.0266   416.6667\n1107     0.1498     0.6817        2.3014  2083.3332\n1108     0.1498     0.6817        2.3014  2916.6666\n1109     0.1498     0.6817        2.3014  2083.3332\n1110     0.1498     0.6817        2.3014  3749.9999\n1111     0.4522     0.2413        1.0266  2083.3332\n1112     0.1498     0.6817        2.3014  2916.6666\n1113     0.1498     0.6817        2.3014  1249.9998\n1114     0.0503     0.0143        0.0289  5416.6667\n1115     0.4522     0.2413        1.0266  4583.3320\n1116     0.1498     0.6817        2.3014  2916.6666\n1117     0.4522     0.2413        1.0266  1249.9998\n1118     0.4522     0.0156        0.0058  4583.3320\n1119     0.1498     0.7369        2.3101 12499.9980\n1120     0.4522     0.2413        1.0266  2916.6666\n1121     0.4522     0.2413        1.0266  2916.6666\n1122     0.0052     0.0732        0.1726  2916.6666\n1123     0.4522     0.1665        0.3975  4583.3320\n1124     0.4522     0.2413        1.0266  7083.3317\n1125     0.1498     0.7369        2.3101  3749.9999\n1126     0.4522     0.2413        1.0266  3749.9999\n1127     0.4522     0.0156        0.0058  2916.6666\n1128     0.1498     0.7369        2.3101  6250.0013\n1129     0.1498     0.0531        0.0052  3749.9999\n1130     0.1498     0.0531        0.0052  2083.3332\n1131     0.4522     0.2413        1.0266  2083.3332\n1132     0.1498     0.7369        2.3101  2916.6666\n1133     0.1498     0.7369        2.3101  7916.6663\n1134     0.1498     0.6817        2.3014  4583.3320\n1135     0.1498     0.0233        0.0219  2083.3332\n1136     0.0789     0.0102        0.0209  2083.3332\n1137     0.1498     0.0082        0.0044  2083.3332\n1138     0.1498     0.6817        2.3014  2916.6666\n1139     0.1498     0.7369        2.3101  3749.9999\n1140     0.1498     0.6817        2.3014  4583.3320\n1141     0.1498     0.6817        2.3014  4583.3320\n1142     0.4522     0.0156        0.0058  2916.6666\n1143     0.0069     0.0361        0.4216  3749.9999\n1144     0.1498     0.6817        2.3014  2916.6666\n1145     0.4522     0.2413        1.0266  4583.3320\n1146     0.1498     0.7369        2.3101 12499.9980\n1147     0.1498     0.6817        2.3014  5416.6667\n1148     0.1498     0.6817        2.3014  5416.6667\n1149     0.1498     0.0233        0.0219  2083.3332\n1150     0.1498     0.6817        2.3014  6250.0013\n1151     0.1498     0.6817        2.3014  4583.3320\n1152     0.0789     0.0102        0.0209  3749.9999\n1153     0.1498     0.0531        0.0052  4583.3320\n1154     0.1498     0.0233        0.0219  7083.3317\n1155     0.0451     0.1574        0.4671   416.6667\n1156     0.4522     0.2413        1.0266  1249.9998\n1157     0.1498     0.6817        2.3014  6250.0013\n1158     0.4522     0.1665        0.3975   416.6667\n1159     0.0789     0.0559        0.6456  4583.3320\n1160     0.1498     0.2339        0.6288  2916.6666\n1161     0.0503     0.0143        0.0289  4583.3320\n1162     0.1498     0.6817        2.3014  5416.6667\n1163     0.1498     0.0531        0.0052  4583.3320\n1164     0.1498     0.0082        0.0044  3749.9999\n1165     0.0789     0.0102        0.0209 12499.9980\n1166     0.1498     0.6817        2.3014  2916.6666\n1167     0.4522     0.0156        0.0058  5416.6667\n1168     0.4522     0.0156        0.0058  2083.3332\n1169     0.0789     0.0897        1.0905  2916.6666\n1170     0.4522     0.2413        1.0266  2083.3332\n1171     0.4522     0.2413        1.0266  5416.6667\n1172     0.0025     0.0108        0.2377  8750.0010\n1173     0.1498     0.0233        0.0219  2083.3332\n1174     0.0789     0.0014        0.0029  2916.6666\n1175     0.0789     0.0102        0.0209  4583.3320\n1176     0.0789     0.0102        0.0209  6250.0013\n1177     0.4522     0.2413        1.0266  2916.6666\n1178     0.4522     0.2413        1.0266  3749.9999\n1179     0.4522     0.2413        1.0266  6250.0013\n1180     0.4522     0.2413        1.0266  1249.9998\n1181     0.4522     0.1665        0.3975   416.6667\n1182     0.1498     0.6817        2.3014  6250.0013\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(Fish <- dfidx(Fishing, varying = 2:9, shape = \"wide\", choice = \"mode\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n~~~~~~~\n first 10 observations out of 4728 \n~~~~~~~\n    mode   income   price  catch    idx\n1  FALSE 7083.332 157.930 0.0678 1:each\n2  FALSE 7083.332 157.930 0.2601 1:boat\n3   TRUE 7083.332 182.930 0.5391 1:rter\n4  FALSE 7083.332 157.930 0.0503 1:pier\n5  FALSE 1250.000  15.114 0.1049 2:each\n6  FALSE 1250.000  10.534 0.1574 2:boat\n7   TRUE 1250.000  34.534 0.4671 2:rter\n8  FALSE 1250.000  15.114 0.0451 2:pier\n9  FALSE 3750.000 161.874 0.5333 3:each\n10  TRUE 3750.000  24.334 0.2413 3:boat\n\n~~~ indexes ~~~~\n   id1     id2\n1    1   beach\n2    1    boat\n3    1 charter\n4    1    pier\n5    2   beach\n6    2    boat\n7    2 charter\n8    2    pier\n9    3   beach\n10   3    boat\nindexes:  1, 2 \n```\n\n\n:::\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntemp <- mountain |> \n  select(realization) %>%\n  mutate(rand = runif(nrow(.))) |> \n  mutate(realization = factor(realization))\nmountain_mlogit <- dfidx(temp, shape = \"long\", choice = \"realization\")\n\nmlogit(realization ~ rand, data = temp)\n```\n:::\n\n\nNever mind. Can't get it to work.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndetach(package:mlogit)\n```\n:::\n\n\n\n## nnet::multinom\n\nThis is an alternative to mlogit that doesn't require reshaping the data. See [here](https://stats.oarc.ucla.edu/r/dae/multinomial-logistic-regression/). It compares all other levels to the reference level. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(nnet)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmountain_mulitnom <- multinom(realization ~ gender3 + state, data = mountain)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# weights:  24 (14 variable)\ninitial  value 3903.369462 \niter  10 value 3034.322054\niter  20 value 2989.285561\nfinal  value 2989.274875 \nconverged\n```\n\n\n:::\n:::\n\nThe output from running this model shows information about iterations. The numbers are the negative log-likelihood. This is multipled by two and is shown in the model summary as the Residual Deviance. That is used when comparing nested models. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mountain_mulitnom)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nmultinom(formula = realization ~ gender3 + state, data = mountain)\n\nCoefficients:\n                 (Intercept) gender3male gender3other   stateUT    stateID\nutah               -1.483513  -1.0397146    -1.071468 0.7742535 -0.3580328\nhyperarticulated   -0.140472  -0.3888622    -1.597108 0.5795590 -0.8351621\n                    stateMT    stateWY\nutah             -1.5071344  0.3150364\nhyperarticulated -0.9990279 -0.5521896\n\nStd. Errors:\n                 (Intercept) gender3male gender3other   stateUT   stateID\nutah               0.1952717  0.13394902     0.291178 0.2032615 0.2520320\nhyperarticulated   0.1131090  0.07785582     0.217914 0.1167654 0.1475948\n                   stateMT   stateWY\nutah             0.3239367 0.2765668\nhyperarticulated 0.1461432 0.1887760\n\nResidual Deviance: 5978.55 \nAIC: 6006.55 \n```\n\n\n:::\n:::\n\nThere's a blog of coefficients and a block of standard errors. These are in logodds. \n\nNo p-values. But we can calculate that with Wald tests, which I guess are z-tests.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(z <- summary(mountain_mulitnom)$coefficients/summary(mountain_mulitnom)$standard.errors)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 (Intercept) gender3male gender3other  stateUT   stateID\nutah               -7.597174   -7.762017    -3.679768 3.809150 -1.420585\nhyperarticulated   -1.241917   -4.994646    -7.329073 4.963447 -5.658480\n                   stateMT   stateWY\nutah             -4.652558  1.139097\nhyperarticulated -6.835954 -2.925105\n```\n\n\n:::\n\n```{.r .cell-code}\n(p <- p <- (1 - pnorm(abs(z), 0, 1)) * 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  (Intercept)  gender3male gender3other      stateUT\nutah             3.019807e-14 8.437695e-15 2.334463e-04 1.394454e-04\nhyperarticulated 2.142672e-01 5.894384e-07 2.318146e-13 6.925287e-07\n                      stateID      stateMT     stateWY\nutah             1.554375e-01 3.278425e-06 0.254662596\nhyperarticulated 1.527192e-08 8.146150e-12 0.003443405\n```\n\n\n:::\n:::\n\n\n\n* So the baseline is standard variant used by Utah women.\n* The log odds of hearing Utah variant verses standard variant will decrease by 1.0397 if moving from female to male. ***\n* The log odds of hearing Utah variant verses standard variant will decrease by 1.0715 if moving from female to nonbinary. ***\n* The log odds of hearing Utah variant verses standard variant will increase by 0.7742 if moving from GenAm to Utah. ***\n* The log odds of hearing Utah variant verses standard variant will decrease by 0.3580 if moving from GenAm to Idaho. NS\n* The log odds of hearing Utah variant verses standard variant will decrease by 1.5071 if moving from GenAm to Montana. ***\n* The log odds of hearing Utah variant verses standard variant will increase by 0.3150 if moving from GenAm to Wyoming. NS\n* The log odds of hearing the hyperarticulated variant verses standard variant will decrease by 0.3888 if moving from female to male. ***\n* etc.\n\nWe can take the exp() of these logodds coeficients to get odds.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(coef(mountain_mulitnom))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 (Intercept) gender3male gender3other  stateUT   stateID\nutah               0.2268394   0.3535556    0.3425055 2.168972 0.6990502\nhyperarticulated   0.8689480   0.6778276    0.2024813 1.785251 0.4338042\n                   stateMT   stateWY\nutah             0.2215439 1.3703093\nhyperarticulated 0.3682372 0.5756879\n```\n\n\n:::\n:::\n\n\n* So the baseline of hearing Utah verses standard is 0.22?\n* The odds of hearing Utah variant verses standard variant will increase by 0.3535 if moving from female to male. \n\nI'm not sure I get this. So, let's extract predicted probabilities. \n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds <- fitted(mountain_mulitnom) |> \n  as_tibble() |> \n  bind_cols(mountain) |> \n  select(state, gender3, standard, utah, hyperarticulated) |> \n  distinct() |> \n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 14 × 5\n   state gender3 standard   utah hyperarticulated\n   <fct> <fct>      <dbl>  <dbl>            <dbl>\n 1 ID    male       0.762 0.0427           0.195 \n 2 ID    female     0.651 0.103            0.245 \n 3 ID    other      0.884 0.0480           0.0675\n 4 MT    female     0.730 0.0367           0.234 \n 5 MT    male       0.810 0.0144           0.176 \n 6 UT    female     0.329 0.162            0.510 \n 7 UT    male       0.449 0.0782           0.472 \n 8 UT    other      0.674 0.114            0.212 \n 9 WY    male       0.690 0.0758           0.234 \n10 WY    female     0.552 0.172            0.276 \n11 WY    other      0.828 0.0882           0.0839\n12 ZZ    female     0.477 0.108            0.415 \n13 ZZ    male       0.599 0.0480           0.353 \n14 ZZ    other      0.798 0.0620           0.140 \n```\n\n\n:::\n\n```{.r .cell-code}\npreds |> \n  filter(gender3 != \"other\") |> \n  pivot_longer(cols = c(standard, utah, hyperarticulated), names_to = \"realization\", values_to = \"probability\") |> \n  mutate(realization = factor(realization, levels = c(\"standard\", \"utah\", \"hyperarticulated\")),\n         state = factor(state, levels = c(\"UT\", \"ID\", \"MT\", \"WY\", \"ZZ\"))) |> \n  ggplot(aes(realization, probability, fill = gender3)) + \n  geom_col(position = position_dodge2()) +\n  scale_y_continuous(breaks = seq(0, 1, 0.2)) + \n  facet_wrap(~state, nrow = 1) + \n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-14-1.png){width=1440}\n:::\n:::\n\n\nOkay, that worked pretty well. Not sure if I can add random effects, so it might be limiting in that way.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndetach(package:nnet)\n```\n:::\n\n\n\n\n## polytomous\n\nThis is a \"one vs. rest\" approach where each pairwise comparison is made. In a three-way model like this, the benefit is now I can compare utah verses hyperarticulated variant, instead of those two to the standard. This package also offers some goodness-of-fit stats.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"polytomous\")\nlibrary(polytomous)\n```\n:::\n\n\nNevermind. It was [removed from CRAN](https://cran.r-project.org/web/packages/polytomous/index.html) in October 2015. \n\n## VGAM::vglm()\n\n[This page](https://repub.github.io/DLC_statistical_guides/docs/R/multinomial-logistic-regression.html) shows how to use VGAM. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(VGAM)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: stats4\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: splines\n```\n\n\n:::\n:::\n\n\nThe syntax is straightforward. Be sure to add the `family = multinomial` argument. I'll move the standard argument to the end so it can be the reference value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmountain_vglm <- vglm(realization ~ gender3 + state,\n                      data = mountain %>% mutate(realization = fct_relevel(realization, \"standard\", after = Inf)),\n                      family = multinomial)\n```\n:::\n\n\nThe summary looks more familiar. It even has p-values. I wish it would use actual text instead of `:1` and `:2`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mountain_vglm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nvglm(formula = realization ~ gender3 + state, family = multinomial, \n    data = mountain %>% mutate(realization = fct_relevel(realization, \n        \"standard\", after = Inf)))\n\nCoefficients: \n               Estimate Std. Error z value Pr(>|z|)    \n(Intercept):1  -1.48355    0.19527  -7.597 3.02e-14 ***\n(Intercept):2  -0.14048    0.11311  -1.242 0.214254    \ngender3male:1  -1.03972    0.13395  -7.762 8.35e-15 ***\ngender3male:2  -0.38886    0.07786  -4.995 5.90e-07 ***\ngender3other:1 -1.07124    0.29115  -3.679 0.000234 ***\ngender3other:2 -1.59710    0.21792  -7.329 2.32e-13 ***\nstateUT:1       0.77431    0.20326   3.809 0.000139 ***\nstateUT:2       0.57955    0.11677   4.963 6.93e-07 ***\nstateID:1      -0.35797    0.25203  -1.420 0.155507    \nstateID:2      -0.83513    0.14759  -5.658 1.53e-08 ***\nstateMT:1      -1.50719    0.32394  -4.653 3.28e-06 ***\nstateMT:2      -0.99906    0.14614  -6.836 8.13e-12 ***\nstateWY:1       0.31508    0.27657   1.139 0.254604    \nstateWY:2      -0.55217    0.18878  -2.925 0.003445 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nNames of linear predictors: log(mu[,1]/mu[,3]), log(mu[,2]/mu[,3])\n\nResidual deviance: 5978.55 on 7092 degrees of freedom\n\nLog-likelihood: -2989.275 on 7092 degrees of freedom\n\nNumber of Fisher scoring iterations: 6 \n\nNo Hauck-Donner effect found in any of the estimates\n\n\nReference group is level  3  of the response\n```\n\n\n:::\n:::\n\n\nThe numbers look very similar to the nnet::multinom version. Not identically, but probably functionally the same. \n\nWe can do a likelihood ratio test to compare models.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmountain_vglm_nogender <- vglm(realization ~ state,\n                      data = mountain,\n                      family = multinomial)\nlrtest(mountain_vglm_nogender, mountain_vglm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLikelihood ratio test\n\nModel 1: realization ~ state\nModel 2: realization ~ gender3 + state\n   #Df  LogLik Df  Chisq Pr(>Chisq)    \n1 7096 -3051.5                         \n2 7092 -2989.3 -4 124.48  < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nCool. That's helpful. Looks like it can't do interactions though.\n\nNo code to show how to get predicted values. But let's see if I can.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds <- fitted(mountain_vglm) |> \n  as_tibble() |> \n  bind_cols(mountain) |> \n  mutate(across(c(standard, utah, hyperarticulated), round, digits = 4)) |> \n  select(state, gender3, standard, utah, hyperarticulated) |> \n  distinct() |> \n  print()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: There was 1 warning in `mutate()`.\nℹ In argument: `across(c(standard, utah, hyperarticulated), round, digits =\n  4)`.\nCaused by warning:\n! The `...` argument of `across()` is deprecated as of dplyr 1.1.0.\nSupply arguments directly to `.fns` through an anonymous function instead.\n\n  # Previously\n  across(a:b, mean, na.rm = TRUE)\n\n  # Now\n  across(a:b, \\(x) mean(x, na.rm = TRUE))\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 14 × 5\n   state gender3 standard   utah hyperarticulated\n   <fct> <fct>      <dbl>  <dbl>            <dbl>\n 1 ID    male       0.762 0.0427           0.195 \n 2 ID    female     0.651 0.103            0.246 \n 3 ID    other      0.884 0.048            0.0675\n 4 MT    female     0.730 0.0367           0.234 \n 5 MT    male       0.810 0.0144           0.176 \n 6 UT    female     0.329 0.162            0.510 \n 7 UT    male       0.449 0.0782           0.472 \n 8 UT    other      0.674 0.114            0.212 \n 9 WY    male       0.690 0.0758           0.234 \n10 WY    female     0.552 0.172            0.276 \n11 WY    other      0.828 0.0882           0.0839\n12 ZZ    female     0.477 0.108            0.415 \n13 ZZ    male       0.599 0.048            0.353 \n14 ZZ    other      0.798 0.062            0.140 \n```\n\n\n:::\n\n```{.r .cell-code}\npreds |> \n  filter(gender3 != \"other\") |> \n  pivot_longer(cols = c(standard, utah, hyperarticulated), names_to = \"realization\", values_to = \"probability\") |> \n  mutate(realization = factor(realization, levels = c(\"standard\", \"utah\", \"hyperarticulated\")),\n         state = factor(state, levels = c(\"UT\", \"ID\", \"MT\", \"WY\", \"ZZ\"))) |> \n  ggplot(aes(realization, probability, fill = gender3)) + \n  geom_col(position = position_dodge2()) +\n  scale_y_continuous(breaks = seq(0, 1, 0.2)) + \n  facet_wrap(~state, nrow = 1) + \n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-21-1.png){width=1440}\n:::\n:::\n\n\nThis looks pretty much the same as the one with `nnet:multinorm`. So that's good. \n\nUse other methods to get confidence intervals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoefs    <- coef(mountain_vglm)    |> as.data.frame() |> rownames_to_column()\nconfints <- confint(mountain_vglm) |> as.data.frame() |> rownames_to_column()\n\nleft_join(coefs, confints, by = \"rowname\") |> \n  janitor::clean_names() |>\n  rename(coef = coef_mountain_vglm,\n         ci_2.5 = x2_5_percent,\n         ci_97.5 = x97_5_percent) |>\n  separate(rowname, into = c(\"predictor\", \"realization\"), sep = \":\") |> \n  print() |> \n  ggplot(aes(predictor, y = coef, fill = realization)) + \n  geom_col()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      predictor realization       coef     ci_2.5     ci_97.5\n1   (Intercept)           1 -1.4835474 -1.8662739 -1.10082096\n2   (Intercept)           2 -0.1404758 -0.3621653  0.08121363\n3   gender3male           1 -1.0397197 -1.3022541 -0.77718534\n4   gender3male           2 -0.3888584 -0.5414531 -0.23626373\n5  gender3other           1 -1.0712386 -1.6418905 -0.50058669\n6  gender3other           2 -1.5970970 -2.0242044 -1.16998965\n7       stateUT           1  0.7743114  0.3759268  1.17269605\n8       stateUT           2  0.5795501  0.3506942  0.80840608\n9       stateID           1 -0.3579720 -0.8519447  0.13600067\n10      stateID           2 -0.8351313 -1.1244106 -0.54585201\n11      stateMT           1 -1.5071856 -2.1421029 -0.87226831\n12      stateMT           2 -0.9990648 -1.2855014 -0.71262814\n13      stateWY           1  0.3150752 -0.2269856  0.85713603\n14      stateWY           2 -0.5521662 -0.9221591 -0.18217333\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}