---
layout: post
title:  "Brand Yourself 3"
date:   2020-03-03
categories:
  - How-to Guides
  - Presentations
redirect_from: 
  - "/brand-yourself"
  - "/brand_yourself"
  - "/pages/brand-yourself"
  - "/pages/brand_yourself"
---

:::callout-tip
Download the slides [here](/downloads/200303-brand-yourself_linguistics.pdf)
:::


Today, I led a professionalization workshop as a part of the Graduate Research Workshop Series, sponsored by UGA Libraries. In it, I talked about different ways grad students can boost their online presence through building a personal webpage, utilizing social media, and finding their field's conversation---basically, how to make yourself more googleable. In today's job market, there's no surefire way to ensure you'll get hired. But increasing your online presence and making yourself more googleable probably helps. I spent the workshop discussing academic social media, building a personal webpage, and using Twitter to join the conversation. At the end, I challenged people to not leave the room until they had built some sort of new online profile they didn't have when they walked in.

*Additional Materials*: I've given this presentation several times, each one with some updated information. You can see the (very similar) slides from [September 2019](/downloads/190920-brand-yourself.pdf), [September 2018](/downloads/180928-brand-yourself.pdf), from [April 2017](/downloads/170413-brand-yourself.pdf) and from [November 2016](/blog/brand-yourself). My views on a few things have changed since then (I value personal webpages more and academic social media less) and there are a few topics that were cut in the latest version.