---
layout: post
title: NWAV49
date: 2021-10-18 08:00:00 -0400
aliases:
 - /nwav49
categories:
  - Conferences
  - Methods
  - Presentations
  - Research
  - Simulations
  - South
---

I'm at New Ways of Analyzing Variation 49 online right now! Other than an quick online satellite session of LabPhon last summer, I haven't attended a conference since November 2019 when we hosted LCUGA at UGA. Anyway, I'm excited to be conferencing again and while I miss seeing colleagues in-person, this online format isn't bad. Anyway, on this page you'll find links to the slides and YouTube videos of my two talks.

<br/>

## Order of Operations in Sociophonetic Analysis

:::callout-tip
Download the poster [here](/downloads/211019-NWAV49_OoO.pdf)!
:::


I'm very excited and nervous about this Order of Operations one. As it turns out, even if you start with the exact same spreadsheet and use the exact same functions, if you do those function in different orders, it'll produce different results. Sometimes drastically different results. I did this by processing a spreadsheet 5,040 unique ways and got a whole range of results. To me at least, it's making me rethink how I process my data and how I can interpret others' results when the order isn't explicitly reported in the methods section of a paper.

<iframe width="560" height="315" src="https://www.youtube.com/embed/8TEip-Fixyw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>






## 100 Years of Georgia English

:::callout-tip
Download the poster [here](/downloads/211019-NWAV49_Georgia.pdf)!
:::

As a continuation of some work I did as a grad student, [Peggy Renwick](http://faculty.franklin.uga.edu/mrenwick/) and I presented our research on Georgia English vowels and how they've changed over 100 years. Basically, all of them have. The Southern Vowel Shift seems to have undergone a rise and fall, perhaps peaking in those born around WWII. Meanwhile, back vowels are fronting. Younger people today have something like the Low-Back-Merger Shift, but flavored with some Southernisms still. You'll hear more about this project in later conferences too.

<iframe width="560" height="315" src="https://www.youtube.com/embed/USF6fspxiGU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br/>

