---
layout: post
title: "Bill Labov"
date: 2024-12-18 09:54:00 -0600
date-modified: last-modified
categories: 
  - Personal
---

::: {.callout-note}
This is edited from an email that I sent out this morning to the students in my undergraduate sociolinguistics course that just finished teaching. There is so much more I could say but I wanted to keep it focused on what they might know. I hope there aren't any inaccuracies in what I've written. I only knew Bill Labov from a distance but he was still an influential figure for me.
:::


Dear all,

It is with a heavy heart that I inform you that Bill Labov---the linguist behind the fourth floor study and Martha's Vineyard Island study and the founder of variationist sociolinguistics---passed away yesterday at the ripe age of 97 at his home with his wife by his side. 

Looking through this semester, I mentioned Labov at least nine times. He introduced attention to speech, the observer's paradox, and the vernacular principle to linguistics and created the sociolinguistic interview. With his dissertation in New York, he introduced the idea of systematic variation or, as he puts it, ordered heterogeneity. He was the one to point out the gender paradox. He popularized Herzog's and Garde's principles in the study of language change (and coined those terms). He supervised the creation of the Penn Neighborhood Corpus and supervised students' sociolinguistic interviews around Philadelphia for decades. That corpus now serves as an invaluable resource for tracking phonetic change over time. Looking back, I'm surprised that's all I've said about him, because there are so many other important ideas he's introduced to the field. 

He was a prolific writer and extremely involved in the field. He founded *Language in Society* in 1972, which has since become a premiere venue for sociolinguistics research. He also founded another extremely influential journal, *Language Variation and Change* and edited it for a long time. He was a former president of the Linguistic Society of America and the American Dialect Society. He has numerous books, many of which are foundational in sociolinguistics. His last one, *Conversations with Strangers*, which he wrote with his wife, was published just last year and contains stories about the awesome things he's learned from people in the 1000+ sociolinguistic interviews he conducted. (If you've ever done a sociolinguistic interview, you'll find that *everyone* has a cool story.) I happened to buy that book recently, so that'll be what I read this evening.

He mentored [countless](https://academictree.org/linguistics/tree.php?pid=24968&fbclid=IwZXh0bgNhZW0CMTAAAR0k0VUZutEQngweBenpabuZMw8o4-hQ_XY4Auu60uAV9q8clumQyUNAsfI_aem_a9n9R6rxPmVLJOnGmS7X2A) students at the University of Pennsylvania, many of whom have gone on to be their own giants in sociolinguistics. Among those whose ideas I've brought into class include Penny Eckert (she did the Jocks vs. Burnouts study and is the founder of 3rd Wave Sociolinguistics and brought ideas like indexicality to sociolinguistics), John Rickford (leading figure on African American English and proponent of the Creole Origins Hypothesis of African American English), John Baugh (housing discrimination), Anne Charity-Hudley (educational linguistics and linguistic activism). Many of them have then gone to mentor other giants in sociolinguistics. I can trace my academic lineage to Labov through Penny Eckert and can call him my academic great-great-grandfather. 

While entire [books](https://www.bloomsbury.com/us/labov-a-guide-for-the-perplexed-9781441158529/) and [annotated bibliographies](https://www.oxfordbibliographies.com/display/document/obo-9780199772810/obo-9780199772810-0195.xml) have been written about his scholarly work, perhaps his bigger contribution to the world is in social activism and the pursuit of linguistic justice. He not only coined the "Principle of Error Correction" and the "Principle of Debt Incurred" as nice ideas, but he lived them too: he was an early researcher of African American English and, 30 years later, testified at a senate hearing on the legitimacy of African American English in the wake of the Oakland Ebonics Controversy. He was a champion for the underdog, marginalized communities, and children and did countless acts of uncompensated work in the community, far beyond what is expected from a professor.

All who knew him personally describe him so positively. He regularly cites older scholars, lesser-known researchers, and students in his own and he acknowledges that many of the ideas we attribute to him actually came from someone else. He was humble in his contributions and was so happy to hear of someone proving him wrong. He was his students' loudest cheerleader and saw the potential in them before they did themselves. He attended their extra-curricular activities and weddings, and met their friends and families. He is the kind of mentor I try to be like. [Here](https://jofrhwld.github.io/blog/posts/2024/12/2024-12-17_in-remembrance/) is a very nice tribute by Joe Fruehwald that I think captures the kinds of things I've heard from his students. [This post in Language Log](https://languagelog.ldc.upenn.edu/nll/?p=67399) also shares these sentiments. If you look up other linguists on social media right now, you'll see numerous other similar tributes. As for me, he attended my very first conference presentation in 2015 where I talked about address forms among Latter-day Saints (which shows that even he was willing to listen to students' work) and while I did have the opportunity to see him speak at various conferences, unfortunately, I never had a chance to meet him. So all I know about him I learned from a distance and through others' accounts; I can't even imagine how awesome it would have been like to take classes from him.

Bill Labov is the reason I became a sociolinguist. I remember learning about the fourth floor study in my intro to linguistics course and thought it was one of the most fascinating studies ever. Since then, I have read so much of his work and it has been the foundation of my own research. The first time I went to New York City, I didn't care to see the Statue of Liberty, One World Trade Center, Rockefeller Plaza, or Central Park. No, I did a pilgrimage to Saks, Macy's, and the building where S. Klein was located and got workers to say "fourth floor" there. I encourage you to read Labov's own account of [how he got into linguistics](https://www.ling.upenn.edu/~wlabov/HowIgot.html). Interestingly, he was a chemist for over a decade before beginning linguistics in his 30s, which just goes to show the value that late bloomers, non-traditional students, and people with unique backgrounds have on academia. He was a giant of a person and the best linguist of our generation. 

Anyway, I'll look forward to grading your final papers today. Thanks for a great semester. 

Joey