project:
  type: website
  output-dir: docs

website:
  title: "Joey Stanley"
  site-url: https://new.joeystanley.com
  navbar:
    title: '<span id="name">Joey Stanley</span><br/><span id="tagline">assistant professor, linguistics</span>'
    left:
      - text: "About Me <em>who am I?</em>"
        file: index.qmd
      - text: "CV <em>what have I done?</em>"
        file: cv.qmd
      - text: "Research <em>what am I working on?</em>"
        file: research/index.qmd
      - text: "Teaching <em>what do I teach?</em>"
        file: teaching.qmd
      - text: "Resources <em>what stuff do I use?</em>"
        file: resources.qmd
      - text: "Blog <em>what's going on?</em>"
        file: blog/index.qmd
    right:
      - icon: email
      - icon: twitter
        href: https://twitter.com/joey_stan
      - icon: clouds-fill
        href: https://bsky.app/profile/joeystan.bsky.social
      - icon: github
        href: https://github.com/JoeyStanley/joeystanley_new
      - icon: scholar
      - icon: rss

      
format:
  html:
    theme: cosmo
    css: styles.css

editor: source

resources:
  - CNAME

