project:
  type: website
  output-dir: docs

website:
  title: "Joey Stanley"
  site-url: https://new.joeystanley.com
  navbar:
    left:
      - text: "About Me"
        file: index.qmd
      - text: "CV"
        file: cv.qmd
      - text: "Research"
        file: research.qmd
      - text: "Teaching"
        file: teaching.qmd
      - text: "Resources"
        file: resources.qmd
      - text: "Blog"
        file: blog/index.qmd
    right:
      - icon: email
      - icon: twitter
        href: https://twitter.com/joey_stan
      - icon: clouds-fill
        href: https://bsky.app/profile/joeystan.bsky.social
      - icon: github
        href: https://github.com/JoeyStanley/joeystanley_new
      - icon: scholar
      - icon: rss
      
format:
  html:
    theme: cosmo
    css: styles.css

editor: source

resources:
  - CNAME

