project:
  type: website
  output-dir: docs

website:
  title: "joeystanley"
  navbar:
    left:
      - text: "About Me"
        file: index.qmd
      - text: "CV"
        file: cv.qmd
      - text: "Research"
        file: research.qmd
      - text: "Teaching"
        file: teaching.qmd
      - text: "Resources"
        file: resources.qmd
      - text: "News"
        file: news.qmd
    right:
      - icon: email
      - icon: twitter
        href: https://twitter.com
      - icon: github
        href: https://github.com/
      - icon: scholar
      - icon: rss
      
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

