project:
  type: website
  output-dir: docs

website:
  title: "Joey Stanley"
  site-url: https://joeystanley.com
  google-analytics: "350348361"
  navbar:
    title: '<span id="name">Joey Stanley</span><br/><span id="tagline">assistant professor, linguistics</span>'
    left:
      - text: "About Me <em>who am I?</em>"
        file: index.qmd
      - text: "CV <em>what have I done?</em>"
        file: cv/index.qmd
      - text: "Research <em>what do I research?</em>"
        file: research/index.qmd
      - text: "Teaching <em>what do I teach?</em>"
        file: teaching.qmd
      - text: "Idiolect <em>what do I sound like?</em>"
        file: /pages/idiolect
      - text: "Blog <em>what's going on?</em>"
        file: blog/index.qmd
#      - text: "Misc <em>what else is on here?</em>"
#        menu: 
#          - text: "Resources <em>what stuff do I use?</em>"
#            file: resources.qmd
#          - text: "Datasets <em>what can you use?</em>"
#            file: data
    right:
      - icon: envelope
        href: mailto:joey_stanley@byu.edu
      - icon: list
        menu: 
           # https://github.com/quarto-dev/quarto-cli/discussions/7640
         - text: "{{< fa brands bluesky >}} Bluesky"
           href: https://bsky.app/profile/joeystanley.com
         - icon: twitter
           text: Twitter
           href: https://twitter.com/joey_stan
         - icon: mortarboard-fill
           text: Google Scholar
           href: https://scholar.google.com/citations?user=61pJV_YAAAAJ&hl=en&oi=sra
         - icon: github
           text: Github
           href: https://github.com/JoeyStanley/joeystanley_new
         - icon: rss
           text: RSS feed
           href: joeystanley.com/feed.xml

      
format:
  html:
    theme: cosmo
    css: styles.css
    header-includes: <link rel="stylesheet" media="screen" href="https://font.download/font/iowanoldst-bt" type="text/css"/>

editor: source

resources:
  - CNAME

toc: true
