---
title: "What am I doing right now?"
date-modified: last-modified
---

<br/>

## Preparing to teach

* 🛠 Linguistics Tools ([LING 240](https://catalog.byu.edu/courses/12290-000)) 

* 🗣️ Sociolinguistics ([LING 452](https://catalog.byu.edu/courses/12546-000))

<!--
🗣 African American English (as [LING 495R Senior Capstone](https://catalog.byu.edu/courses/12295-001))

* 🗣️ Varieties of English ([ELING 468](https://catalog.byu.edu/courses/11256-002))

* 🎙️ Applied Phonetics ([ELING 327](https://catalog.byu.edu/courses/11232-001_)
-->

## Research

<!--* 👨🏻‍🏫 Preparing an abstract for NWAV54.-->

<!--* 💬 Collecting data on language attitudes towards regional varieties of English.-->

* 📖 Working on a textbook about American English varieties with Betsy Evans.

* 📃 Working on a paper about Utah English with a student.

* 📃 Working on a paper about Idaho English with Valerie Freeman and other collaborators.

<!--* 📊 Analyzing... -->

<!--* 📚 Reading... -->

<!--* 🤔 Thinking about what I'd like to get done in a potential sabbatical next year.-->

* 🇬🇧 Recruiting students for a study abroad in the UK next summer.

* 🛠 Developing some pretty awesome new tools for sociophonetic data analysis. [Here's one](/blog/VoxHumana) and stay tuned for the other.



## Advising

* ⛪️ An MA thesis on how religiosity correlates with language attitudes towards Spanish-accented English.

* ️🎤 An MA thesis on the acoustic correlates of "hero" and "villain" in voice actors. 

* 🗣️ An MA project that produces materials for Swahili speakers to learn English.

* ️🧑‍🧑‍🧒‍🧒 An MA thesis on address forms for in-laws and other non-core family members.

* 🎤 A [HumGrant](https://humgrants.byu.edu) on the social perception of affricate closure duration in Utah English.

* 👩🏼‍🤝‍👩🏻 A [HumGrant](https://humgrants.byu.edu) on the effect of pitch on the perceptions of female voices.



## Personal

* 🏡 Enjoying my new house!

<!--* 📊 Working on a few analyses for my [HymnStats blog](https://hymnstats.joeystanley.com).-->

* 📘 Listening to Brandon Sanderson's *Tress of the Emerald Sea*.

<!--* 🎶 Taking organ lessons. (This is my first time taking music lessons since 2011!)-->

* 🧶 Knitting a red scarf with a pretty cool Japanese cable pattern.

<!--* 👔 Learning to sew so I can finally have shirts that fit my long arms.-->

* 🧩 Toying around with 3x3, 5x5, and 7x7 Rubik's cubes.

* 📺 Watching *Silo* and *Ghosts*.


