---
layout: aside
title: Teaching
date-modified: last-modified
format:
  html:
    toc: true
---

### Current courses

* ELING 327: Applied Phonetics
* LING 452: Sociolinguistics
* LING 604: Research Design in Linguistics

### Past courses

*"Sounds" courses*

* ELING 327: English Phonetics and Phonology (×2)
* ELING 327: Applied Phonetics (×2, once with Lisa Johnson)
* LING 210:  The Sounds of Language (×2)
* LING 3060: Phonetics and Phonology (×2 at the University of Georgia)

*Sociolinguistics courses*

* ELING 468: Varieties of English (×5)
* LING 452:  Introduction to Sociolinguistics (×2)
* LING 495R: African American English (×3)
* LING 550:  Sociolinguistics (×4)
* LING 580R: Sociolinguistic Fieldwork (with Lisa Johnson)

*Methods courses*

* LING 240:  Linguistic Tools 1 (×4)
* LING 580R: Linguistic Data Analysis (with Earl Brown)
* LING 604:  Research Design in Linguistics (×4, once with Dan Dewey)

### Future courses

*Spring 2026*

* LING 495R: African American English


<br/>
The rest of this page serves as a repository for teaching materials and workshops I have prepared.

<br/>

## Courses

### [The Sounds of Language](https://catalog.byu.edu/courses/12288-000)

This is one of the core classes students take after taking intro to linguistics. It covers phonetics and phonology in an introductory way and serves as a prereq to the stand-alone phonetics and stand-alone phonology courses we offer. I've taught this in Winter 2024 and Winter 2025. [Here](/downloads/250429-L210_syllabus.pdf) is the most recent syllabus.

### [English Phonetics and Phonology](https://catalog.byu.edu/courses/11232-001)

I taught this Winter 2022 and Winter 2023. It's similar to the Phonetics and Phonology course I taught already, but it cuts out most non-English material and goes into more depth into English. [Here](/downloads/230103-E327_syllabus.pdf) is a syllabus. Because of curricular changes, this course was retired and replaced by Applied Phonetics. 

### [Applied Phonetics](https://catalog.byu.edu/courses/11232-001)

I taught this course in Winter 2024 (co-taught with Lisa Johnson) and Winter 2025 and am currently teaching it a third time in Winter 2026. This was a new course in the department that I developed in response to the some changes in the department. It was formally "English Phonetics and Phonology" but in response to the department changing the English Language major to Applied English Linguistics in 2022, I felt like it needed to change too. So, we first spend five weeks of basic phonetics and phonology concepts. Then for most of the rest of the semester, we spend about a week on each of several "applied" topics, showing how knowledge of phonetics can be helpful in a variety of ways. We look at L1 acquisition, aging, disorders and pathology, technology and speech recognition, forensic phonetics, SLA, regional and social accents, phonetics in the media, and applications in business. Since I don't know much about many of these topics, I try to get a guest lecturer to come in for many of them, which is pretty cool especially when they're outside the department (like a speech pathologist, an animation professor, and a dialect coach). [Here](/downloads/250429-E327_syllabus.pdf) is the most recent syllabus.

### [Introduction to Sociolinguistics](https://catalog.byu.edu/courses/12546-000)

I taught this undergraduate version of sociolinguistics in Winter 2021 (two sections) and Fall 2024, and am currently teaching it in Winter 2026. You can look through the syllabus [here](/downloads/250103-L452_syllabus.pdf). We used Allan Bell's *The Guidebook to Sociolinguistics*, though I jump around quite a bit. 

In Winter 2021, I was presented with an unusual teaching challenge with this course. I had two sections of this course on a Tuesday-Thursday schedule. The section that started at 12:30 was a larger section and, because we were in peak pandemic-mode still, half the students could be there in the person and the other half had to join via Zoom. (They were expected to alternate each day.) The 2:00 section was smaller, so they could attend in-person every day, but it was also cross-listed with the graduate version of the course (see below), which was expected to be more rigorous in some way. This setup made for a really tricky course to manage. The solution I came up with was, in my opinion, pretty cool. Instead of having my students attend lectures over Zoom, I prepared about 75-minutes of materials that they could explore on their own online (watching certain YouTube videos, exploring websites, watching a few brief supplementary prerecorded lectures of my own, taking a quiz, doing a homework assignment, and responding to a prompt on a dedicated Slack channel). That means I only needed to prepare and teach just a single lecture each week. I taught it in-person to half the 12:30 students on Tuesday and then again to the full cross-listed group at 2:00. I then taught the same lecture to the other half of the 12:30 students on Thursday. No one attended over Zoom. For the undergrads in the cross-listed version, they were excused on the Thursday lecture, leaving just the grad students. Together, we could read and discuss articles together. It was an interesting setup and I kind of enjoyed it. I will admit though, several years later, I'll still seeing the effects of having only prepared 15 75-minute lectures because now I need to prepare something like 40 50-minute lectures and I find that I'm constantly having to add or expand material from that first time though. 

In Fall 2024, I tried a new (to me) pedagogical technique by adding "Synthesis Days" to the course (see the prompt [here](/downloads/250103_L452_synthesis_prompt.pdf)). It was too much to write about here, so I have [a dedicated post](/blog/synthesis_days) about those. 

### [Sociolinguistics](https://catalog.byu.edu/courses/03565-002)

I taught this course Winter 2021, Fall 2021, Fall 2022, and Fall 2024 and am currently teaching it Winter 2026. This is the graduate-level version of the Introduction to Sociolinguistics course above. The course is usually cross-listed with the undergraduate version but in Fall 2021 and Fall 2022 I was able to do it as a stand-alone course. Regardless of how it's taught, tt's still introductory course and is similar to the undergraduate version. But when I teach it as a stand-alone course, we take one day a week to read and discuss articles. [Here](/downloads/220103-L550_syllabus.pdf) is my most recent syllabus for the stand-alone version. 

### [Special Topics: African American English](https://catalog.byu.edu/courses/01990-003)

I taught this course Spring of 2023, 2024, and 2025 under the auspices of the senior capstone course, as well as as a linguistics elective, in the linguistics department. (So, technically it was cross-listed as LING 495R: Senior Capstone, ELING 495R: The Senior Course, LING 421R: Studies in Linguistics, and ELING 421R: Studies in Language or Editing). 

The capstone courses in my department are designed to be open-ended and end up being special topics courses that cover a wide range of subfields in linguistics. Most of the faculty who had been teaching these capstone courses though had recently retired, so we have been in dire need for new courses to put into the rotation. I had wanted to teaching something about language ideology, discrimination, and/or attitudes but I was asked to do something to do with American English; we settled on African American English, which I think was a nice compromise. 

So, with the help and input from many friends and colleagues, I designed and prepped the course, using Lisa Green's *[African American English](https://doi.org/10.1017/CBO9780511800306)* as my main textbook. I went into the course knowing some things here and there about AAE from just being exposed to the literature on it in sociolinguistics, and it turned out to be very challenging but a richly rewarding course for me. [Here](/downloads/240501-L495R_AAE_syllabus.pdf) is the syllabus.

### [Special Topics: Sociolinguistic Fieldwork](https://catalog.byu.edu/courses/01990-003)

This is a special topics course that I taught with Lisa Johnson in Winter 2023. We used Natalie Schilling's textbook of the same name as our guide and did a Utah County--based implementation of similar courses taught in other universities. (Our "fieldsite" that we chose was Lehi, Utah.) The course involved going out to the field to conduct sociolinguistic interviews. You can see a syllabus [here](/downloads/230105-L580_socio_fieldwork.pdf). 

### [Introduction to Varieties of English](https://catalog.byu.edu/courses/11256-002)

I've taught this course five times (Summer 2020, Fall 2020, Fall 2021, Fall 2022, and Fall 2025). In Summer 2020, it was completely online and focused on the British Isles to make up for the study abroad to the UK and Ireland that was canceled due to covid. In Fall 2020, Fall 2021, and Fall 2022 we covered around 30 varieties of English in three broad units: North America, the British Isles, and everywhere else. [Here](/downloads/260102_E468_F25_syllabus.pdf) is my most recent syllabus. 

I tried two new types of assignments in Fall 2025 that I'll share here. First, in the past I've had them take a recording of a variety of English and explain it in two ways: once to a dialectology expert and once to a layperson. They usually did alright on the first, but usually not so good to the layperson. It didn't feel like a very realistic exercise though, writing a carefully edited description to a layperson. What is having to explain something orally. So, instead I prepared one half of a podcast episode where I had an AI voice ask questions about the variety or things about it broadly, and they had to record themselves supplying the other half. That was pretty cool. The other thing I tried in 2025 was I completely altered the final project. Before, I had them do a research paper about "anything having to do with any variety of English". But that was too broad and not really fitting of the course. So, this time, they had to produce a podcast episode about a variety of English. So, they had to find recordings, introduce them, talk about what dialect features the people have, and use those as examples to explain the broader linguistic phenomena going on in the variety. It turned out pretty well I think! There are some bugs to fix, but I'll try it again next time I teach the course.  

### [Linguistics Tools 1](https://catalog.byu.edu/courses/12290-000)

I taught this course in Fall 2020, Fall 2021, Fall 2024, and Fall 2025 and am currently teaching it Winter 2026. I am also the coordinator for this course. We cover how to do linguistics research from start to finish. So includes data collection and data analysis, but also general research skills like literature reviews and how to write and present research. We include some software-specific training like Zotero, Antconc, and Praat, but also general skills like survey design, experimental design, and qualitative data analysis. We also cover basic statistics (correlation, *t*-tests, ANOVA, and chi-square tests). It's an overloaded course and could easily be split into at least three different courses, so it's tricky trying to balance depth and breadth. [Here](/downloads/260102_L240_F25_syllabus.pdf) is my most recent syllabus. 

Something I'll mention here that I thought was pretty cool was that I was concerned that this course was too modular, so when I taught it in Fall 2024, I tried to integrate things more. One change I made is that relatively early in the semester I had them create a survey with specific question types. They then analyzed the data from that survey in subsequent homework assignments, like running an ANOVA on quantitative data they gathered or doing content analysis on the open-ended questions. It was good for them to see real data, and it was much more interesting to them to analyze their own data rather than ones I might provide them.

### [Special Topics: Linguistic Data Analysis](https://catalog.byu.edu/courses/01990-003)

This is a special topics course that I taught with Earl Brown in Fall 2022. We built upon the version of the course he taught in Winter 2020. [Here](/downloads/220801_L580_data_analysis.pdf) is the syllabus we started off with (though it did change quite a bit in the end).

### [Research Design in Linguistics](https://gradstudies.byu.edu/ling-604-research-design)

I've taught this course Winter 2021 (with Dan Dewey), Winter 2022, Winter 2024, and Winter 2025. It is called "Research Design" and we do cover some basic research methods, but the main purpose of the course is that students need to end the semester with a prospectus for their MA thesis. As seen in the [syllabus](/downloads/250429-L604_syllabus.pdf), there are weekly milestones they need to hit, like coming up with a thesis topic, finding a committee, doing a lit review, and finally putting together a prospectus. 

This is quite a fun class for me. For one, it's required of all first-year Linguistics MA students, so I get to meet all them. But also, I get the rewarding experience of seeing students go from a vague research idea at the beginning of the semester to a full prospectus by the end. Of course, that takes quite a bit of work for me to give lots of one-on-one feedback throughout the semester, but I enjoy it. The irony is that I never did a Master's and here I am coaching people on how to do theirs!

Historically, the professor for this course gets a disproportionate number of students asking them to be on their committees. So, this course was passed around from one faculty member to another to ease that burden a little bit. This hasn't been a problem for me, and I enjoy the course, so I've taught it to four of the past five cohorts. It puts a lot of responsibility on my shoulders to shepherd students into their theses and to transition them from just taking courses to working on a thesis. But I don't think we've seen a drop in the quality of our MA theses, so I'll continue to teach it as long as they'll let me. 

### [Phonetics and Phonology](http://bulletin.uga.edu/Link.aspx?cid=ling3060)

I taught this course Fall 2017 and Spring 2019 at UGA. I teach a very similar course at BYU with a different title ("Sounds of Language"). [Here](/downloads/190308_LING3060_syllabus.pdf) is a syllabus from UGA.

**[Praat Tutorial](/downloads/190523-Praat_tutorial.pdf)**---For homework, I often assign students mini-projects that involve the use of Praat. This assignment serves as a useful tutorial to downloading and running Praat for the first time. In it, I give detailed instructions on how to make and transcribe a sentence.

**[Features Chart](/downloads/180814-features_chart.pdf)**---When I was preparing to teach features for the first time, I found it hard to keep track of all of them so I started making a chart. It turned out to be pretty useful and I thought my students might like it too. It's meant to act as reference rather than instruction, so you'll still have to read through the relevant chapters to understand everything. It's a lot of information to cram into a single page, so it's still a work in progress to make it look better. It's sort of one of those things that makes sense to the person who made it and no one else, so you're milage may vary. I should have an accompanying "How to use this chart" guide. Maybe next time. 



<br/>
<br/>
<br/>




## Workshops

### [LaTeX Workshops](/pages/latex.qmd)

Caleb Crumley, Jonathan Crum, and I led a series of three workshops on LaTeX as a way to introduce the new UGA Dissertation LaTeX template. I discussed basic LaTeX skills, Caleb showed how to use the template, and Jonathan illustrated more advanced topics. This series got the stamp of approval from the UGA Graduate School and had over 100 registered attendees.

### [Praat Scripting Workshops](/pages/praat-workshops.qmd)

Lisa Lipani and I led three workshops on Praat and Praat scripting. We discussed the basics of the Praat interface, how to code basic things, and then did one devoted to automatic extraction of formant measurements. 

### [Data Visualization Workshops](/pages/dataviz.qmd)

In a suite of five workshops, I discussed data visualization. Three of them were focused on ggplot2 (see the R workshops) but two were platform-independent and discussed the use of color and Edward Tufte's principles of data visualization. Though they're outside my discipline, I really enjoyed these workshops.

### [R Workshops](/pages/r-workshops.qmd)

I have led more than a dozen workshops on R on a variety of topics. In addition to just an intro to R, I've talked about the tidyverse, RMarkdown, and Shiny. I've done a handful just on ggplot2, and I have handouts ready for more detailed workshops on customizing plots in ggplot2 for future workshops. 

### [Professionalization ("Brand Yourself") Workshops](/blog/brand-yourself-3)

In this workshops, I discuss ways to boost your online presence as an academic. I've given this workshop several times over the past few years and it has evolved quite a bit based on my own experiences. The gist: make a website and possibly also get active on Twitter.

### [Academic Poster Workshop](/downloads/190911-poster_workshop.pdf)

I gave a brief---and very opinionated---workshop on how to make an academic poster. I discuss overall design and layout, nit-picky things like font sizes and color, and content. 

### [Excel Workshop](/blog/excel-workshop)

I once gave a workshop on Excel. It was a while ago.
