---
layout: post
title: "My cot-caught distribution"
date: 2023-05-23 14:00:00 -0600
categories:
  - Dissertation
  - Lexical Sets
  - Personal
---

In appendix C of my [dissertation](/blog/dissertation), I listed 838 words that contain low vowels, classified as /ɑ/ or /ɔ/ according to my idiolect. I think it may be a useful resource for those who have the *cot-caught* merger, so I thought I'd pull it out and make it more available. 

The words that are included here are all those that came up in the course of the 54 sociolinguistic interviews I did in Washington State as part of my dissertation work. This means that there are some quirky ones included like *Sinterklaas* and *Jawas*. By nature of the naturalistic data, certain common words may be missing.

Please note that, again, this reflects *my* idiolect, and may not be reflective of others' speech, other varieties of English, or historical distributions. For more information about the phonetic realization my two vowels and some phonological peculiarities, please see my description of my [idiolect](/pages/idiolect.qmd). 

If you find this page useful, please cite it as Appendix C of my dissertation: 

> Stanley, Joseph A. (2020). *Vowel Dynamics of the Elsewhere Shift: A Sociophonetic Analysis of English in Cowlitz County, Washington*. Ph.D. Dissertation, University of Georgia, Athens, GA.


## <sc>lot</sc>, *cot*, /ɑ/, <sc>bot</sc>, etc.

The following 550ish words are all those that were classified as part of the <sc>lot</sc> lexical set, which includes many words in the <sc>palm</sc> set (though not *palm* itself because of that pesky /l/!). Personal names and other identifying words have been removed.

*accelerometer*, *accommodate*, *accommodation*, *accomplish*, *accomplished*, *adopt*, *adopted*, *adopting*, *agronomous*, *ah*, *aloha*, *Aotearoa*, *apostrophe*, *approximately*, *aquatic*, *assada*, *astronomical*, *atomic*, *atrocities*,

*battery-operated*, *biography*, *biological*, *blah*, *blobs*, *block*, *blockage*, *blocked*, *blocking*, *blocks*, *blossomed*, *body*, *bomb*, *bomber*, *bombing*, *bombings*, *bombs*, *bombshell*, *bon*, *bond*, *bonfire*, *bonfires*, *Bonnie*, *Bonnie’s*, *bother*, *bothered*, *bothering*, *bothers*, *bottle*, *bottles*, *bottom*, *bottoms*, *box*, *boxes*, *boxing*, 

*Chicago*, *chocks*, *chop*, *chopped*, *chopping*, *chops*, *chronically*, *cilantro*, *clock*, *clock’s*, *clocked*, *clocks*, *closet*, *closeted*, *cocker*, *cockney*, *cocktails*, *cod*, *cog*, *cogs*, *cognitive*, *colonoscopy*, *com*, *combat*, *combination*, *combos*, *comedies*, *comedy*, *comical*, *comment*, *comments*, *commerce*, *commodity*, *common*, *commonly*, *comp*, *compact*, *compensate*, *compensating*, *competent*, *competition*, *competitions*, *complement*, *complex*, *complicate*, *complicated*, *complications*, *compound*, *comstock*, *con*, *concentrate*, *concentrating*, *concept*, *concepts*, *concert*, *concerts*, *concrete*, *condo*, *conduct*, *conference*, *conferences*, *confidence*, *confident*, *confirmation*, *conflict*, *conglomerate*, *congregates*, *congress*, *Conner*, *Connie*, *conquer*, *cons*, *conscience*, *conscious*, *consequence*, *consequences*, *constable*, *constant*, *constantly*, *constitution*, *contact*, *contacted*, *content*, *contest*, *contests*, *continental*, *contraband*, *contract*, *contracted*, *contractor*, *contractors*, *contracts*, *contrast*, *controversy*, *conversation*, *converse*, *convert*, *cooperating*, *cop*, *copper*, *cops*, *copy*, *copying*, *Cossack*, *costume*, *cot*, *cots*, *counter-clockwise*, *Cozumel*, *crop*, *crops*,

*deposit*, *dichotomy*, *dock*, *doctor*, *doctor’s*, *doctorate*, *doctors*, *doctrine*, *documented*, *documents*, *dodge*, *dodgeball*, *dodged*, *Don*, *Donald*, *dot*, *drama*, *drop*, *drop-out*, *dropoff*, *dropouts*, *dropped*, *dropping*, *drops*,

*ebonics*, *economic*, *economics*, *economy*, *electronic*, *electronics*, *ensemble*, *esophagus*, *Exxon*,

*father*, *father-in-law*, *father-in-law’s*, *father’s*, *fiance*, *fiance’s*, *Firefox*, *flock*, *flocks*, *flops*, *fondest*, *fondue*, *forgot*, *forgotten*, *fox*,

*galoshes*, *garage*, *garages*, *geography*, *geometry*, *god*, *god’s*, *goddess*, *godfather*, *godparents*, *gosh*, *gospel*, *gossip*, *got*, *gotcha*, *gotta*, *gotten*, *grandfather*, *grandma*, *grandma’s*, *grandpa*, *grandpa’s*, *great-grandfather’s*, *Guam*,

*ha*, *hobbies*, *hobby*, *hockey*, *homogenized*, *Honda*, *honest*, *honestly*, *honesty*, *honor*, *honorable*, *hopped*, *hopper*, *hops*, *hospice*, *hospital*, *hospitals*, *hostage*, *hot*, *hotter*, *hottest*, *hypothesis*,

*impossible*, *impoverished*, *improper*, *Iran*, *ironic*, *ironically*,

*Java*, *Jawa*, *Jawas*, *job*, *job-wise*, *jobs*, *jock*, *jockey*, *jockeying*, *jockeys*, *jocks*, *Joplin*,

*Kawasaki*, *knob*, *knock*, *knocked*, *knocking*, *knocks*,

*la*, *Lafayette*, *lava*, *Lhasa*, *llama*, *llamas*, *lobby*, *lobster*, *lock*, *locked*, *locking*, *locks*, *lodge*, *logic*, *lot*, *lots*, *lotta*, *lotteries*,

*ma*, *Mazama*, *Mazamas*, *McDonald*, *McDonald’s*, *McDonalds*, *microprocessor*, *microprocessors*, *mill-dominated*, *mock*, *model*, *modeling*, *models*, *moderate*, *modern*, *modest*, *modify*, *modular*, *mom*, *mom’s*, *moms*, *monetary*, *Monica*, *monocle*, *monopoly*, *monotone*, *monster’s*, *Monterrey*, *Montgomery*, *Montiville*, *monument*, *mop*, *Morocco*, *motto*,

*nah*, *Nazi*, *Nazis*, *neon*, *nodding*, *non-athletes*, *non-profit*, *non-profits*, *non-stop*, *novel*, *novelist*,

*o’clock*, *obligated*, *obsolete*, *obstacles*, *obvious*, *obviously*, *occupies*, *October*, *odd*, *odd-shaped*, *oddly*, *odds*, *Ohana*, *omelette*, *omelettes*, *op*, *opera*, *operate*, *operating*, *operation*, *operations*, *operator*, *operators*, *opportunities*, *opportunity*, *opposite*, *option*, *optional*, *options*, *orthodontist*, *ostracized*, *Ostrander*, *ostriches*, *otters*, *oxy*, *oxy-fuel*, *oxygen*,

*pa*, *pasta*, *pecan*, *pecans*, *periodontist*, *phenomenal*, *philanthropic*, *philosophies*, *philosophy*, *phonologically*, *phosphorus*, *photographer*, *photography*, *Photoshop*, *plopped*, *Pocahontas*, *pocket*, *pockets*, *pod*, *podcast*, *pond*, *ponds*, *Pontiac*, *pop*, *popped*, *pops*, *popular*, *population*, *posh*, *positing*, *positive*, *possible*, *possibly*, *pot*, *potholes*, *potluck*, *potlucks*, *Potter*, *potty*, *pottying*, *poverty*, *predominantly*, *probably*, *problem*, *problem-solvers*, *problems*, *process*, *processed*, *processes*, *processing*, *proclamation*, *product*, *products*, *progress*, *project*, *projects*, *prom*, *prominent*, *prop*, *proper*, *properly*, *properties*, *property*, *props*, *prosecuted*, *proselyte*, *prospects*, *prostate*, *psychologically*,

*quads*,

*recognizance*, *reconnaissance*, *regatta*, *remodel*, *remodeled*, *remodeling*, *remodels*, *repository*, *reprocess*, *respond*, *responded*, *response*, *responses*, *responsible*, *robin*, *robin’s*, *rock*, *rock’s*, *Rockefeller*, *rocker*, *rockers*, *rocket*, *rockets*, *rocking*, *rocks*, *rocky*, *rod*, *rods*, *rotted*, *rotten*,

*Saigon*, *Scotland*, *self-conscious*, *shock*, *shocked*, *shop*, *shopped*, *shopping*, *shops*, *shot*, *shotguns*, *shots*, *Sinterklaas*, *ska’s*, *sloppy*, *snobbies*, *snobby*, *snot*, *sobbed*, *soccer*, *soccer’s*, *sock*, *socket*, *socks*, *sponsor*, *sponsoring*, *spot*, *spots*, *spotted*, *spotter*, *spotters*, *squash*, *squat*, *squatter*, *squatters*, *stock*, *stocking*, *stockings*, *stomping*, *stop*, *stopped*, *stopping*, *stops*,

*taco*, *telethon*, *teriyaki*, *throttle*, *toddler*, *top*, *topic*, *topics*, *topless*, *Toppenish*, *toppled*, *tops*, *trigonometry*, *tropical*, *trot*, *Tsugawa’s*, *tsunami*,

*Uganda*, *unblock*, *uncommon*, *Vietnam*,

*whatnot*, *Wisconsin*,

*Yamaha*,

*zombie*


## <sc>thought</sc>, *caught*, /ɔ/, <sc>bought</sc>, etc.

Meanwhile, the following 280ish words are all those that were classified as part of the <sc>thought</sc> lexical set, which includes most (or probably all) words in the <sc>cloth</sc> set. Again, personal names and other identifying words have been removed.

*across*, *along*, *alongside*, *applesauce*, *Auburn*, *auction*, *auctions*, *audio*, *audio’s*, *audits*, *aught*, *August*, *Austin*, *Austria*, *Austrian*, *author’s*, *authorized*, *autism*, *auto*, *auto-related*, *autobiography*, *automatic*, *automatically*, *automobiles*, *autopsy*, *awe*, *awesome*, *awful*, *awkward*, *awkwardness*,

*belong*, *belonged*, *belongings*, *beyond*, *blog*, *blogger*, *bloggers*, *blogging*, *blogs*, *blond*, *bonko*, *bonkos*, *boss*, *bosses*, *Boston*, *bought*, *bra*, *bras*, *broad*, *broadcast*, *broadcasting*, *broadway*, *brothels*, *brought*,

*c’mon*, *calm*, *caught*, *cause*, *caused*, *causes*, *causing*, *cautious*, *chainsaw*, *chalked*, *chocolate*, *chocolates*, *clause*, *clog*, *clogged*, *clogging*, *cloth*, *coffee*, *Cong*, *cost*, *Costco*, *costs*, *cross*, *cross-wired*, *crossed*, *crosses*, *crossing*, *crosswise*, *crossword*, *cutoff*,

*daughter*, *daughter-in-law*, *daughter-in-laws*, *daughter’s*, *daughters*, *daughters-in-law*, *dawn*, *dawned*, *dishwater*, *dog*, *dog’s*, *doggie*, *dogging*, *doggone*, *dogs*, *dong*, *donkeys*, *draw*, *drawed*, *drawing*, *drawn*, *draws*,

*elongated*, *exhaust*,

*fog*, *fought*, *frogs*, *froth*,

*gloss*, *gone*, *goner*, *gong*, *goth*, *goths*, *granddaughter*, *granddaughters*,

*haunted*, *haunts*, *hawed*, *hawk*, *hog*, *Hogwarts*,

*jaw*, *jigsaw*, *jog*, *jogged*, *jogging*, *Johnston*, *Johnston’s*,

*Las Vegas*, *laundry*, *law*, *lawn*, *lawnmower*, *lawns*, *laws*, *lifelong*, *log*, *logged*, *logger*, *loggers*, *logging*, *logjammed*, *logs*, *long*, *Long-Bell*, *Long-Bell’s*, *long-span*, *long-standing*, *long-term*, *longer*, *longest*, *longjohns*, *longshore*, *longshoreman*, *longshoreman’s*, *Longview*, *Longview-ite*, *Longview’s*, *loss*, *losses*, *lost*,

*mama*, *Montana*, *moss*, *mossy*, *naughty*,

*off-duty*, *offer*, *offered*, *offerings*, *offers*, *offhand*, *office*, *officer*, *officers*, *offices*, *often*, *Ogden*, *online*, *on*, *onset*, *onto*,

*palm*, *pause*, *paused*, *pausing*, *paw*, *pawn*, *paws*, *pong*, *profit*, *profitable*, *prolonging*, *promise*, *promised*, *promising*, *prompt*, *prophecy*, *prophet*,

*quantities*,

*raw*, *restaurant*, *restaurants*,

*sauce*, *saucers*, *sauces*, *sausage*, *Sauvie*, *saw*, *sawing*, *sawmill*, *saws*, *Schwann’s*, *scoff*, *slaughtering*, *sloshes*, *soft*, *softball*, *software*, *somber*, *sombering*, *song*, *songs*, *sophomore*, *spawning*, *squaw*, *stalker*, *stalking*, *straw*, *strawberries*, *strawberry*, *strong*, *stronger*, *strongest*, *swans*, *swath*,

*talk*, *talkative*, *talked*, *talker*, *talkie*, *talking*, *talks*, *taught*, *thaw*, *thought*, *thoughts*, *tomboy*, *Tonga*, *tossed*, *traumatized*,

*underwater*, *upon*, *Utah*,

*vaudeville*,

*waffle*, *waffles*, *walk*, *walked*, *walking*, *walks*, *walkway*, *wand*, *wandering*, *wash*, *washboardy*, *Washburn*, *washed*, *washer*, *Washington*, *watch*, *watched*, *watches*, *watching*, *water*, *watering*, *waters*, *wrong*