---
layout: post
title: "SoSy"
date: 2023-03-02 08:00:00 -0600
categories:
  - Conferences
  - Presentations
  - Research
  - Students
---

Today, I'm in Champaign, Illinois at the 5th Sociolinguistics Symposium (SoSy) at the University of Illinois Urbana-Champaign. I'm with a student of mine, Katya Kravchenko, and we're here presenting her research project, "Surzhyk: Attitudes and Usage among Ukrainian People." You can view the slides [here](/downloads/230302-SoSy_Surzhyk.pdf).

Throughout my sociolinguistics course last semester, Katya regularly kept us updated on fascinating things going on with language attitudes and ideologies among Ukrainians since the Russian invasion of Ukraine in February 2022. I think pretty much every Ukrainian speaks Russian, but not all speak Ukrainian. Even President Zelenskyy isn't a native Ukrainian speaker and reportedly hired a tutor to help him achieve full command of the language. 

Attitudes towards Russian have changed dramatically in the past year though. Before, TV shows would put Ukrainians subtitles if someone speaks Russian. Now, they remove the Russian audio entirely and dub it over with Ukrainian. (This what happened on the Ukrainian version of the show, "The Bachelor".) Sometimes, there's a disclaimer at the start of the show saying apologetically that it was filmed before February 2022 and that they apologize for the Russian. There's a grassroots effort (I wish I had the website, but I can't find it now) to replace Russian borrowings into Ukrainian with pure Ukrainian words. This is done either by coining neologisms, or by going back to and older form of Ukrainian and finding words that, for whatever reason, didn't make their way into modern Ukrainian. Basically, many Ukrainians are vowing to never speak Russian again. 

For native bilinguals, it's not too much of a problem. However, for those who aren't fluent in Ukrainian this can be a tricky thing! 

In comes Surzhyk. Surzhyk is a mix of Ukrainian and Russian, akin to Spanglish. There's not a lot of linguistic research on it, but it's rather stigmatized. In the past year though, Katya is finding that people's view of Surzhyk is becoming more positive. She interviewed 15 Ukrainians who were living in Ukraine in February 2022 and since fled to Utah. One part of the interview asked them about their usage patterns. Like any Fergesonian Low language, it's seen as too casual for formal settings. But, when it comes to attitudes, it's seen as a bridge to help Russian speakers learn Ukrainian. Speaking Surzhyk instead of Russian signals a *lot* about someone's position in the war. A year and a month ago, speaking one language---whether it be Ukrainian or Russian---was better than mixing the two. Today, speaking Surzhyk is seen as better than full Russian. 

This is 99% Katya's research, but it has been fun to hop on board and work with her on this. It's not about vowels, statistics, or American English, and I don't speak a word of Russian, Ukrainian, or Surzhyk. But it has been a fun stretch for me. 

