---
layout: post
title: NWAV51
date: 2023-10-13 21:30:00 -0600
categories:
  - Conferences
  - Presentations
  - Research
aliases:
  - "/nwav51"
---


This weekend, some students that I advise in different capacities presented their research at NWAV51 in New York! I am co-author on them, but it's about 95% their work. For reasons I won't get into here, I was not able to attend the conference myself, so these three students presented by themselves!

## Thursday's Presentation on Ukrainian Language Ideolgies

:::callout-tip
Download the slides [here](/downloads/231013-NWAV_Ukraine.pdf)!
:::

Kateryna Kravchenko presented her research, "An analysis of Ukrainians’ language attitudes and ideology: A conflict-catalyzed identity shift." Katya has been tracking Ukrainian language ideologies since the Russian invasion of Ukraine in February 2022 and has noticed that many Ukrainians are vowing to never use Russian again, even though it is their first language. It appears to start with social media and then move to other domains after that. She has conducted interviews with Ukrainians who have had to flee the country since February 2022 and has some really fascinating first-hand insights into what we're calling a "conflict-catalyzed identity shift." 

## Friday's Presentation on "Southern" Utah English

:::callout-tip
Download the slides [here](/downloads/231014-NWAV_SouthernUtah.pdf)!
:::

Chad Huckvale has been working on perceptual dialectology research in Utah, and has been focused on this idea that people describe parts of Utah as sounding "Southern," even though Utah English and Southern American English have little in common. In his presentation, "Perceptions of 'Southern' Utah English," he presents results from two experiments on this topic. First, he did a class draw-a-map task and found that, unsurprisingly, people labeled the urban area along the Wasatch Front as "urban" (and related words) and everywhere else as "rural" (and related words). In his second experiment, people listened to speech samples and were asked where in Utah they thougt they were from. (The twist is that only a few of the speakers were actually from Utah!) People placed speakers with features of Southern American English in the rural parts of the state. There's a lot more in Chad's MA thesis, but this was 

## Friday's presentation on tourism and its effect on language

:::callout-tip
Download the slides [here](/downloads/231014-NWAV_Tourism.pdf)!
:::

Finally, Zoe Elredge just graduated with her BA, but she's been working hard on perceptions of Park City English. In her presentation, "Exploring the Effects of Cross-Cultural Variation and Tourism in Utah English," she presents just some of the results of a very rich data collection she has gathered. The results are messy, but it seems like Parkite English is perceived as less professional and less laidback. That seems contradictory, but it kinda fits the stereotype of being a "Mountain Surfer Dudes" as one participant put it: superficial and posh. With Park City being a ritsy, touristy area, perhaps people are less willing to invest in friendships. Again, the results are messy, and Zoe is still digging to see what it can say and I look forward to see what she finds. 