---
layout: post
title: Synthesis Days
date: 01/09/2024
categories: 
 - Teaching
---

I don't often post just about teaching, but I thought I'd report on something I tried this past semester. I had some issues with how I taught sociolinguistics in the past, so I came up with "synthesis days" to solve some of them. I think it worked and it might be useful for you too.

## Issues with past iterations of the course

While prepping to teach sociolinguistics again, I thought back on things I didn't like about how I've taught it in the past. For one, it was one of my first courses I taught, so the slides were a bit amateurish, so they just needed to be spruced up a little bit. (I guess that says something about how I've grown as a teacher or whatever.) 

But one main issue was that my version of the course was a holdover from covid-era teaching. The first time I taught it, it was a single 75-minute lecture taught twice a week. One section came in on Tuesday and the other came in Thursday. On students' off-days, they did some online content I prepared for them. It worked for that early 2021 semester. I later taught it as a stand-alone graduate level course (as opposed to a cross-listed one) where I split that 75-minute lecture into two 50-minute lectures and then we discussed articles on Fridays. But now that I was teaching it as a regular Monday-Wednesday-Friday 50-minute course, I needed to make some changes beyond just continuing the stretch out what was once just a single lecture.

Meanwhile, I had some issues with how assessment happened. I had weekly open-book quizzes, weekly mini-projects for homework assignments, a midterm and final, and a final project. It was a lot, and I just didn't feel like those quizzes and tests were good assessment tools. 

Finally, one big issue I had was that the course was too modular. The topics didn't build upon each other as much as I'd like and each week was more or less independent of the other. This means that a student could miss two weeks of class and then jump right in without feeling behind, and I don't think that should be the case.

So, I went for a long walk and had a conversation with ChatGPT to help brainstorm some ideas. While many of its ideas were no good, it did spark an idea of my own. I decided to try adding "Synthesis Days" to the course.

## The synthesis days

The course was already broken up into four broad units: situated language, language variation, language attitudes, and the life cycle of language. You can see the syllabus [here](/downloads/250103-L452_syllabus.pdf). So, at the end of each unit, I dedicated an entire lecture to synthesizing what we had just discussed for the past 2--3 weeks. Theses synthesis days consisted of three main components: a paper, a presentation, and a discussion.

### The synthesis paper

Each student had to write a synthesis paper for the unit. I emphasized that this was a *synthesis*, not a summary, so if they just wrote a paper that regurgitates the various topics from that unit one paragraph at a time, they would not get a good grade. You can read the prompt [here](/downloads/250103_L452_synthesis_prompt.pdf), but I emphasized that I wanted them to draw connections between topics in the unit and to see how they relate to each other. I encouraged them to incorporate examples from class as well as add their own. They needed to cover every lecture topic from that unit without dwelling too much on any one too much, which means if they were gone at any point during the unit, they'd have to play catch-up. I didn't give them a page/word limit, but I said I'd be hard to do a good job in less than 500 words. I graded them holistically out of ten. 

Unlike other assignments, these synthesis papers were due when class started on the synthesis days. I wanted to see how students did without getting ideas from others in the presentation or discussion. 

I will say that students expressed how difficult it was to do these papers. Sure enough, the first unit's synthesis papers averaged an 8.3. They often lost points for not incorporating all the topics, not having a clear narrative throughout, being too much of a summary, and not discussing the bigger picture. But, I gave detailed feedback, and the average scores went up to 9.1, then a 9.7, and then a 10.0 (yes, they all did excellent the last time!). So, it was really cool to see them grow and finally learn how to write these. However, they took a long time to grade, and these were on top of regular weekly assignments, so that was tricky for me to stay caught up.

I think being able to do a synthesis like this is a good skill for other areas of writing. In fact, when I graded their final papers, I found myself giving the same kind of feedback in their lit reviews as I did on the synthesis papers (don't dwell on one paper too much, no narrative, avoid the one-citation-per-paragraph summary, discuss the bigger picture). Next time I teach the course, I'll have to explicitly make the connection for them that the skills needed in these syntheses should be applied to lit reviews. 

Overall, I liked the synthesis papers and I plan on doing them again next year. I'll just need to make sure I can grade them on time!

### The synthesis presentation

So what do we do on the synthesis day? Instead of me giving a lecture, I thought it'd be good to see students present. So, this year I had 20 students and four units, so I randomly assigned them into groups of five and randomly assigned each group to each unit. Groups were then asked each one to prepare a 20-minute synthesis lecture for their assigned unit. So on each synthesis day, we saw one group presentation. Those who presented for that unit were exempt from turning in a paper. The presentations should have been similar in style to the papers: a synthesis rather than a summary, covering all topics equally, and incorporating new and old examples. 

The presentations were mostly okay, but I realized this is a difficult thing to do well as a group. What I mostly saw was five students each giving good stand-alone presentations back-to-back. They were less unified in their delivery than I was hoping and there was usually not much of a larger narrative or arc that permeated through the entire thing. 

This was my first time ever doing group work and I'm not sure if I'll keep it for next time. They were hard for the students, difficult to grade, and I'm not sure what pedagogical purpose they served. 

### The synthesis discussion

For the remainder of the 50-minute lecture, we broke out into small groups and discussed the unit. I asked presenters to end their lecture with a handful of questions to stimulate some discussion topics. I then distributed the five presenters among the rest of the class so they could kind of lead the discussions. I jumped from group to group, contributing ideas here and there and just listening to what they were saying. 

I was pleasantly surprised at how well these discussions went. Pretty much everyone stayed on-track as far as I could tell. People had good ideas and it was good to see them come out in those discussions. Everyone had the synthesis fresh on their minds because they all either gave a presentation or turned in a paper, so everyone was prepared. But it was good to see people telling personal stories and how the topics from the unit give them a different perspective on what happened. I heard a few students say they enjoyed this as an end-cap to the unit as well. 

I'll definitely try to do discussions again next year. My one issue is that because they were not graded, I noticed attendance was lower on the synthesis days. I'll have to find a way to encourage students to be there. 

## Conclusion

I liked these synthesis days and will probably do them again next time I teach the course. I'll have to tweak a few things, but overall I thought it was really good. 

I will say that one major thing about adding four synthesis lectures is that I had to account for four non-contentful lecture days. I also took the last two weeks of the course (so, the five days after Thanksgiving) and made those final presentation days. So in total, there were nine non-lecture days. Keep in mind that my first iteration of the course had just fifteen 75-minute lectures, so it's not like there were nine lectures that were just cut out entirely. But it did mean I had to be careful about covering everything I wanted in only about 35 lecture days. But, I thought keeping the units tight and more integrated was good for me as a teacher and for the students.

So, overall, I think these synthesis days solved many of my issues: the course was far less modular, there were more useful assessments than quizzes and exams, and the lectures were better organized and updated with fresh content. 