---
layout: post
title: "For the Benefit of the World 2025"
date: 2025-10-29 09:00:00 -0600
date-modified: last-modified
reference-location: margin
format:
  html:
    toc: true
categories:
  - Conference
  - CALD
number-sections: true
aliases: 
  - "/benefit"
#resources: 
#image: 
---

Recently, several of us in the linguistics department at BYU started a group called the **Coalition Against Linguistic Discrimination** (CALD). It has been on my mind for a while now that I want to make a difference in the world when it comes to linguistic discrimination, accentism, and linguistic prejudice. We are now a group of faculty and students trying to find ways to raise awareness across campus and do research on this topic. 

One of our first products is a poster presentation at BYU's [For the Benefit of the World](https://forthebenefitoftheworld.byu.edu) conference. This conference is an "effort to explore the state of BYU research and creative works associated with caring for those in need, including work that addresses existing human needs or their root causes and scholarship related to humanitarian efforts of The Church of Jesus Christ of Latter-day Saints." From the looks of it, they probably expected abstracts related to medicine, water sanitation, or other clearly humanitarian-based projects. They probably didn't expect a linguistics-based presentation---which is the very reason we wanted to submit.

:::{.callout-tip}
Download the poster [here](/downloads/251114-BenefitOfTheWorld.pdf).
:::

Unfortunately, I was unable to attend because of a conflict in my teaching schedule. But Dr. Lisa Morgan Johnson presented on behalf of the group. She also did the lion's share of preparing the poster as well. As part of this presentation, we've prepared a page of [resources for learning more about linguistic discrimination](pages/linguistic-discrimination.html). Hopefully this is the beginning of full-fledged website, but for now we just wanted *something* to send conference attendees to for more information. 

