---
layout: post
title: "The stories behind the languages I've studied"
date: 2023-05-27 15:00:00 -0600
date-modified: last-modified
categories: 
  - Personal
---

There's a trend on linguistics Twitter right now where people are sharing the ages that they started studying/learning whatever languages they know. As I thought about the ones I know, I realized that there's a story behind each one, and like many linguists, I have a list of languages and a few-word summary of their fluency at the bottom of my CV. But the stories are much more than I'd like to explain on my CV or in a tweet. So, here are some of those stories behind the languages I've studied.

## English

My first and, for a long time, only language. Read more about my idiolect [here](/pages/idiolect).

## (Modern) Greek

In fourth grade, I was in a "gifted" program or whatever and we had a unit on Greek. I remember nothing.  

## Swahili

In fifth grade, that same gifted program had a Swahili unit. Literally the only thing I remember is the titular line from the song "Head, Shoulders, Knees, and Toes", which is *kichwa, mabega, magoti na migu*. Google Translate has *toes* as *vidole*, so I don't know what *migu* is. 

Unrelated to that, early in grad school, probably around summer 2015 or so, I thought I'd try auditing Swahili. I sat in on one class and decided I probably didn't have the time to commit.

## Portuguese

When I was 19, I started my two-year stint as a Mormon missionary in Brazil. I took some private lessons for a couple months summer 2007 from a Brazilian woman from church. When I moved there in October, I was put into an intensive language training course, which was about 9 weeks, after which I was thrust into the streets pretty much and fully immersed in the language.

It took a while for me to attain fluency, but I made it there eventually. I made a *ton* of flashcards and learned lots of words. People would joke that if anyone needed to teach a lawyer, they'd have to call me because I'm the only one that has the vocabulary! My pronunciation wasn't bad either: I could convince people that I was from Brazil---granted, I told them I was from Amapá, a remote, rural state way up in the Amazon. No one knew anyone from there, so they were often like, "Oh, so *that's* what the accent sounds like!" As I explain [here](/blog/ten-years-of-linguistics), I was in a college town for a while and inadvertently bought [a phonetics and phonology textbook](https://www.editoracontexto.com.br/produto/fonetica-e-fonologia-do-portugues-roteiro-de-estudos-e-guia-de-exercicios-nova/1496828) and learned some basic linguistics concepts from there. About a month before I was finished, I bought a [big ol' grammar book](https://editoranacional.com.br/livros-buscar-detalhe/?id=472), one that was intended for Brazilian university students studying Portuguese, and read the whole thing. Perhaps because of that book and my general attitude towards language learning at the time, I still have somewhat prescriptivist attitudes in Portuguese, and I really wish I hadn't adhered so strongly to the standard language ideology because I know I heard a *lot* of variation while living there. 

Since being back in the US, I've had relatively little opportunity to use my Portuguese. I took a grammar and a literature course as an undergrad. In grad school, I attended a conversation group. I also was briefly part of a Brazil-based research team that analyzed monkey vocalizations and I had one heck of a time trying to explain statistics in Portuguese. Mormon missionaries don't exactly need that kind of vocabulary, so that was a lot of new words. 

How is my Portuguese now? Pretty rusty. Probably not terrible and I could survive. I've forgotten a lot of the nuance on how to say certain things. I listen to podcasts occasionally and I don't understand everything, which is a little disheartening. But, again, as a missionary there are a *lot* of semantic domains that you don't ever need to talk about, so it makes sense. Maybe I just need to start busting out the vocab cards again.

## Guarani

After living in Brazil for about nine months (this was June-ish of 2009, right after I turned 20), I was transferred to Campo Grande where I encountered Guarani for the first time. I thought it was interesting and I thought I'd try to learn it. A friend had what was basically a "teach yourself Guarani" book that was written in Spanish---so I had to quickly figure out a bit of basic Spanish to read it. My dad also sent me a copy of the Book of Mormon in Guarani and basically said, "Eh, since you're learning another language anyway, might as well try this one too." So over the next few months, here and there, I learned a bit of grammar and vocabulary. This was my first time looking at a non-Indo-European language and it was fascinating to me. By the end of my time in Brazil, I had somehow managed figured out quite a bit of grammar.

When I got back to BYU, I found some old books on Guarani and used them to learn more of the grammar I hadn't figured out via translation. In Fall 2011, I also sat in on a grammar course that was intended for missionaries who had served in Paraguay speaking Guarani. I didn't do well because I really was out of my league and because I had also signed up for Mandarin that same semester. I've occasionally pecked at it and even have an [interactive Guarani dictionary](/blog/interactive-guarani-dictionary). I even submitted an abstract to LSA on templatic morphology, but it was (rightfully) rejected. I saw that they've recently added a Duolingo course in Guarani, taught in Spanish, so there's more opportunity to practice. One day, I'll get back to studying it. 

## Kichwa

After my intro to linguistics course, I went on a language documentation study abroad to Amazonian Ecuador in June--July 2011. There, I started to learn Ecuadorian (Lowland, Pastaza, etc) Kichwa. I never really got to the point of being fluent, but I had two semesters' worth of coursework done, so I had, at one point, a bit of vocabulary and a decent grasp of lots of basic grammar. Nowadays, I remember virtually nothing, but when I see my colleague Janis Nuckolls talk about her research, some things come back.

## Spanish

At some point while in Brazil, I started to study Spanish on my own. I had to know something because that Guarani book I had was written in Spanish. I've never taken formal classes though, so I don't know much. Knowing Portuguese is helpful and I tell people that my Spanish is basically Portuguese with a Spanish accent. I also have a really hard time understanding spoken Spanish, though when I was in Ecuador, I noticed that Ecuadorian Spanish was much easier. My one success story was the one time I was in Sunday School while in Ecuador and the teacher called on me to answer a question, and not only did I understand the question, but I also produced a coherent answer.

## Mandarin

While in Ecuador, a fellow study abroader had studied Chinese. I had two roommates who spoke Mandarin at the time too. And I was interested in learning more about tone. So I signed up for Mandarin and ended up taking two semesters of it. I enjoyed it. Except for the writing. I don't think we advanced very far at all because everything we learned to say we had to be able to read and write too, and learning characters was a slow process. I think by the end, I knew just shy of 500 characters. What little grammar I knew though I felt pretty comfortable with. Literally the only thing I remember today is 我有兩個會說中文的室友, "I have two roommates who can speak Chinese." Except I had to look up the characters on Google Translate. Knowing Pinyin at least has been helpful for reading Chinese names.

## K'iche'

During the Winter 2012 semester of BYU, they offered a introductory K'iche' course. I audited it and attended for a few weeks, but ultimately couldn't keep up with it and Mandarin in the same semester. (I wish had had continued, because it would have been helpful for studying Tz'utijil later on!)

## Tshiluba

Fall of 2012, I took a Field Methods course and our informant was a native speaker of [Tshiluba](https://en.wikipedia.org/wiki/Luba-Kasai_language) (aka Luba-Kasai), a Bantu language spoken in the DRC. I really enjoyed that course and spent the majority of my time documenting the TAM system. 

## Bolivian Quechua

When I started graduate school at the Univeristy of Georgia, they had just gotten, in the words of my advisor Chad Howe, a "crap-ton" of money to help their Quechua program. I was in the second cohort of students to take Quechua there. I took two semesters from Chad Howe. I then continued to third- and fourth-semester courses, which were taught by a native speaker, remotely from Bolivia. (Keep in mind, this was 2015--2016, long before remote learning had become mainstream!) The instructor didn't speak any English though and, as you may recall, I don't really speak Spanish that well, so much of the class was facilitated by a TA who was a Romance Languages PhD student and year ahead of me in school. (Hi, Bethany!) I was one of a couple students in Quechua 201 and the only student in Quechua 202. Towards the end, I was starting to achieve some semblance of fluency, and I could speak somewhat off the cuff and express most of what I wanted to, haltingly, and with lots of mistakes. I do have one line on my CV about Quechua morphology, a conference presentation from LCUGA in 2016. 

## Tz'utujil

During my first year of grad school, I took field methods again, and our informant spoken Tz'utijil. Like I did with Tshiluba, I focused on verbal morphology, but this time it was more about valency. I had quite a lot of fun with it and wrote a "grammar" of something like 60 pages. Pretty fun. 

## Dutch

In 2019, I started to study Dutch because I had been accepted to a conference in the Netherlands and I wanted to not be *that* kind of American that just expects everyone to speak English. I did what I could to study, but in a few months, while dissertating, I couldn't learn that much. While in Utrecht and Amersfoort, I did learn enough to ask people if they spoke English---which they almost always replied, "Yes, of course." However, I had really gotten into breadmaking around then and I ended up going to a corner bakery a little bit away from the touristy downtown area and when I asked the baker if she spoke English, she said, somewhat apologetically, "een beetje" ('a little bit'). That was my one chance to actually use Dutch!

Since then, I've continued studying Dutch. No real reason---I don't have plans to go back to the Netherlands---but it's fun to have something to work on. I'm using Duolingo, but I'm also reading grammar books, studying a ton of vocabulary, and listening to podcasts. I follow a few Dutch-speaking folks on Twitter and can often understand most of their tweets now. Right now, I'd say it's the language I've learned the most, other than English and Portuguese.

## Korean

Towards the end of grad school, I needed a 8000-level course, so I took Korean Linguistics, which was under the auspices of a course called "Lesser-Taught Languages." Most of the students were Korean majors or minors, and the only other grad students were both Korean. I didn't do that well in the course because I had never studied Korean at all. And my lesser-than-ideal performance shows because I remember virtually nothing from it. 

## Honorable Mentions

Languages I studied for a *very* brief time. 

* Haitian Creole: For a brief week or so in about 2012, my dad thought he was going to be doing business in Haiti, so he asked me to try and learn some Haitian Creole to help him interpret. It didn't pan out.
* German: In 2019, I applied for a job in Switzerland so I started to try and learn German. I as starting Dutch at the same time, and I soon found out I didn't get the job, so I didn't get very far.
* Ukrainian: In 2022, I started to advise a student on the sociolinguistics of Ukrainian. I thought I'd try and learn some Ukrainian to help with that. 

<br/>
Language I'd like to study in the future.

* Aymara: Aymara books are near Guarani books in the library, and I have an uncle-in-law who learned it while serving as a missionary in Bolivia. And since South American languages are cool, this would be next on my bucket list from that part of the world.
* Korean: My wife and I agreed that once we're both done with our current Duolingo courses (Dutch for me, Russian for her), we'd learn Korean together. We've watched a few Korean shows on Netflix and Korean culture is becoming more and more prevalent in the US right now anyway, so it might be handy to know.
* Norwegian: My great-great-grandfather was the end of an at least 40-generation-long line of Norwegians, specifically from the southern tip of the country. I can trace my ancestry to folks born in the 700s AD, and even the ones born in the 1200s were born only about 30 miles from where my great-great-grandfather was born. Anyway, it'd be interesting to learn Norwegian and visit the area. 

## End

Anyway, I've heard people say that the more languages you know, the harder it is to define *fluent*. That's certainly the case for me.