---
layout: post
title: LSA and ADS 2023
date: 2023-01-06 06:30:00 -0600
categories: 
  - Conferences
  - Presentations
  - Research
  - Students
  - Utah
  - West
aliases: 
    - "/ads2023"
    - "/lsa2023"
    - "/blog/lsa-and-ads-2023"
---

This week I'm in Denver at annual meetings of the Linguistic Society of America and the American Dialect Society. I gave two talks, which you can download here:

## LSA talk on *mountain* in Utah

My first talk is called "Utahns sound Utahn when they avoid sounding Utahn." Basically, I find that Utahns say *moun*[tʰɨn] more than other people do because they avoid the stigma assigned to the glottal stop in the local realization, *moun*[ʔɨn], and that has since spread to the nationwide standard *moun*[ʔn̩]. I've been very eager to talk about these ideas for a while so I hope you find them as interesting as I do.

* [Here](/downloads/230106-LSA_mountain.pptx) is the actual powerpoint file. In the notes for each slide you'll see the actual script I read from. And since the audio is embedded into the file, if you enter presentation mode and mouse over a quote, you'll hear the actual audio. 
* In case you don't need all that and you just want a PDF, [here's](/downloads/230106-LSA_mountain.pdf) that instead.

If you want to read a little more about this topic, please see my [blog post](/blog/idaho-montana-wyoming-and-utah-english-survey-results) from a few months ago with some preliminary results. 



## ADS talk on Idaho English

My other talk, "Is Idaho English really 'the epitome of Average English'?", was in collaboration with KaTrina Jackson, who unfortunately couldn't be there to help present. The quote in the title comes from Dennis Preston's 1989 book where he found that people didn't think anything of Idaho English. We examine data on Idaho English and show that it lacks stigmatized linguistic features from Utah, but also innovative features like the LBMS. It does have features that are floating under the radar though. In the end we, conclude that Idaho English does appear to be the epitome of average English.

* [Here's](/downloads/230106-ADS_Idaho_notes.pdf) a version that has the slides and the full script that I read from, in case you want to get all the nitty-gritty detail. 
* [Here](/downloads/230106-ADS_Idaho.pdf) is a PDF of the slides themselves, in case you just want that instead.

Please see my [blog post](/blog/idaho-montana-wyoming-and-utah-english-survey-results) from a few months ago which goes into a little more detail than what I had time to talk about here. 