---
layout: post
title: "10 Years of wanting to be an academic"
date: 2023-01-12 08:00:00 -0600
categories: 
  - Personal
---

Last week, I was at the LSA/ADS conferences in Denver, and it occurred to me that ten years ago this week is when I decided I wanted to be an academic.

In the summer of 2011, I went on a study abroad to Ecuador with my now-colleague Janis Nuckolls. It was a fantastic experience and really got me excited about linguistics. Afterwards, me and two other students started meeting with her as a research group. Over the next year we met weekly as we worked on the phonology of Kichwa ideophones, research that would eventually lead to [our 2016 publication in IJAL](https://www.journals.uchicago.edu/doi/10.1086/684425).[That paper may forever be my most cited publication, which is weird because it's not at all what I do for research now!]{.aside}

We got the point where Janis was ready to submit the research to a conference. So, we wrote up the abstract and submitted it to the SSILA conference, which meets concurrently with LSA, ADS, and a few other sister societies. And we got in! 

At first, I wasn't planning on going. I was engaged and the conference was less than two weeks after my wedding. I decided last minute that I really should go though. My wife helped me pick out some conference clothes (I still wear the green shirt I got then as a homage to my first conference!), I managed to get some funds from the department, and after a red-eye flight that included layovers in Denver and Philadelphia, I made it to Boston. 

Our presentation was in the very first session on that Thursday, and I remember being pretty nervous as I read my section. I didn't look up from my script once. But because the talk was over with soon after arriving to the conference, I was able to spend the the next two days wandering around attending whatever talks looked interesting. 

I'm pretty sure I ended up spending most of my time at the ADS sessions. I was still an undergrad, but I had already applied to some graduate schools with the intent of studying sociolinguistics, so I actually recognized some of the names there and I was able to put faces to names. According to my program book from that year, here are a few things I saw:

* Joseph Hill presented, in ASL, about the influence of African American English on African American Sign Language. 
* Nicole Rosen presented on the difference between Latter-day Saints and non-Latter-day Saints in Alberta.
* Dan Villarreal (and my now-colleague, Grant Eckstein) presented on intonation patterns of Latter-day Saints compared to non-Latter-day Saints when reading scripture. 
* Bill Kretzschmar presented on computational approaches to dialect mapping. (Little did I know I'd be his RA for four years!) 
* Lisa Davidson and Daniel Erker presented on hiatus resolution in American English. 
* Livia Oushiro and Ronald Mendes presented on nasal /e/ in Brazilian Portuguese
* Patricia Cukor-Avila on Texans' perceptions of regional variation
* David Durian on what we now call the LBMS in Ohio. 

It's really interesting to look through the booklet and see what talks I didn't consider but would definitely see today. It's also interesting to see where people I now know were ten years ago.

Anyway, by the end of the conference, I had caught the bug. I knew that *that* is where I wanted to be. Those were my people. In fact, it was at the next LSA/ADS I went to, which was two years later in Portland, that I got the idea for my dissertation topic. The story for that will have to wait for another blog post.

<br/>