---
layout: post
title: LSA and ADS 2025
date: 01/09/2025
categories: 
 - Conferences
 - Kohler Tapes
 - Methods
 - Presentations
 - Research
 - Students
 - Utah
aliases: 
    - "/ads2025"
    - "/lsa2025"
---

This week I'm in Philadelphia at annual meetings of the Linguistic Society of America and the American Dialect Society. I gave three talks, which you can download here, I officially started two new service positions, and I got an award! It was a busy conference for me!

## Saturday morning's ADS talk on Georgia Prelaterals

:::callout-tip
Download the slides [here](/downloads/250111-ADS2025_GAPrelats.pdf)!
:::

On Saturday morning at the ADS session, Peggy Renwick presented research on behalf of our research term on prelateral front vowels and how they've changed over time in Georgia. The talk is called "Complementary pre-lateral mergers across ethnicities and generations in Georgia." Overall, we find that the various prelateral mergers peaked and reversed at different times for Black and White speakers, and for the two *feel-fill* and *fail-fell* pairs. 


## Saturday afternon's ADS poster on Utah English

:::callout-tip
Download the poster [here](/downloads/250111-ADS2025_Kohler.pdf)!
:::

On Saturday afternoon, I presented with my student, Hallie Davidson, a poster called "Variation in Early 20th Century Utah English." This is the first time I've presented results from a collection of oral narratives I acquired called the "Kohler Tapes." I've written blog posts about [how I acquired the tapes](/blog/kohler-tapes), [the process of digitizing them](/blog/kohler-tapes-update), and [a summary of the metadata](/blog/kohler-tapes-update2), so I won't repeat that here. But, because Hallie has been working on transcribing these tapes, we finally have some really preliminary linguistic results to present. They're just impressionistic right now, nothing really conclusive, but we show that there's a lot of variation in this collection. We're excitedly working on some developments that involve training an AI model on this data so we can get the rest transcribed and we look forward to doing acoustic analysis soon!

## Sunday morning's LSA talk source separation

More info coming soon…

## Other Things

At the ADS Business Meeting, I was voted a member of the American Dialect Society Executive Committee! I replace Alicia Wassink, who was just voted President-Elect of the Linguistic Society of America. I'm excited to serve with Jessi Grieser, Nicole Rosen, and Paul Reed.

At that same meeting, I was also voted a Kurath Fund Trustee, which is a position within the Linguistic Atlas Project. I'll serve with Jennifer Cramer and Dennis Preston.

Finally, at the ADS Breakfast on Saturday morning, I received the 9t Audrey Duckert Memorial Travel Award to attend these ADS meetings. 

I'm so humbled to be considered for these positions and award! Thank you to all those who were involved! 