---
layout: aside
title: Data Visualization Workshops
redirect_from: 
    - "/dataviz"
---

# Data Visualization Workshops

In Fall of 2019, I lead a series of five workshops on data visualization. This page houses the handouts and materials for those workshops.

<br/>
<!-- These R-workshops is duplicated in pages/r-workshops -->

## [Part 1: Intro to ggplot2](/downloads/190821-intro_to_ggplot2)

*August 21, 2019*---In Part 1 of this workshop I cover the basic syntax and how to make some simple types of plots. 

<br/> 

## [Part 2: Extending your ggplot2 skills](/downloads/190828-ggplot2_intermediate)

*August 28, 2019*---Often you'll want to customize your plots in some way. So, in this workshop we cover how to mess with properties of the plots like the axes, colors, and legends to make the plot work better for you. 

### [Supplement to Part 2](/downloads/190828-ggplot2_supplement)

Apparently I had a lot to say about how to extend your ggplot2 skills, so I ended up creating a supplement with lots of additional detail on how to modify your plots.

<br/> 

## [Custom Themes](/downloads/190904-ggplot2_custom_themes)

*September 4, 2019*--Based on a popular [blog post](/blog/2016-12-16-custom-themes-in-ggplot2) I wrote, this workshop wraps all customization methods together and shows how to create your own themes.

### [Supplement: A detailed look at `ggplot2::theme`](/downloads/190904-ggplot2_theme)

As I was preparing for the custom themes workshop, I got a little carried away illustrating all the components of the `theme` function. I decided to simplify that portion of the workshop and create this separate handout that just focuses on `theme`. It is not yet finished, but it may be of some help to people (including myself!).

<br/>

## *Fidelity, integrity, and sophistication: Edward Tufte’s principles of data visualization*

*October 16, 2019*---In this workshop, I introduce a few key concepts from Edward Tufte's book, *The Visual Display of Quantitative Information* such as graphical integrity, proportional ink, data-ink ratio, removing redundant material, and general graphical sophistication. Basically, the workshop could be thought of as, "How not to make awful plots."

<br/>

## [*Send the right message: The dos and don’ts of COLOR in data visualization*](/downloads/191023-color.pdf)

*October 23, 2019*---Meagan Duever, GIS Librarian at UGA will help me lead this workshop. We talk about general principles of color in data visualization, introduce a whole bunch of nice color palettes, and demonstrate how to customize your colors in ArcMap, QGIS, Excel, and R.

<br/>

## Older versions

You may also be interested in the 2018 versions of some of these workshops that I gave (Part 1 [Rmarkdown](/downloads/180216-ggplot2-part1) and [PDF](/downloads/180216-ggplot2-part1.pdf) and Part 2 [RMarkdown](/downloads/180223-ggplot2-part2) and [PDF](/downloads/180223-ggplot2-part2.pdf)). An older version from 2017 that combines elements of Parts 1 and 2 can be found here as a [PDF](/downloads/171012-ggplot2_handout.pdf) or [RMarkdown](/downloads/171012-ggplot2) file.