---
title: "Resources for Learning More about Linguistic Discrimination"
author: "Joey Stanley"
date: "2025-10-29"
date-modified: last-modified
format:
  html:
    toc: true
number-sections: true
---

This page contains resources to help you learn more about linguistic discrimination. These resources were compiled by the Coalition Against Linguistic Discrimination (CALD) at Brigham Young University. The page is in its infancy, so there are not too many things yet, but we hope to add more resources soon. For more information about CALD, please contact Joey Stanley at joey_stanley@byu.edu.


## [Universal Declaration of Linguistic Rights](https://unesdoc.unesco.org/ark:/48223/pf0000104267_eng)

This document was drafted in 1996 and was signed by several non-government organizations to support basic linguistic rights, particularly for endangered languages.

## Similar Projects

### [The Accentism Project](https://accentism.org)

This project has the aim of uncovering and challenging such discrimination in everyday life. The site provides the opportunity for people to share their own stories and experiences of language-based bias, prejudice, and discrimination.

This site contains first-hand accounts by those who have experienced linguistic discrimination (paprticularly in the United Kingdom), a summary of research that has been done, a list of accentism being featured in the media, and training for businesses. 

### [CIRCE Project](https://www.circe-project.eu)

The Counteracting Accent Discrimination in Education Project has three goals: 

1. Investigate how accent discrimination takes place in schools, and how it impacts pupils’ and students life.

1. Provide students and teachers with resources to develop greater tolerance towards accent variation.

1. Raise awareness about accent discrimination in school and university settings.

The project website contains numerous resources related to these goals, including a seminar series and videos showcasing powerful stories and compelling videos that tackle linguistic discrimination and sound-based racism.

### [Accent Bias in Britain](https://accentbiasbritain.org)

This project examines current attitudes to accents in Britain, and investigates whether unconscious accent bias plays a role in how job candidates are evaluated. The project has three goals:

1. To identify whether accent bias exists in professional hiring contexts, and what impacts this can have.

1. To understand the causes and effects of any bias and provide an informed, evidence-based understanding of attitudes to accents in the UK today.

1. To test tools, training and techniques that can be used to combat bias.

The site also includes practical resources, reports of their research, and datasets to explore. 

### [Speaking of Prejudice](https://hosting.northumbria.ac.uk/languageattitudesengland/)

This project "investigates deeply embedded (implicit) and self-reported attitudes towards accents spoken in the north and the south of England." One main purpose for the project is to raise awareness of the "social and educational implications of listeners’ conscious and more deeply embedded implicit prejudices towards particular accents".

### [Linguistic Bias Working Group](https://depts.washington.edu/lxbias/resources/)

A group at the University of Washington, led by Betsy Evans, Russell Hugo, and Alex Panicacci, that "aims to engage all members of the UW community in the acknowledgment of language diversity on campus and the role of linguistic bias in diversity, equity, and inclusion."

### [ROLE Collective](https://www.rolecollective.org)

The ROLE Collective is a consortium of scholars working against harmful language beliefs in policy and practice, within academia and beyond. They have a collection of resources for researchers and educators, including publications, presentations, mutlimedia content, readings, and other materials. 

## Audio Resources

### [Vocal Fries Podcast](https://vocalfriespod.com)

This podcast about linguistic discrimination by Carrie Gillon and Megan Figueroa teaches you "how not to be an asshole about language."

### [Accentricity Podcast](https://www.accentricity-podcast.com)

A podcast by Sadie Ryan about why there is no such thing as bad grammar, no language is more important than any other language, and every voice is valid.

## Other Resources

### [Community-Engaged Scholarship Toolkit](https://www.asanet.org/public-engagement/sociology-action-network/community-engaged-scholarship-toolkit/)

This site provides resources for academics on how to incorporate community-engaged scholarship in tenure and promotion materials. 

### [Speech Language Varieties](https://lmj351.wixsite.com/speechvarieties)

This is a site created by Dr. Lisa Morgan Johnson and her students at Brigham Young University. It is meant for speech pathologists working with people with select varieties of English to help them distinguish dialect from disorder. 

