---
layout: post
title: "Introducing VoxHumana: A spiritual sucessor to DARLA"
date: 2026-07-23 08:12:00 -0600
date-modified: last-modified
categories: 
  - Methods
  - Phonetics
---

I am thrilled to announce a new online tool I've created called *VoxHumana* (*VxH*). With VoxHumana, you upload an audio file, and it'll send it through Whisper for automatic transcription, then to the Montreal Forced Aligner (MFA) for forced alignment, and then through new-fave for automatic formant extraction. With VxH, you can take raw audio and get a spreadsheet of acoustic measurements. 

VxH is designed to be a "spiritual successor" to DARLA. By that, I mean that it is clearly inspired by DARLA but is not a direct continuation of it. VxH does much of what DARLA could do: transcription, forced alignment, and formant extraction. But it uses the latest software for each one. Instead of an in-house transcription method, VxH uses Whisper. Instead of MFA version 1.X, VxH uses MFA version 2.x (with version 3.x coming soon). And instead of FAVE-Extract, it uses new-fave. 

To be clear, there is very little that VxH does that these component parts don't do already. There is no in-house processing other than what Whisper, MFA, and new-fave offer. VxH literally strings the three pieces of software together into an easy-to-use interface. 

