---
layout: post
title: LSA and ADS 2026
date: 01/09/2026
categories: 
 - Conferences
 - GIS
 - Presentations
 - Research
 - Utah
aliases: 
    - "/ads2026"
    - "/lsa2026"
---

This week I'm in New Orleans at the annual meetings of the Linguistic Society of America and the American Dialect Society. I will give three presentations, which you can download here. 

<br/>

## Friday morning's LSA talk on Meta-Linguistic Commentary

:::callout-tip
Download the slides [here](/downloads/260108-LSA2026_metalinguistic.pdf). 
:::

On Friday morning, I presented on a talk called "Towards a taxonomy of meta-linguistic commentary: The case of Utah English." I'm venturing out into qualitative data analysis because the comments I hear about Utah English are juicy! The gist is that the vibes I get from Utahns about their own variety are different than the vibes I get from others about their varieties. So, is there a way to quantify this abstract part of language regard? I'm not there yet, but I show a few categories of comments that seem to be common in Utah. Perhaps I can soon start to quantify things and put a number on those different vibes.


## Friday morning's ADS poster on Pittsburghese

:::callout-tip
Download the poster [here](/downloads/260108-ADS2026_Pittsburghese.pdf)!
:::

At the ADS poster session, Scott Kiesling had a poster called "Measuring Pittsburgh Neighborhoods with the Archive of Pittsburgh Language and Speech (APLS)". Scott was involved in data collection in Pittsburgh in the early 2000s and recently, Dan Villarreal created [APLS](https://apls.pitt.edu) to make it easy to search and work with that data. We test whether a dozen or so phonological variables are conditioned by neighborhood. We do find some evidence and we can see how these variables co-occur. This is my first time venturing into this dialect area, so it's pretty exciting to me to work with this new (to me) dataset!


## Sunday morning's ADS talk on regional grammatical variation

:::callout-tip
Download the slides [here](/downloads/260111-ADS2026_youtube.pdf)!
:::

At ADS, I presented some research I've been working on with Brett Hashimoto, who is my colleague at BYU, and Jack Grieve who is at the University of Birmingham. Brett has access to a monster corpus of transcriptions from YouTube videos of town hall meetings and other local meetings. Following the methods in Grieve (2016), we created maps for each variant of something like 135 lexico-grammatical variables. We found lots of interesting distribution patterns. At this point, we're just showing maps but we hope to do some cluster analysis soon and see how these variables co-occur.  